# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-27 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphinx_domains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sphinxdomain',
            name='anchor',
            field=models.CharField(max_length=4092, verbose_name='Anchor'),
        ),
        migrations.AlterField(
            model_name='sphinxdomain',
            name='display_name',
            field=models.CharField(max_length=4092, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='sphinxdomain',
            name='doc_name',
            field=models.CharField(max_length=4092, verbose_name='Doc Name'),
        ),
        migrations.AlterField(
            model_name='sphinxdomain',
            name='name',
            field=models.CharField(max_length=4092, verbose_name='Name'),
        ),
    ]
