# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-13 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphinx_domains', '0003_additional_indexed_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sphinxdomain',
            name='build',
            field=models.IntegerField(null=True, verbose_name='Build id'),
        ),
    ]
