# Generated by Django 1.11.20 on 2019-06-25 23:18
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_add-build-field'),
        ('sphinx_domains', '0004_add-build-field'),
    ]

    operations = [
        migrations.AddField(
            model_name='sphinxdomain',
            name='html_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sphinx_domains', to='projects.HTMLFile'),
        ),
    ]
