# Generated by Django 2.2.14 on 2020-07-13 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sphinx_domains', '0005_htmlfile-sphinx-domain-integration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sphinxdomain',
            options={'get_latest_by': 'modified'},
        ),
    ]
