# Generated by Django 3.2.13 on 2022-08-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sphinx_domains", "0006_update_timestamp_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sphinxdomain",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
