# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-04 13:48
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0009_add-error-to-promos'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporterpromo',
            name='sold_clicks',
            field=models.IntegerField(default=0, verbose_name='Sold Clicks'),
        ),
        migrations.AlterField(
            model_name='supporterpromo',
            name='sold_impressions',
            field=models.IntegerField(default=1000000, verbose_name='Sold Impressions'),
        ),
    ]
