# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-14 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0011_add-theme-filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporterpromo',
            name='display_type',
            field=models.CharField(choices=[(b'doc', b'Documentation Pages'), (b'site-footer', b'Site Footer'), (b'search', b'Search Pages'), (b'error', b'Error Pages'), (b'community', b'Community Only Pages')], default=b'doc', max_length=200, verbose_name='Display Type'),
        ),
    ]
