# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-14 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0011_add-theme-filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporterpromo',
            name='community',
            field=models.BooleanField(default=False, verbose_name='Community Ad'),
        ),
    ]
