# Generated by Django 3.2.13 on 2022-05-31 15:22

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_track_status_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pageview",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
