# Generated by Django 3.2.13 on 2022-07-06 19:29
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("analytics", "0004_merge_duplicate_records"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="pageview",
            constraint=models.UniqueConstraint(
                condition=models.Q(("version", None)),
                fields=("project", "path", "date", "status"),
                name="analytics_pageview_constraint_unique_without_optional",
            ),
        ),
    ]
