# Generated by Django 3.2.19 on 2023-06-13 11:12
import datetime

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("analytics", "0006_alter_pageview_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pageview",
            name="date",
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
    ]
