# Generated by Django 5.2.3 on 2025-08-06 18:28

import django.db.models.deletion
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0007_index_on_pageview_date"),
        ("builds", "0064_healthcheck"),
        ("projects", "0152_create_gh_app_integration"),
    ]

    safe = Safe.before_deploy()

    operations = [
        migrations.AlterField(
            model_name="pageview",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="page_views",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="pageview",
            name="version",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="page_views",
                to="builds.version",
                verbose_name="Version",
            ),
        ),
    ]
