# Generated by Django 5.2.9 on 2025-12-18 17:29

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()
    dependencies = [
        ("analytics", "0007_index_on_pageview_date"),
        ("projects", "0157_disable_builds_after_n_failed"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenTelemetryConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False, help_text="Enable OpenTelemetry metrics for this project"
                    ),
                ),
                (
                    "endpoint_url",
                    models.URLField(
                        blank=True,
                        help_text="Endpoint URL (e.g., https://prometheus-xxx.grafana.net/otlp/v1/metrics)",
                        max_length=1024,
                        null=True,
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        help_text="Grafana Cloud API Key (encrypted in production)",
                        max_length=512,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otel_config",
                        to="projects.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "OpenTelemetry Configuration",
                "verbose_name_plural": "OpenTelemetry Configurations",
            },
        ),
    ]
