# Generated by Django 5.2.9 on 2026-01-20 15:20

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()
    dependencies = [
        ("analytics", "0007_index_on_pageview_date"),
        ("builds", "0066_add_buildconfig_model"),
        ("projects", "0157_disable_builds_after_n_failed"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["project", "date", "status"],
                include=("path", "view_count"),
                name="analytics_pageview_issue_12686",
            ),
        ),
    ]
