comment: off
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
codecov:
  require_ci_to_pass: false
github_checks:
  annotations: false
