version: 2
formats: all
sphinx:
  configuration: docs/conf.py
python:
  install:
    - requirements: requirements/pip.txt
    - requirements: requirements/docs.txt

search:
  ignore:
    # Internal documentation
    - development/design/*
    - search.html
    - 404.html
  ranking:
    # Deprecated content
    api/v1.html: -1
    config-file/v1.html: -1

    # Useful content, but not something we want most users finding
    custom_installs/*: -6
    changelog.html: -6
