# Custom build commands to build and publish a docusaurus project
#
# To bootstrap an example documentation project in docs/ for this template,
# you can use the following npx command:
#
#   npx create-docusaurus@latest docs classic
#
# Introduction to custom build commands:
# https://docs.readthedocs.io/en/stable/build-customization.html
#
# Complete config file reference:
# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

build:
  os: ubuntu-22.04
  tools:
    nodejs: "18"

  # We assume that a docusaurus project exists in docs/
  commands:
    # Install Docusaurus and its dependencies
    - cd docs/ && npm install
    # Build the site
    - cd docs/ && npm run build
    # Copy generated files into Read the Docs output directory
    - mkdir --parents $READTHEDOCS_OUTPUT/html/
    - cp --recursive docs/build/* $READTHEDOCS_OUTPUT/html/
