# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-01 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('builds', '0009_added_external_version_type'),
        ('projects', '0044_auto_20190703_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('query', models.CharField(max_length=4092, verbose_name='Query')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_queries', to='projects.Project')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_queries', to='builds.Version', verbose_name='Version')),
            ],
            options={
                'verbose_name': 'Search query',
                'verbose_name_plural': 'Search queries',
            },
        ),
    ]
