# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-28 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_pageview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='view_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
