# Generated by Django 4.2.16 on 2024-09-23 20:22

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.always()
    dependencies = [
        ("search", "0005_alter_searchquery_id"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="searchquery",
            index=models.Index(
                fields=["modified", "project", "version"],
                name="search_sear_modifie_3ac4ab_idx",
            ),
        ),
    ]
