# Generated by Django 1.9.12 on 2017-10-27 12:56
from django.db import migrations
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0019_add-features"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIProject",
            fields=[],
            options={
                "proxy": True,
            },
            bases=("projects.project",),
        ),
    ]
