# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-10-27 12:56
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_add-features'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIProject',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('projects.project',),
        ),
    ]
