# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-12-21 16:30
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_add-webhook-deprecation-feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrelationship',
            name='alias',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Alias', db_index=False),
        ),
    ]
