# Generated by Django 1.9.12 on 2017-12-21 16:30
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0021_add-webhook-deprecation-feature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectrelationship",
            name="alias",
            field=models.SlugField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Alias",
                db_index=False,
            ),
        ),
    ]
