# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-12-21 16:31
from __future__ import unicode_literals

from django.db import migrations
from django.utils.text import slugify


class Migration(migrations.Migration):
    def migrate_data(apps, schema_editor):
        ProjectRelationship = apps.get_model("projects", "ProjectRelationship")
        for rel in ProjectRelationship.objects.all():
            if rel.alias:
                print('Changing ProjectRelationship alias: {}:{}'.format(rel, rel.alias))
                rel.alias = slugify(rel.alias)
                rel.save()

    dependencies = [
        ('projects', '0022_add-alias-slug'),
    ]

    operations = [
        migrations.RunPython(migrate_data)
    ]
