# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-03-04 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_migrate-alias-slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='abandoned_mail_sent',
            field=models.BooleanField(default=False),
        ),
      
    ]
