# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-12-22 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_migrate-alias-slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='canonical',
            field=models.BooleanField(default=False, help_text='This Domain is the primary one where the documentation is served from'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='count',
            field=models.IntegerField(default=0, help_text='Number of times this domain has been hit'),
        ),
        migrations.AlterField(
            model_name='project',
            name='allow_promos',
            field=models.BooleanField(default=True, help_text='If unchecked, users will still see community ads.', verbose_name='Allow paid advertising'),
        ),
        migrations.AlterField(
            model_name='project',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='URL that documentation is expected to serve from.', verbose_name='Canonical URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='comment_moderation',
            field=models.BooleanField(default=False, verbose_name='Comment Moderation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='conf_py_file',
            field=models.CharField(blank=True, default='', help_text='Path from project root to <code>conf.py</code> file (ex. <code>docs/conf.py</code>). Leave blank if you want us to find it for you.', max_length=255, verbose_name='Python configuration file'),
        ),
        migrations.AlterField(
            model_name='project',
            name='container_mem_limit',
            field=models.CharField(blank=True, help_text='Memory limit in Docker format -- example: <code>512m</code> or <code>1g</code>.', max_length=10, null=True, verbose_name='Container memory limit'),
        ),
        migrations.AlterField(
            model_name='project',
            name='copyright',
            field=models.CharField(blank=True, help_text='Project copyright information.', max_length=255, verbose_name='Copyright'),
        ),
        migrations.AlterField(
            model_name='project',
            name='default_version',
            field=models.CharField(default=b'latest', help_text='The version of your project that / redirects to.', max_length=255, verbose_name='Default version'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='The reStructuredText description of the project.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='has_valid_clone',
            field=models.BooleanField(default=False, help_text='This project has been successfully cloned.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='has_valid_webhook',
            field=models.BooleanField(default=False, help_text='This project has been built with a webhook.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='install_project',
            field=models.BooleanField(default=False, help_text='Install your project inside a virtualenv using <code>setup.py install</code>.', verbose_name='Install Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='num_major',
            field=models.IntegerField(blank=True, default=2, help_text='2 means supporting 3.X.X and 2.X.X, but not 1.X.X.', null=True, verbose_name='Number of Major versions'),
        ),
        migrations.AlterField(
            model_name='project',
            name='num_minor',
            field=models.IntegerField(blank=True, default=2, help_text='2 means supporting 2.2.X and 2.1.X, but not 2.0.X.', null=True, verbose_name='Number of Minor versions'),
        ),
        migrations.AlterField(
            model_name='project',
            name='num_point',
            field=models.IntegerField(blank=True, default=2, help_text='2 means supporting 2.2.2 and 2.2.1, but not 2.2.0.', null=True, verbose_name='Number of Point versions'),
        ),
        migrations.AlterField(
            model_name='project',
            name='path',
            field=models.CharField(editable=False, help_text='The directory where <code>conf.py</code> lives.', max_length=255, verbose_name='Path'),
        ),
        migrations.AlterField(
            model_name='project',
            name='privacy_level',
            field=models.CharField(choices=[('public', 'Public'), ('protected', 'Protected'), ('private', 'Private')], default='public', help_text='Level of privacy that you want on the project. Protected means public but not in listings. Note that the project documentation is still seen by everyone, <a href="http://docs.readthedocs.io/en/latest/privacy.html" target="_blank">more info</a>.', max_length=20, verbose_name='Privacy Level'),
        ),
        migrations.AlterField(
            model_name='project',
            name='programming_language',
            field=models.CharField(blank=True, choices=[('words', 'Only Words'), ('py', 'Python'), ('js', 'JavaScript'), ('php', 'PHP'), ('ruby', 'Ruby'), ('perl', 'Perl'), ('java', 'Java'), ('go', 'Go'), ('julia', 'Julia'), ('c', 'C'), ('csharp', 'C#'), ('cpp', 'C++'), ('objc', 'Objective-C'), ('other', 'Other')], default='words', help_text='The primary programming language the project is written in.', max_length=20, verbose_name='Programming Language'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True, help_text="The project's homepage.", verbose_name='Project homepage'),
        ),
        migrations.AlterField(
            model_name='project',
            name='repo',
            field=models.CharField(help_text='Hosted documentation repository URL.', max_length=255, verbose_name='Repository URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='version',
            field=models.CharField(blank=True, help_text='Project version these docs apply to, i.e. 1.0a.', max_length=100, verbose_name='Version'),
        ),
    ]
