# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-26 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import readthedocs.projects.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_show-version-warning-existing-projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSHKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.TextField(blank=True, help_text='Add this to your version control to give us access.', null=True, verbose_name='Public SSH Key')),
                ('private_key', models.TextField(blank=True, null=True, verbose_name='Private SSH Key')),
            ],
            bases=(readthedocs.projects.mixins.SSHKeyGenMixin, models.Model),
        ),
        migrations.AddField(
            model_name='sshkey',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
