# Generated by Django 1.9.13 on 2018-06-29 15:53
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0025_show-version-warning-existing-projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="ad_free",
            field=models.BooleanField(
                default=False,
                help_text="If checked, do not show advertising for this project",
                verbose_name="Ad-free",
            ),
        ),
    ]
