# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-27 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_add_htmlfile_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedfile',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='Modified date'),
            preserve_default=False,
        ),
    ]
