# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-14 21:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_remove_json_with_html_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLFile',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('projects.importedfile',),
        ),
        migrations.AddField(
            model_name='importedfile',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2018, 9, 14, 21, 10, 26, 231002), verbose_name='Modified date'),
            preserve_default=False,
        ),
    ]
