# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-02 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_change-max-length-project-slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='url',
            field=models.URLField(blank=True, help_text='URL to send the webhook to', max_length=600),
        ),
    ]
