# Generated by Django 1.11.16 on 2018-11-01 14:37
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0030_change-max-length-project-slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="importedfile",
            name="modified_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Modified date"),
        ),
    ]
