# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 23:12
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_add_modified_date_importedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='url',
            field=models.URLField(blank=True, help_text='URL to send the webhook to', max_length=600),
        ),
    ]
