# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_add_modified_date_importedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLFile',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('projects.importedfile',),
        ),
    ]
