# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 12:20
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_add_environment_variables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='copyright',
        ),
        migrations.RemoveField(
            model_name='project',
            name='django_packages_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='mirror',
        ),
        migrations.RemoveField(
            model_name='project',
            name='num_major',
        ),
        migrations.RemoveField(
            model_name='project',
            name='num_minor',
        ),
        migrations.RemoveField(
            model_name='project',
            name='num_point',
        ),
        migrations.RemoveField(
            model_name='project',
            name='suffix',
        ),
        migrations.RemoveField(
            model_name='project',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='project',
            name='version',
        ),
    ]
