# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-22 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_remove-auto-doctype'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLFile',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('projects.importedfile',),
        ),
    ]
