# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-13 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_update-doctype-helptext'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_abandoned',
            field=models.BooleanField(default=False, verbose_name='Is abandoned'),
        ),
    ]
