# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-23 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_update-doctype-helptext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedfile',
            name='path',
            field=models.CharField(max_length=4096, verbose_name='Path'),
        ),
    ]
