# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_index-repo-field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentvariable',
            name='value',
            field=models.CharField(help_text='Value of the environment variable', max_length=2048),
        ),
    ]
