# Generated by Django 1.11.20 on 2019-04-16 18:43
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0041_index-repo-field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="environmentvariable",
            name="value",
            field=models.CharField(help_text="Value of the environment variable", max_length=2048),
        ),
    ]
