# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-13 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_increase_env_variable_value_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedfile',
            name='build',
            field=models.IntegerField(null=True, verbose_name='Build id'),
        ),
    ]
