# Generated by Django 1.11.21 on 2019-06-13 18:03
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0042_increase_env_variable_value_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="importedfile",
            name="build",
            field=models.IntegerField(null=True, verbose_name="Build id"),
        ),
    ]
