# Generated by Django 2.2.11 on 2020-04-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_auto_20190703_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='max_concurrent_builds',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum concurrent builds allowed for this project'),
        ),
    ]
