# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-17 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_auto_20190703_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='show_version_warning',
            field=models.BooleanField(default=False, help_text='Show a warning banner with a link to the stable version on not stable versions, except for latest.', verbose_name='Show version warning'),
        ),
    ]
