# Generated by Django 2.2.10 on 2020-04-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_project_max_concurrent_builds'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='urlconf',
            field=models.CharField(default=None, help_text='Supports the following keys: language, version, subproject, filename.An example `/<language>/<version>/<filename>', max_length=255, null=True, verbose_name='Documentation URL Configuration'),
        ),
    ]
