# Generated by Django 2.2.12 on 2020-05-01 00:13
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0046_domain_hsts_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhook",
            name="url",
            field=models.URLField(help_text="URL to send the webhook to", max_length=600),
        ),
    ]
