# Generated by Django 2.2.12 on 2020-05-04 18:41
from django.db import migrations
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0047_webhook_url_set_blank_default"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="version_privacy_level",
        ),
    ]
