# Generated by Django 2.2.12 on 2020-05-04 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_webhook_url_set_blank_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='version_privacy_level',
        ),
    ]
