# Generated by Django 2.2.10 on 2020-05-21 22:18
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0048_remove_version_privacy_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="external_builds_enabled",
            field=models.BooleanField(
                default=False,
                help_text='More information in <a href="https://docs.readthedocs.io/en/latest/guides/autobuild-docs-for-pull-requests.html">our docs</a>',
                null=True,
                verbose_name="Build pull requests for this project",
            ),
        ),
    ]
