# Generated by Django 2.2.10 on 2020-05-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_remove_version_privacy_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='urlconf',
            field=models.CharField(default=None, help_text='Supports the following keys: $language, $version, $subproject, $filename. An example `$language/$version/$filename`.https://docs.djangoproject.com/en/2.2/topics/http/urls/#path-converters', max_length=255, null=True, verbose_name='Documentation URL Configuration'),
        ),
    ]
