# Generated by Django 2.2.12 on 2020-06-01 17:21
from django.db import migrations
from django_safemigrate import Safe


def forwards_func(apps, schema_editor):
    """Make all external_builds_enabled fields not none."""
    Project = apps.get_model("projects", "Project")
    (Project.objects.filter(external_builds_enabled=None).update(external_builds_enabled=False))


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0051_project_urlconf_feature"),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
