# Generated by Django 2.2.12 on 2020-06-01 17:27
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0052_migrate_null_external_builds_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="external_builds_enabled",
            field=models.BooleanField(
                default=False,
                help_text='More information in <a href="https://docs.readthedocs.io/en/latest/guides/autobuild-docs-for-pull-requests.html">our docs</a>',
                verbose_name="Build pull requests for this project",
            ),
        ),
    ]
