# Generated by Django 2.2.12 on 2020-06-11 23:55
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0054_urlconf_blank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Short description of this project",
                verbose_name="Description",
            ),
        ),
    ]
