# Generated by Django 2.2.12 on 2020-06-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0054_urlconf_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='analytics_disabled',
            field=models.BooleanField(default=False, help_text='Disable Google Analytics completely for this project (requires rebuilding documentation)', verbose_name='Disable Analytics'),
        ),
    ]
