# Generated by Django 2.2.14 on 2020-07-13 20:00
from django.db import migrations
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0057_add_page_rank"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="environmentvariable",
            options={"get_latest_by": "modified"},
        ),
    ]
