# Generated by Django 2.2.12 on 2020-07-21 18:21
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0060_make_rank_not_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="importedfile",
            name="ignore",
            field=models.BooleanField(
                null=True, verbose_name="Ignore this file from operations like indexing"
            ),
        ),
    ]
