# Generated by Django 2.2.12 on 2020-07-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0060_make_rank_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedfile',
            name='ignore',
            field=models.BooleanField(null=True, verbose_name='Ignore this file from operations like indexing'),
        ),
    ]
