import django_extensions.db.fields

# Generated by Django 2.2.16 on 2020-09-10 22:37
from django.db import migrations
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0062_add_ssl_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, null=True, verbose_name="created"
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
    ]
