# Generated by Django 2.2.12 on 2020-10-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0063_extend_domain_from_timestamp_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='environmentvariable',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created')},
        ),
        migrations.AlterField(
            model_name='feature',
            name='default_true',
            field=models.BooleanField(default=False, verbose_name='Default all past projects to True'),
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='default_true',
            new_name='past_default_true',
        ),
        migrations.AddField(
            model_name='feature',
            name='future_default_true',
            field=models.BooleanField(default=False, verbose_name='Default all future projects to True'),
        ),
    ]
