# Generated by Django 2.2.16 on 2020-10-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0063_extend_domain_from_timestamp_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='privacy_level',
            field=models.CharField(choices=[('public', 'Public'), ('protected', 'Protected'), ('private', 'Private')], default='public', help_text='Should the project dashboard be public?', max_length=20, verbose_name='Privacy Level'),
        ),
    ]
