# Generated by Django 2.2.16 on 2020-10-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0064_add_feature_future_default_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='active',
            field=models.BooleanField(default=True, help_text='Is this domain active?', null=True, verbose_name='Active'),
        ),
    ]
