# Generated by Django 2.2.16 on 2020-10-01 18:00
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0064_add_feature_future_default_true"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="privacy_level",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("protected", "Protected"),
                    ("private", "Private"),
                ],
                default="public",
                help_text="Should the project dashboard be public?",
                max_length=20,
                verbose_name="Privacy Level",
            ),
        ),
    ]
