# Generated by Django 2.2.16 on 2020-11-19 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0066_make_imported_file_slug_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importedfile',
            name='slug',
        ),
    ]
