# Generated by Django 2.2.16 on 2020-11-19 14:53
from django.db import migrations
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0067_change_max_length_feature_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="importedfile",
            name="slug",
        ),
    ]
