# Generated by Django 2.2.19 on 2021-03-17 15:23
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0069_migrate_protected_projects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importedfile",
            name="md5",
            field=models.CharField(max_length=255, null=True, verbose_name="MD5 checksum"),
        ),
    ]
