# Generated by Django 2.2.17 on 2021-01-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0069_migrate_protected_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='external_builds_privacy_level',
            field=models.CharField(choices=[('public', 'Public'), ('protected', 'Protected'), ('private', 'Private')], default='private', null=True, help_text='Should builds from pull requests be public?', max_length=20, verbose_name='Privacy level of builds from pull requests'),
        ),
        migrations.AlterField(
            model_name='project',
            name='external_builds_enabled',
            field=models.BooleanField(default=False, help_text='More information in <a href="https://docs.readthedocs.io/page/guides/autobuild-docs-for-pull-requests.html">our docs</a>', verbose_name='Build pull requests for this project'),
        ),
    ]
