# Generated by Django 2.2.20 on 2021-04-15 18:40
from django.db import migrations
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0071_add_env_var_privacy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="importedfile",
            name="md5",
        ),
    ]
