# Generated by Django 2.2.23 on 2021-06-04 00:05
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0073_remove_protected_privacy_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="modified_date",
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name="Modified date"),
        ),
        migrations.AlterField(
            model_name="project",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Publication date"
            ),
        ),
    ]
