# Generated by Django 2.2.24 on 2021-06-17 12:14

from django.db import migrations


def migrate_data(apps, schema_editor):
    RemoteRepository = apps.get_model('oauth', 'RemoteRepository')
    queryset = RemoteRepository.objects.filter(project__isnull=False).select_related('project').only('pk', 'project')
    for rr in queryset.iterator():
        rr.project.remote_repository_id = rr.pk
        rr.project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0076_project_remote_repository'),
    ]

    operations = [
        migrations.RunPython(migrate_data),
    ]
