# Generated by Django 2.2.24 on 2021-08-04 17:52

from django.db import migrations, models
import readthedocs.projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0080_historicalproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='external_builds_enabled',
            field=models.BooleanField(default=False, help_text='More information in <a href="https://docs.readthedocs.io/page/pull-requests.html">our docs</a>.', verbose_name='Build pull requests for this project'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='external_builds_privacy_level',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default=readthedocs.projects.models.default_privacy_level, help_text='Allow public access to builds from pull requests?', max_length=20, null=True, verbose_name='Privacy level of Pull Requests'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='privacy_level',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', help_text='Allow public access to your project dashboard, build pages, and versions list? More information in <a href="https://docs.readthedocs.io/page/commercial/privacy-level.html">our docs</a>.', max_length=20, verbose_name='Dashboard Privacy Level'),
        ),
        migrations.AlterField(
            model_name='project',
            name='external_builds_enabled',
            field=models.BooleanField(default=False, help_text='More information in <a href="https://docs.readthedocs.io/page/pull-requests.html">our docs</a>.', verbose_name='Build pull requests for this project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='external_builds_privacy_level',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default=readthedocs.projects.models.default_privacy_level, help_text='Allow public access to builds from pull requests?', max_length=20, null=True, verbose_name='Privacy level of Pull Requests'),
        ),
        migrations.AlterField(
            model_name='project',
            name='privacy_level',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', help_text='Allow public access to your project dashboard, build pages, and versions list? More information in <a href="https://docs.readthedocs.io/page/commercial/privacy-level.html">our docs</a>.', max_length=20, verbose_name='Dashboard Privacy Level'),
        ),
    ]
