import django.utils.timezone
import django_extensions.db.fields

# Generated by Django 2.2.24 on 2021-09-27 18:11
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0082_add_extra_history_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebHookEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("build:triggered", "Build triggered"),
                            ("build:passed", "Build passed"),
                            ("build:failed", "Build failed"),
                        ],
                        max_length=256,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="emailhook",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
                null=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emailhook",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified", null=True
            ),
        ),
        migrations.AddField(
            model_name="webhook",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
                null=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="webhook",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified", null=True
            ),
        ),
        migrations.AddField(
            model_name="webhook",
            name="payload",
            field=models.TextField(
                blank=True,
                help_text='JSON payload to send to the webhook. Check <a href="https://docs.readthedocs.io/page/build-notifications.html#variable-substitutions-reference">the docs</a> for available substitutions.',
                max_length=25000,
                null=True,
                verbose_name="JSON payload",
            ),
        ),
        migrations.AddField(
            model_name="webhook",
            name="secret",
            field=models.CharField(
                blank=True,
                help_text="Secret used to sign the payload of the webhook",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="url",
            field=models.URLField(
                help_text="URL to send the webhook to",
                max_length=600,
                verbose_name="URL",
            ),
        ),
        migrations.AddField(
            model_name="webhook",
            name="events",
            field=models.ManyToManyField(
                help_text="Events to subscribe",
                related_name="webhooks",
                to="projects.WebHookEvent",
            ),
        ),
    ]
