# Generated by Django 2.2.24 on 2021-09-27 20:43
from django.db import migrations
from django_safemigrate import Safe


def forwards_func(apps, schema_editor):
    """Create supported events for webhooks."""
    WebHookEvent = apps.get_model("projects", "WebHookEvent")
    for event in ["build:triggered", "build:failed", "build:passed"]:
        WebHookEvent.objects.get_or_create(name=event)


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0083_init_generic_webhooks"),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
