# Generated by Django 2.2.25 on 2021-12-21 09:35
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0085_subscribe_old_webhooks_to_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="is_spam",
            field=models.NullBooleanField(
                default=None,
                help_text="Manually marked as (not) spam",
                verbose_name="Is spam?",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="is_spam",
            field=models.NullBooleanField(
                default=None,
                help_text="Manually marked as (not) spam",
                verbose_name="Is spam?",
            ),
        ),
    ]
