# Generated by Django 3.2.11 on 2022-01-24 17:45
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0086_is_spam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproject",
            name="is_spam",
            field=models.BooleanField(
                default=None,
                help_text="Manually marked as (not) spam",
                null=True,
                verbose_name="Is spam?",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_spam",
            field=models.BooleanField(
                default=None,
                help_text="Manually marked as (not) spam",
                null=True,
                verbose_name="Is spam?",
            ),
        ),
    ]
