# Generated by Django 3.2.12 on 2022-05-05 17:29
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0087_use_booleanfield_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="canonical",
            field=models.BooleanField(
                default=False,
                help_text="This domain is the primary one where the documentation is served from",
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="cname",
            field=models.BooleanField(
                default=False, help_text="This domain is a CNAME for the project"
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="machine",
            field=models.BooleanField(default=False, help_text="This domain was auto-created"),
        ),
    ]
