# Generated by Django 3.2.13 on 2022-06-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0088_domain_field_edits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproject",
            name="external_builds_enabled",
            field=models.BooleanField(
                default=False,
                help_text='More information in <a href="https://docs.readthedocs.io/page/guides/autobuild-docs-for-pull-requests.html">our docs</a>.',
                verbose_name="Build pull requests for this project",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="external_builds_enabled",
            field=models.BooleanField(
                default=False,
                help_text='More information in <a href="https://docs.readthedocs.io/page/guides/autobuild-docs-for-pull-requests.html">our docs</a>.',
                verbose_name="Build pull requests for this project",
            ),
        ),
    ]
