# Generated by Django 3.2.13 on 2022-07-12 21:56
from django.db import migrations
from django.db import models
from django_safemigrate import Safe

import readthedocs.projects.validators


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0089_update_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="domain",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    readthedocs.projects.validators.DomainNameValidator(),
                    readthedocs.projects.validators.NoIPValidator(),
                ],
                verbose_name="Domain",
            ),
        ),
    ]
