# Generated by Django 3.2.13 on 2022-08-02 19:56
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0091_upate_meta_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="skip_validation",
            field=models.BooleanField(
                default=False, null=True, verbose_name="Skip validation process."
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="validation_process_start",
            field=models.DateTimeField(
                auto_now_add=True,
                null=True,
                verbose_name="Start date of the validation process.",
            ),
        ),
    ]
