# Generated by Django 3.2.16 on 2022-12-21 10:45
import django.db.models.deletion
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0093_migrate_null_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectrelationship",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="superprojects",
                to="projects.project",
                verbose_name="Subproject",
            ),
        ),
        migrations.AlterField(
            model_name="projectrelationship",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subprojects",
                to="projects.project",
                verbose_name="Main project",
            ),
        ),
    ]
