# Generated by Django 3.2.15 on 2022-10-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0093_migrate_null_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importedfile",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
