# Generated by Django 3.2.13 on 2022-07-11 09:06
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0094_auto_20221221_1045"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproject",
            name="default_branch",
            field=models.CharField(
                blank=True,
                default=None,
                help_text='What branch "latest" points to. Leave empty to use the default value for your VCS.',
                max_length=255,
                null=True,
                verbose_name="Default branch",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="default_branch",
            field=models.CharField(
                blank=True,
                default=None,
                help_text='What branch "latest" points to. Leave empty to use the default value for your VCS.',
                max_length=255,
                null=True,
                verbose_name="Default branch",
            ),
        ),
    ]
