# Generated by Django 3.2.18 on 2023-02-28 16:27
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0095_default_branch_helptext"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="delisted",
            field=models.BooleanField(
                default=False,
                help_text="Delisting a project removes it from Read the Docs search indexing and asks external search engines to remove it via robots.txt",
                null=True,
                verbose_name="Delisted",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="delisted",
            field=models.BooleanField(
                default=False,
                help_text="Delisting a project removes it from Read the Docs search indexing and asks external search engines to remove it via robots.txt",
                null=True,
                verbose_name="Delisted",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="skip",
            field=models.BooleanField(
                default=False, verbose_name="Skip (disable) building this project"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="skip",
            field=models.BooleanField(
                default=False, verbose_name="Skip (disable) building this project"
            ),
        ),
    ]
