# Generated by Django 3.2.18 on 2023-02-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0095_default_branch_helptext"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="delisted",
            field=models.BooleanField(
                default=False,
                help_text="Delisting a project removes it from search results and asks search engines to remove it via robots.txt",
                verbose_name="Delisted",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="delisted",
            field=models.BooleanField(
                default=False,
                help_text="Delisting a project removes it from search results and asks search engines to remove it via robots.txt",
                verbose_name="Delisted",
            ),
        ),
    ]
