# Generated by Django 3.2.18 on 2023-03-06 20:08
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0097_add_http_header"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproject",
            name="enable_epub_build",
            field=models.BooleanField(
                default=False,
                help_text="Create a EPUB version of your documentation with each build.",
                verbose_name="Enable EPUB build",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="enable_pdf_build",
            field=models.BooleanField(
                default=False,
                help_text="Create a PDF version of your documentation with each build.",
                verbose_name="Enable PDF build",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="enable_epub_build",
            field=models.BooleanField(
                default=False,
                help_text="Create a EPUB version of your documentation with each build.",
                verbose_name="Enable EPUB build",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="enable_pdf_build",
            field=models.BooleanField(
                default=False,
                help_text="Create a PDF version of your documentation with each build.",
                verbose_name="Enable PDF build",
            ),
        ),
    ]
