# Generated by Django 3.2.18 on 2023-03-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0098_pdf_epub_opt_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproject",
            name="conf_py_file",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Path from project root to your Sphinx configuration file, typically named <code>conf.py</code>. Leave blank if you want us to find it for you.",
                max_length=255,
                verbose_name="Sphinx configuration file",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="documentation_type",
            field=models.CharField(
                choices=[
                    ("sphinx", "Sphinx Html"),
                    ("mkdocs", "Mkdocs"),
                    ("sphinx_htmldir", "Sphinx HtmlDir"),
                    ("sphinx_singlehtml", "Sphinx Single Page HTML"),
                    ("generic", "Others (generic)"),
                ],
                default="sphinx",
                help_text='Specify the type of documentation you are building. This will make the automatic Read the Docs builder detect your MkDocs or Sphinx configuration and  build your project running Read the Docs\' default command. The Generic builder is only possible to use with a readthedocs.yaml configuration file since you need to specify the build command in this case. If you need more options, use a <a href="https://docs.readthedocs.io/en/stable/config-file/index.html">configuration file</a>. ',
                max_length=20,
                verbose_name="Documentation type",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="conf_py_file",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Path from project root to your Sphinx configuration file, typically named <code>conf.py</code>. Leave blank if you want us to find it for you.",
                max_length=255,
                verbose_name="Sphinx configuration file",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="documentation_type",
            field=models.CharField(
                choices=[
                    ("sphinx", "Sphinx Html"),
                    ("mkdocs", "Mkdocs"),
                    ("sphinx_htmldir", "Sphinx HtmlDir"),
                    ("sphinx_singlehtml", "Sphinx Single Page HTML"),
                    ("generic", "Others (generic)"),
                ],
                default="sphinx",
                help_text='Specify the type of documentation you are building. This will make the automatic Read the Docs builder detect your MkDocs or Sphinx configuration and  build your project running Read the Docs\' default command. The Generic builder is only possible to use with a readthedocs.yaml configuration file since you need to specify the build command in this case. If you need more options, use a <a href="https://docs.readthedocs.io/en/stable/config-file/index.html">configuration file</a>. ',
                max_length=20,
                verbose_name="Documentation type",
            ),
        ),
    ]
