# Generated by Django 3.2.18 on 2023-04-04 15:10
from django.db import migrations
from django.db import models
from django_safemigrate import Safe

import readthedocs.projects.validators


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0099_alter_domain_https"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="readthedocs_yaml_path",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="<strong>Warning: experimental feature</strong>. Custom path from repository top-level to your <code>.readthedocs.yaml</code>, ex. <code>subpath/docs/.readthedocs.yaml</code>. Leave blank for default value: <code>.readthedocs.yaml</code>.",
                max_length=1024,
                null=True,
                validators=[readthedocs.projects.validators.validate_build_config_file],
                verbose_name="Path for .readthedocs.yaml",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="readthedocs_yaml_path",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="<strong>Warning: experimental feature</strong>. Custom path from repository top-level to your <code>.readthedocs.yaml</code>, ex. <code>subpath/docs/.readthedocs.yaml</code>. Leave blank for default value: <code>.readthedocs.yaml</code>.",
                max_length=1024,
                null=True,
                validators=[readthedocs.projects.validators.validate_build_config_file],
                verbose_name="Path for .readthedocs.yaml",
            ),
        ),
    ]
