# Generated by Django 4.2.4 on 2023-08-02 10:59
import django.db.models.deletion
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0102_allow_version_warning_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailhook",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_notifications",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_notifications",
                to="projects.project",
            ),
        ),
    ]
