# Generated by Django 4.2.4 on 2023-08-10 21:03
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0103_alter_emailhook_project_alter_webhook_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="httpheader",
            name="value",
            field=models.CharField(max_length=4096),
        ),
    ]
