# Generated by Django 4.2.4 on 2023-08-23 20:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0104_alter_httpheader_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalproject",
            name="urlconf",
        ),
        migrations.RemoveField(
            model_name="project",
            name="urlconf",
        ),
    ]
