# Generated by Django 4.2.4 on 2023-08-23 20:35
from django.db import migrations
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0104_alter_httpheader_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalproject",
            name="urlconf",
        ),
        migrations.RemoveField(
            model_name="project",
            name="urlconf",
        ),
    ]
