# Generated by Django 4.2.5 on 2023-09-18 11:57
import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0105_remove_project_urlconf"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddonsConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable/Disable all the addons on this project",
                    ),
                ),
                ("analytics_enabled", models.BooleanField(default=True)),
                ("doc_diff_enabled", models.BooleanField(default=True)),
                ("doc_diff_show_additions", models.BooleanField(default=True)),
                ("doc_diff_show_deletions", models.BooleanField(default=True)),
                (
                    "doc_diff_root_selector",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("external_version_warning_enabled", models.BooleanField(default=True)),
                ("ethicalads_enabled", models.BooleanField(default=True)),
                ("flyout_enabled", models.BooleanField(default=True)),
                ("hotkeys_enabled", models.BooleanField(default=True)),
                ("search_enabled", models.BooleanField(default=True)),
                (
                    "search_default_filter",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "stable_latest_version_warning_enabled",
                    models.BooleanField(default=True),
                ),
                (
                    "project",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addons",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AddonSearchFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("syntaxt", models.CharField(max_length=128)),
                (
                    "addons",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.addonsconfig",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
