# Generated by Django 4.2.5 on 2023-09-13 14:21

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0105_remove_project_urlconf"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectAddonsConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("analytics_enabled", models.BooleanField(default=True)),
                ("doc_diff_enabled", models.BooleanField(default=True)),
                ("doc_diff_show_additions", models.BooleanField(default=True)),
                ("doc_diff_show_deletions", models.BooleanField(default=True)),
                ("doc_diff_root_selector", models.CharField(blank=True, null=True)),
                ("external_version_warning", models.BooleanField(default=True)),
                ("ethicalads_enabled", models.BooleanField(default=True)),
                ("flyout_enabled", models.BooleanField(default=True)),
                ("hotkeys_enabled", models.BooleanField(default=True)),
                ("search_enabled", models.BooleanField(default=True)),
                ("search_default_filter", models.CharField(blank=True, null=True)),
                ("stable_latest_version_warning", models.BooleanField(default=True)),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AddonSearchFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("syntaxt", models.CharField(max_length=128)),
                (
                    "addons",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.projectaddonsconfig",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="addons",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="projects.projectaddonsconfig",
                verbose_name="Addons project configuration",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="addons",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project",
                to="projects.projectaddonsconfig",
                verbose_name="Addons project configuration",
            ),
        ),
    ]
