# Generated by Django 4.2.5 on 2023-10-11 23:46
from django.db import migrations
from django_safemigrate import Safe


def forwards_func(apps, schema_editor):
    """Migrate language code to new format."""
    Project = apps.get_model("projects", "Project")
    old_language_codes = [
        "nb_NO",
        "pt_BR",
        "es_MX",
        "uk_UA",
        "zh_CN",
        "zh_TW",
    ]
    for old_language_code in old_language_codes:
        new_language_code = old_language_code.lower().replace("_", "-")
        Project.objects.filter(language=old_language_code).update(language=new_language_code)


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0107_alter_project_language"),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
