# Generated by Django 4.2.9 on 2024-01-22 19:16
from django.db import migrations
from django.db import models
from django_safemigrate import Safe

import readthedocs.projects.models


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0111_add_multiple_versions_without_translations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproject",
            name="external_builds_privacy_level",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                default=readthedocs.projects.models.default_privacy_level,
                help_text="Should builds from pull requests be public? <strong>If your repository is public, don't set this to private</strong>.",
                max_length=20,
                null=True,
                verbose_name="Privacy level of Pull Requests",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="external_builds_privacy_level",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                default=readthedocs.projects.models.default_privacy_level,
                help_text="Should builds from pull requests be public? <strong>If your repository is public, don't set this to private</strong>.",
                max_length=20,
                null=True,
                verbose_name="Privacy level of Pull Requests",
            ),
        ),
    ]
