# Generated by Django 4.2.9 on 2024-01-23 16:54
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0112_alter_project_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addonsconfig",
            name="analytics_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
