# Generated by Django 4.2.9 on 2024-01-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0113_disable_analytics_addons"),
    ]

    operations = [
        migrations.AddField(
            model_name="addonsconfig",
            name="flyout_sorting_custom_pattern",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Sorting pattern supported by BumpVer "
                '(<a href="https://github.com/mbarkhau/bumpver#pattern-examples"> See examples</a>',
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="addonsconfig",
            name="flyout_sorting",
            field=models.CharField(
                choices=[
                    ("alphabetically", "Alphabetically"),
                    ("semver-readthedocs-compatible", "SemVer (Read the Docs)"),
                    ("python-packaging", "Python Packaging (PEP 440 and PEP 425)"),
                    ("calver", "CalVer (YYYY.0M.0M)"),
                    ("custom-pattern", "Define your own pattern"),
                ],
                default="alphabetically",
            ),
        ),
    ]
