# Generated by Django 4.2.10 on 2024-02-19 11:17

from django.db import migrations, models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy

    dependencies = [
        ("projects", "0115_mark_fields_as_null"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalproject",
            name="conf_py_file",
        ),
        migrations.RemoveField(
            model_name="historicalproject",
            name="enable_epub_build",
        ),
        migrations.RemoveField(
            model_name="historicalproject",
            name="enable_pdf_build",
        ),
        migrations.RemoveField(
            model_name="historicalproject",
            name="install_project",
        ),
        migrations.RemoveField(
            model_name="historicalproject",
            name="path",
        ),
        migrations.RemoveField(
            model_name="historicalproject",
            name="python_interpreter",
        ),
        migrations.RemoveField(
            model_name="historicalproject",
            name="use_system_packages",
        ),
        migrations.RemoveField(
            model_name="project",
            name="conf_py_file",
        ),
        migrations.RemoveField(
            model_name="project",
            name="enable_epub_build",
        ),
        migrations.RemoveField(
            model_name="project",
            name="enable_pdf_build",
        ),
        migrations.RemoveField(
            model_name="project",
            name="install_project",
        ),
        migrations.RemoveField(
            model_name="project",
            name="path",
        ),
        migrations.RemoveField(
            model_name="project",
            name="python_interpreter",
        ),
        migrations.RemoveField(
            model_name="project",
            name="use_system_packages",
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="documentation_type",
            field=models.CharField(
                choices=[
                    ("sphinx", "Sphinx Html"),
                    ("mkdocs", "Mkdocs"),
                    ("sphinx_htmldir", "Sphinx HtmlDir"),
                    ("sphinx_singlehtml", "Sphinx Single Page HTML"),
                ],
                default="sphinx",
                help_text='Type of documentation you are building. <a href="http://www.sphinx-doc.org/en/stable/builders.html#sphinx.builders.html.DirectoryHTMLBuilder">More info on sphinx builders</a>.',
                max_length=20,
                verbose_name="Documentation type",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="documentation_type",
            field=models.CharField(
                choices=[
                    ("sphinx", "Sphinx Html"),
                    ("mkdocs", "Mkdocs"),
                    ("sphinx_htmldir", "Sphinx HtmlDir"),
                    ("sphinx_singlehtml", "Sphinx Single Page HTML"),
                ],
                default="sphinx",
                help_text='Type of documentation you are building. <a href="http://www.sphinx-doc.org/en/stable/builders.html#sphinx.builders.html.DirectoryHTMLBuilder">More info on sphinx builders</a>.',
                max_length=20,
                verbose_name="Documentation type",
            ),
        ),
    ]
