# Generated by Django 4.2.10 on 2024-02-19 11:17

from django.db import migrations
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()

    dependencies = [
        ("projects", "0116_mark_fields_as_null"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalproject",
            name="conf_py_file",
        ),
        migrations.RemoveField(
            model_name="historicalproject",
            name="enable_epub_build",
        ),
        migrations.RemoveField(
            model_name="historicalproject",
            name="enable_pdf_build",
        ),
        migrations.RemoveField(
            model_name="historicalproject",
            name="install_project",
        ),
        migrations.RemoveField(
            model_name="historicalproject",
            name="path",
        ),
        migrations.RemoveField(
            model_name="historicalproject",
            name="python_interpreter",
        ),
        migrations.RemoveField(
            model_name="historicalproject",
            name="use_system_packages",
        ),
        migrations.RemoveField(
            model_name="project",
            name="conf_py_file",
        ),
        migrations.RemoveField(
            model_name="project",
            name="enable_epub_build",
        ),
        migrations.RemoveField(
            model_name="project",
            name="enable_pdf_build",
        ),
        migrations.RemoveField(
            model_name="project",
            name="install_project",
        ),
        migrations.RemoveField(
            model_name="project",
            name="path",
        ),
        migrations.RemoveField(
            model_name="project",
            name="python_interpreter",
        ),
        migrations.RemoveField(
            model_name="project",
            name="use_system_packages",
        ),
    ]
