# Generated by Django 4.2.10 on 2024-03-04 13:32

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("projects", "0117_remove_old_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="addonsconfig",
            name="flyout_sorting",
            field=models.CharField(
                choices=[
                    ("alphabetically", "Alphabetically"),
                    ("semver-readthedocs-compatible", "SemVer (Read the Docs)"),
                    ("python-packaging", "Python Packaging (PEP 440 and PEP 425)"),
                    ("calver", "CalVer (YYYY.0M.0M)"),
                    ("custom-pattern", "Define your own pattern"),
                ],
                default="alphabetically",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="addonsconfig",
            name="flyout_sorting_custom_pattern",
            field=models.CharField(
                blank=True,
                default=None,
                help_text='Sorting pattern supported by BumpVer (<a href="https://github.com/mbarkhau/bumpver#pattern-examples">See examples</a>',
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="addonsconfig",
            name="flyout_sorting_latest_stable_at_beginning",
            field=models.BooleanField(
                default=True,
                help_text="Show <code>latest</code> and <code>stable</code> at the beginning",
            ),
        ),
        migrations.AddField(
            model_name="historicaladdonsconfig",
            name="flyout_sorting",
            field=models.CharField(
                choices=[
                    ("alphabetically", "Alphabetically"),
                    ("semver-readthedocs-compatible", "SemVer (Read the Docs)"),
                    ("python-packaging", "Python Packaging (PEP 440 and PEP 425)"),
                    ("calver", "CalVer (YYYY.0M.0M)"),
                    ("custom-pattern", "Define your own pattern"),
                ],
                default="alphabetically",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="historicaladdonsconfig",
            name="flyout_sorting_custom_pattern",
            field=models.CharField(
                blank=True,
                default=None,
                help_text='Sorting pattern supported by BumpVer (<a href="https://github.com/mbarkhau/bumpver#pattern-examples">See examples</a>',
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicaladdonsconfig",
            name="flyout_sorting_latest_stable_at_beginning",
            field=models.BooleanField(
                default=True,
                help_text="Show <code>latest</code> and <code>stable</code> at the beginning",
            ),
        ),
    ]
