# Generated by Django 4.2.10 on 2024-02-21 11:36

from django.db import migrations
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy

    dependencies = [
        ("projects", "0117_remove_old_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalproject",
            name="requirements_file",
        ),
        migrations.RemoveField(
            model_name="project",
            name="requirements_file",
        ),
    ]
