# Generated by Django 4.2.13 on 2024-07-15 22:05

from django.db import migrations
from django.db import models
from django_safemigrate import Safe

import readthedocs.projects.validators


class Migration(migrations.Migration):
    safe = Safe.before_deploy()
    dependencies = [
        ("projects", "0124_remove_zh_locale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproject",
            name="repo",
            field=models.CharField(
                db_index=True,
                help_text="Git repository URL",
                max_length=255,
                validators=[readthedocs.projects.validators.RepositoryURLValidator()],
                verbose_name="Repository URL",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="versioning_scheme",
            field=models.CharField(
                choices=[
                    (
                        "multiple_versions_with_translations",
                        "Multiple versions with translations (/<language>/<version>/<filename>)",
                    ),
                    (
                        "multiple_versions_without_translations",
                        "Multiple versions without translations (/<version>/<filename>)",
                    ),
                    (
                        "single_version_without_translations",
                        "Single version without translations (/<filename>)",
                    ),
                ],
                default="multiple_versions_with_translations",
                help_text="This affects URL your documentation is served from, and if it supports translations or versions. Changing the versioning scheme will break your current URLs, so you might need to create a redirect.",
                max_length=120,
                null=True,
                verbose_name="URL versioning scheme",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="repo",
            field=models.CharField(
                db_index=True,
                help_text="Git repository URL",
                max_length=255,
                validators=[readthedocs.projects.validators.RepositoryURLValidator()],
                verbose_name="Repository URL",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="versioning_scheme",
            field=models.CharField(
                choices=[
                    (
                        "multiple_versions_with_translations",
                        "Multiple versions with translations (/<language>/<version>/<filename>)",
                    ),
                    (
                        "multiple_versions_without_translations",
                        "Multiple versions without translations (/<version>/<filename>)",
                    ),
                    (
                        "single_version_without_translations",
                        "Single version without translations (/<filename>)",
                    ),
                ],
                default="multiple_versions_with_translations",
                help_text="This affects URL your documentation is served from, and if it supports translations or versions. Changing the versioning scheme will break your current URLs, so you might need to create a redirect.",
                max_length=120,
                null=True,
                verbose_name="URL versioning scheme",
            ),
        ),
    ]
