# Generated by Django 4.2.13 on 2024-07-15 20:58

from django.db import migrations, models
from django_safemigrate import Safe

import readthedocs.projects.validators


class Migration(migrations.Migration):
    safe = Safe.before_deploy
    dependencies = [
        ("projects", "0124_remove_zh_locale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproject",
            name="repo",
            field=models.CharField(
                db_index=True,
                help_text="Git repository URL",
                max_length=255,
                validators=[readthedocs.projects.validators.RepositoryURLValidator()],
                verbose_name="Repository URL",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="repo",
            field=models.CharField(
                db_index=True,
                help_text="Git repository URL",
                max_length=255,
                validators=[readthedocs.projects.validators.RepositoryURLValidator()],
                verbose_name="Repository URL",
            ),
        ),
    ]
