# Generated by Django 4.2.13 on 2024-07-24 21:57

import django.db.models.deletion
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()
    dependencies = [
        ("oauth", "0016_deprecate_old_vcs"),
        ("projects", "0125_update_naming"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproject",
            name="remote_repository",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                verbose_name="Connected repository",
                help_text="Repository connected to this project",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="oauth.remoterepository",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="remote_repository",
            field=models.ForeignKey(
                blank=True,
                verbose_name="Connected repository",
                help_text="Repository connected to this project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="oauth.remoterepository",
            ),
        ),
    ]
