# Generated by Django 4.2.16 on 2024-10-15 16:07
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.always()
    dependencies = [
        ("projects", "0126_alter_remote_repository_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addonsconfig",
            name="flyout_sorting",
            field=models.CharField(
                choices=[
                    ("alphabetically", "Alphabetically"),
                    ("semver-readthedocs-compatible", "SemVer (Read the Docs)"),
                    ("python-packaging", "Python Packaging (PEP 440 and PEP 425)"),
                    ("calver", "CalVer (YYYY.0M.0M)"),
                    ("custom-pattern", "Define your own pattern"),
                ],
                default="semver-readthedocs-compatible",
                max_length=64,
                verbose_name="Sorting of versions",
            ),
        ),
        migrations.AlterField(
            model_name="addonsconfig",
            name="flyout_sorting_custom_pattern",
            field=models.CharField(
                blank=True,
                default=None,
                help_text='Sorting pattern supported by BumpVer (<a href="https://github.com/mbarkhau/bumpver#pattern-examples">See examples</a>)',
                max_length=32,
                null=True,
                verbose_name="Custom version sorting pattern",
            ),
        ),
        migrations.AlterField(
            model_name="addonsconfig",
            name="flyout_sorting_latest_stable_at_beginning",
            field=models.BooleanField(
                default=True,
                verbose_name="Show <code>latest</code> and <code>stable</code> at the beginning",
            ),
        ),
        migrations.AlterField(
            model_name="historicaladdonsconfig",
            name="flyout_sorting",
            field=models.CharField(
                choices=[
                    ("alphabetically", "Alphabetically"),
                    ("semver-readthedocs-compatible", "SemVer (Read the Docs)"),
                    ("python-packaging", "Python Packaging (PEP 440 and PEP 425)"),
                    ("calver", "CalVer (YYYY.0M.0M)"),
                    ("custom-pattern", "Define your own pattern"),
                ],
                default="semver-readthedocs-compatible",
                max_length=64,
                verbose_name="Sorting of versions",
            ),
        ),
        migrations.AlterField(
            model_name="historicaladdonsconfig",
            name="flyout_sorting_custom_pattern",
            field=models.CharField(
                blank=True,
                default=None,
                help_text='Sorting pattern supported by BumpVer (<a href="https://github.com/mbarkhau/bumpver#pattern-examples">See examples</a>)',
                max_length=32,
                null=True,
                verbose_name="Custom version sorting pattern",
            ),
        ),
        migrations.AlterField(
            model_name="historicaladdonsconfig",
            name="flyout_sorting_latest_stable_at_beginning",
            field=models.BooleanField(
                default=True,
                verbose_name="Show <code>latest</code> and <code>stable</code> at the beginning",
            ),
        ),
    ]
