# Generated by Django 4.2.16 on 2024-11-05 17:33

from django.db import migrations
from django_safemigrate import Safe


def forward_add_fields(apps, schema_editor):
    AddonsConfig = apps.get_model("projects", "AddonsConfig")
    for addons in AddonsConfig.objects.filter(project__isnull=False).iterator():
        addons.notifications_show_on_latest = (
            addons.stable_latest_version_warning_enabled
        )
        addons.notifications_show_on_non_stable = (
            addons.stable_latest_version_warning_enabled
        )
        addons.notifications_show_on_external = addons.external_version_warning_enabled
        addons.save()


def reverse_remove_fields(apps, schema_editor):
    AddonsConfig = apps.get_model("projects", "AddonsConfig")
    for addons in AddonsConfig.objects.filter(project__isnull=False).iterator():
        addons.stable_latest_version_warning_enabled = (
            addons.notifications_show_on_latest
            or addons.notifications_show_on_non_stable
        )
        addons.external_version_warning_enabled = addons.notifications_show_on_external
        addons.save()


class Migration(migrations.Migration):
    safe = Safe.before_deploy

    dependencies = [
        ("projects", "0128_addons_notifications"),
    ]

    operations = [
        migrations.RunPython(forward_add_fields, reverse_remove_fields),
    ]
