# Generated by Django 4.2.16 on 2024-10-29 14:09

from django.db import migrations
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()

    dependencies = [
        ("projects", "0129_addons_notification_data_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="addonsconfig",
            name="external_version_warning_enabled",
        ),
        migrations.RemoveField(
            model_name="addonsconfig",
            name="stable_latest_version_warning_enabled",
        ),
        migrations.RemoveField(
            model_name="historicaladdonsconfig",
            name="external_version_warning_enabled",
        ),
        migrations.RemoveField(
            model_name="historicaladdonsconfig",
            name="stable_latest_version_warning_enabled",
        ),
    ]
