# Generated by Django 4.2.16 on 2024-11-06 16:24

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("projects", "0130_addons_remove_old_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="environmentvariable",
            name="value",
            field=models.CharField(help_text="Value of the environment variable", max_length=48000),
        ),
    ]
