# Generated by Django 4.2.16 on 2024-11-06 09:18

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("projects", "0131_increase_env_var_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="addonsconfig",
            name="linkpreviews_doctool_name",
            field=models.CharField(
                blank=True,
                choices=[("sphinx", "Sphinx"), ("other", "Other")],
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="addonsconfig",
            name="linkpreviews_doctool_version",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="addonsconfig",
            name="linkpreviews_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="addonsconfig",
            name="linkpreviews_root_selector",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="historicaladdonsconfig",
            name="linkpreviews_doctool_name",
            field=models.CharField(
                blank=True,
                choices=[("sphinx", "Sphinx"), ("other", "Other")],
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicaladdonsconfig",
            name="linkpreviews_doctool_version",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="historicaladdonsconfig",
            name="linkpreviews_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaladdonsconfig",
            name="linkpreviews_root_selector",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
