# Generated by Django 4.2.16 on 2024-11-13 12:00

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("projects", "0132_addons_linkpreviews_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="addonsconfig",
            name="options_load_when_embedded",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="historicaladdonsconfig",
            name="options_load_when_embedded",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
