# Generated by Django 4.2.16 on 2024-11-14 13:16

from django.db import migrations, models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy

    dependencies = [
        ('projects', '0132_addons_linkpreviews_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addonsconfig',
            name='doc_diff_root_selector',
        ),
        migrations.RemoveField(
            model_name='addonsconfig',
            name='linkpreviews_doctool_name',
        ),
        migrations.RemoveField(
            model_name='addonsconfig',
            name='linkpreviews_doctool_version',
        ),
        migrations.RemoveField(
            model_name='addonsconfig',
            name='linkpreviews_root_selector',
        ),
        migrations.RemoveField(
            model_name='historicaladdonsconfig',
            name='doc_diff_root_selector',
        ),
        migrations.RemoveField(
            model_name='historicaladdonsconfig',
            name='linkpreviews_doctool_name',
        ),
        migrations.RemoveField(
            model_name='historicaladdonsconfig',
            name='linkpreviews_doctool_version',
        ),
        migrations.RemoveField(
            model_name='historicaladdonsconfig',
            name='linkpreviews_root_selector',
        ),
        migrations.AddField(
            model_name='addonsconfig',
            name='options_doctool_name',
            field=models.CharField(blank=True, choices=[('sphinx', 'Sphinx'), ('other', 'Other')], help_text='Name of the documentation tool used by this project', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='addonsconfig',
            name='options_doctool_root_selector',
            field=models.CharField(blank=True, help_text='CSS selector for the main content of the page', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='historicaladdonsconfig',
            name='options_doctool_name',
            field=models.CharField(blank=True, choices=[('sphinx', 'Sphinx'), ('other', 'Other')], help_text='Name of the documentation tool used by this project', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='historicaladdonsconfig',
            name='options_doctool_root_selector',
            field=models.CharField(blank=True, help_text='CSS selector for the main content of the page', max_length=128, null=True),
        ),
    ]
