# Generated by Django 4.2.16 on 2024-11-13 13:34

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("projects", "0133_addons_load_when_embedded"),
    ]

    operations = [
        migrations.AddField(
            model_name="addonsconfig",
            name="customscript_enabled",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="addonsconfig",
            name="customscript_src",
            field=models.CharField(
                blank=True,
                help_text="URL to a JavaScript file to inject at serve time",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicaladdonsconfig",
            name="customscript_enabled",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="historicaladdonsconfig",
            name="customscript_src",
            field=models.CharField(
                blank=True,
                help_text="URL to a JavaScript file to inject at serve time",
                max_length=512,
                null=True,
            ),
        ),
    ]
