# Generated by Django 4.2.16 on 2024-11-11 17:05

from django.db import migrations, models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy

    dependencies = [
        ('projects', '0134_addons_load_when_embedded_notnull'),
    ]

    operations = [
        migrations.AddField(
            model_name='addonsconfig',
            name='user_js_file',
            field=models.CharField(blank=True, help_text='URL to a JavaScript file to inject at serve time', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='historicaladdonsconfig',
            name='user_js_file',
            field=models.CharField(blank=True, help_text='URL to a JavaScript file to inject at serve time', max_length=512, null=True),
        ),
    ]
