# Generated by Django 4.2.16 on 2024-11-13 13:36

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()

    dependencies = [
        ("projects", "0135_addons_load_when_embedded_notnull"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addonsconfig",
            name="customscript_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="historicaladdonsconfig",
            name="customscript_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
