# Generated by Django 4.2.16 on 2024-11-13 13:36

from django.db import migrations, models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy

    dependencies = [
        ('projects', '0135_addons_userjsfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonsconfig',
            name='userjsfile_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historicaladdonsconfig',
            name='userjsfile_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
