# Generated by Django 4.2.16 on 2024-11-20 12:35

from django.db import migrations
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()

    dependencies = [
        ("projects", "0137_use_generic_root_selector"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="addonsconfig",
            name="doc_diff_root_selector",
        ),
        migrations.RemoveField(
            model_name="addonsconfig",
            name="linkpreviews_doctool_name",
        ),
        migrations.RemoveField(
            model_name="addonsconfig",
            name="linkpreviews_doctool_version",
        ),
        migrations.RemoveField(
            model_name="addonsconfig",
            name="linkpreviews_root_selector",
        ),
        migrations.RemoveField(
            model_name="historicaladdonsconfig",
            name="doc_diff_root_selector",
        ),
        migrations.RemoveField(
            model_name="historicaladdonsconfig",
            name="linkpreviews_doctool_name",
        ),
        migrations.RemoveField(
            model_name="historicaladdonsconfig",
            name="linkpreviews_doctool_version",
        ),
        migrations.RemoveField(
            model_name="historicaladdonsconfig",
            name="linkpreviews_root_selector",
        ),
    ]
