# Generated by Django 4.2.16 on 2024-11-25 11:57

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


def forwards_func(apps, schema_editor):
    """
    Enable FileTreeDiff on those projects with the feature flag enabled.
    """
    Feature = apps.get_model("projects", "Feature")
    feature = Feature.objects.filter(feature_id="generate_manifest_for_file_tree_diff").first()
    if feature:
        for project in feature.projects.all().iterator():
            project.addons.filetreediff_enabled = True
            project.addons.save()


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("projects", "0138_remove_old_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="addonsconfig",
            name="filetreediff_enabled",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="historicaladdonsconfig",
            name="filetreediff_enabled",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.RunPython(forwards_func),
    ]
