# Generated by Django 4.2.16 on 2024-11-26 09:04

from django.db import migrations
from django_safemigrate import Safe


def forwards_func(apps, schema_editor):
    """
    Create ``AddonsConfig`` for those projects without it.

    We were creating these models when the user accesses to the dashboard or the API itself.
    Now, we are creating them on a ``post_save`` Django Signal.
    """
    AddonsConfig = apps.get_model("projects", "AddonsConfig")
    Project = apps.get_model("projects", "Project")
    for project in Project.objects.filter(addons__isnull=True).iterator():
        AddonsConfig.objects.get_or_create(project=project)


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("projects", "0140_addons_options_base_version"),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
