# Generated by Django 4.2.17 on 2025-01-08 11:15

from django.db import migrations, models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy

    dependencies = [
        ('projects', '0142_update_dj_simple_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='addonsconfig',
            name='flyout_position',
            field=models.CharField(blank=True, choices=[(None, 'Use default'), ('bottom-right', 'Bottom right'), ('bottom-right', 'Top right')], default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='historicaladdonsconfig',
            name='flyout_position',
            field=models.CharField(blank=True, choices=[(None, 'Use default'), ('bottom-right', 'Bottom right'), ('bottom-right', 'Top right')], default=None, max_length=64, null=True),
        ),
    ]
