# Generated by Django 4.2.17 on 2024-12-24 01:03

from django.db import migrations, models

from django_safemigrate import Safe


def set_notifications_off(apps, schema_editor):
    AddonsConfig = apps.get_model('projects', 'AddonsConfig')
    AddonsConfig.objects.update(
        notifications_show_on_latest=False,
        notifications_show_on_non_stable=False,
    )


class Migration(migrations.Migration):
    safe = Safe.before_deploy

    dependencies = [
        ('projects', '0142_update_dj_simple_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonsconfig',
            name='notifications_show_on_latest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='addonsconfig',
            name='notifications_show_on_non_stable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicaladdonsconfig',
            name='notifications_show_on_latest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicaladdonsconfig',
            name='notifications_show_on_non_stable',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_notifications_off),
    ]
