# Generated by Django 4.2.18 on 2025-02-05 11:33

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("projects", "0145_alter_importedfile_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="addonsconfig",
            name="filetreediff_ignored_files",
            field=models.JSONField(
                blank=True, help_text="List of ignored files. One per line.", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicaladdonsconfig",
            name="filetreediff_ignored_files",
            field=models.JSONField(
                blank=True, help_text="List of ignored files. One per line.", null=True
            ),
        ),
    ]
