# Generated by Django 4.2.19 on 2025-02-20 11:56

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


def migrate(apps, schema_editor):
    AddonsConfig = apps.get_model("projects", "AddonsConfig")
    AddonsConfig.objects.filter(filetreediff_enabled__isnull=True).update(filetreediff_enabled=True)


class Migration(migrations.Migration):
    safe = Safe.after_deploy()

    dependencies = [
        ("projects", "0146_addons_filetreediff_ignored_files"),
    ]

    operations = [
        migrations.RunPython(migrate),
        migrations.AlterField(
            model_name="addonsconfig",
            name="filetreediff_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="historicaladdonsconfig",
            name="filetreediff_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
