# Generated by Django 5.2.3 on 2025-06-23 18:00

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("projects", "0148_remove_unused_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="show_build_overview_in_comment",
            field=models.BooleanField(
                db_default=False,
                help_text="Show an overview of the build and files changed in a comment when a pull request is built.",
                verbose_name="Show build overview in a comment",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="show_build_overview_in_comment",
            field=models.BooleanField(
                db_default=False,
                help_text="Show an overview of the build and files changed in a comment when a pull request is built.",
                verbose_name="Show build overview in a comment",
            ),
        ),
    ]
