# Generated by Django 4.2.20 on 2025-05-06 22:55

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("projects", "0149_show_build_overview_in_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="has_ssh_key_with_write_access",
            field=models.BooleanField(
                default=False, help_text="Project has an SSH key with write access", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="has_ssh_key_with_write_access",
            field=models.BooleanField(
                default=False, help_text="Project has an SSH key with write access", null=True
            ),
        ),
    ]
