# Generated by Django 5.2.3 on 2025-07-08 09:38

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("projects", "0150_add_ssh_key_with_write_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="addonsconfig",
            name="linkpreviews_selector",
            field=models.CharField(
                blank=True,
                help_text="CSS selector to select links you want enabled for link previews. Leave it blank for auto-detect all links in your main page content.",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicaladdonsconfig",
            name="linkpreviews_selector",
            field=models.CharField(
                blank=True,
                help_text="CSS selector to select links you want enabled for link previews. Leave it blank for auto-detect all links in your main page content.",
                max_length=128,
                null=True,
            ),
        ),
    ]
