# Generated by Django 5.2.3 on 2025-07-14 20:18
from django.db import migrations
from django_safemigrate import Safe


def forwards_func(apps, schema_editor):
    """Create GitHub App integration for projects connected to a GitHub App."""
    Project = apps.get_model("projects", "Project")
    for project in Project.objects.filter(remote_repository__vcs_provider="githubapp"):
        integration, _ = project.integrations.get_or_create(
            integration_type="githubapp",
        )
        remote_repo = project.remote_repository
        installation = project.remote_repository.github_app_installation
        integration.provider_data = {
            "installation_id": installation.installation_id,
            "repository_id": remote_repo.remote_id,
            "repository_full_name": remote_repo.full_name,
        }
        integration.save()


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0151_addons_linkpreviews_selector"),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
