# Generated by Django 5.2.3 on 2025-08-11 21:09

import django.db.models.deletion
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()
    dependencies = [
        ("builds", "0064_healthcheck"),
        ("projects", "0152_create_gh_app_integration"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="latest_build",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="builds.build",
                verbose_name="Latest build",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="latest_build",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="builds.build",
                verbose_name="Latest build",
            ),
        ),
    ]
