# Generated by Django 5.2.3 on 2025-08-11 21:16

from django.db import migrations
from django_safemigrate import Safe


def forward(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    for project in Project.objects.all().iterator():
        latest_build = project.builds.order_by("-date").first()
        if latest_build:
            project.latest_build = latest_build
            project.save()


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("projects", "0153_project_latest_build"),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
