# Generated by Django 5.2.4 on 2025-08-15 09:07

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("projects", "0154_set_latest_build"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="git_checkout_command",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Custom command to execute before Git checkout"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="git_checkout_command",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Custom command to execute before Git checkout"
            ),
        ),
    ]
