# Generated by Django 5.2.7 on 2025-11-19 19:47

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("projects", "0155_custom_git_checkout_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="search_indexing_enabled",
            field=models.BooleanField(
                db_default=True,
                default=True,
                help_text="Enable/disable search indexing for this project",
                verbose_name="Enable search indexing",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="search_indexing_enabled",
            field=models.BooleanField(
                db_default=True,
                default=True,
                help_text="Enable/disable search indexing for this project",
                verbose_name="Enable search indexing",
            ),
        ),
    ]
