# Generated by Django 5.2.4 on 2025-01-XX XX:XX
from django.db import migrations
from django.db import models
from django.db.models.functions import Length
from django_safemigrate import Safe


def forwards_func(apps, schema_editor):
    """
    Truncate slugs and names longer than 55 characters.
    
    PR builds use the format {project.slug}--{pr.number}, so we need to leave
    room for the suffix. With max 6 digits for PR numbers + 2 for '--', we need
    to reduce the max from 63 to 55 characters.
    """
    max_length = 55
    Project = apps.get_model("projects", "Project")
    
    # Truncate slugs that are too long
    projects_invalid_slug = Project.objects.annotate(slug_length=Length("slug")).filter(
        slug_length__gt=max_length
    )
    for project in projects_invalid_slug:
        project.slug = project.slug[:max_length]
        project.save()

    # Truncate names that are too long
    projects_invalid_name = Project.objects.annotate(name_length=Length("name")).filter(
        name_length__gt=max_length
    )
    for project in projects_invalid_name:
        project.name = project.name[:max_length]
        project.save()


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    
    dependencies = [
        ("projects", "0155_custom_git_checkout_step"),
    ]

    operations = [
        migrations.RunPython(forwards_func),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(max_length=55, unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=55, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="slug",
            field=models.SlugField(max_length=55, verbose_name="Slug", db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="name",
            field=models.CharField(max_length=55, verbose_name="Name"),
        ),
    ]
