# Generated by Django 5.2.4 on 2025-01-XX XX:XX
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


def forwards_func(apps, schema_editor):
    """
    Update max_length for Project slug and name fields to 55 characters.
    
    PR builds use the format {project.slug}--{pr.number}, so we need to leave
    room for the suffix. With max 6 digits for PR numbers + 2 for '--', we need
    to reduce the max from 63 to 55 characters.
    
    Note: We do NOT truncate existing project slugs as that would break their
    documentation URLs. The max_length change only applies to new projects.
    Existing projects with slugs longer than 55 characters will continue to work.
    """
    # No data migration needed - we only change the field max_length
    # which doesn't affect existing data
    pass


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    
    dependencies = [
        ("projects", "0155_custom_git_checkout_step"),
    ]

    operations = [
        migrations.RunPython(forwards_func),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(max_length=55, unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=55, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="slug",
            field=models.SlugField(max_length=55, verbose_name="Slug", db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="name",
            field=models.CharField(max_length=55, verbose_name="Name"),
        ),
    ]
