# Generated by Django 5.2.7 on 2025-12-02 09:19

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("projects", "0156_project_search_indexing_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="n_consecutive_failed_builds",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Builds on this project were automatically disabled due to N+ consecutive failures. Uncheck this field to re-enable building.",
                verbose_name="Disable builds for this project",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="n_consecutive_failed_builds",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Builds on this project were automatically disabled due to N+ consecutive failures. Uncheck this field to re-enable building.",
                verbose_name="Disable builds for this project",
            ),
        ),
    ]
