# Generated by Django 5.2.10 on 2026-01-19 22:00

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("projects", "0157_disable_builds_after_n_failed"),
    ]

    operations = [
        migrations.AddField(
            model_name="addonsconfig",
            name="search_show_subprojects_filter",
            field=models.BooleanField(
                db_default=True,
                default=True,
                verbose_name="Show subprojects filter in search modal",
            ),
        ),
        migrations.AddField(
            model_name="historicaladdonsconfig",
            name="search_show_subprojects_filter",
            field=models.BooleanField(
                db_default=True,
                default=True,
                verbose_name="Show subprojects filter in search modal",
            ),
        ),
    ]
