# Generated by Django 5.2.10 on 2026-02-13 04:15

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("projects", "0158_add_search_subproject_filter_option"),
    ]

    operations = [
        migrations.AddField(
            model_name="addonsconfig",
            name="markdown_content_negotiation_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable content negotiation to serve markdown versions when requested by AI agents",
            ),
        ),
        migrations.AddField(
            model_name="historicaladdonsconfig",
            name="markdown_content_negotiation_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable content negotiation to serve markdown versions when requested by AI agents",
            ),
        ),
    ]
