# Generated by Django 5.2.10 on 2026-04-13 00:00

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("projects", "0158_add_search_subproject_filter_option"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addonsconfig",
            name="notifications_show_on_external",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="historicaladdonsconfig",
            name="notifications_show_on_external",
            field=models.BooleanField(default=False),
        ),
    ]
