# Generated by Django 5.2.11 on 2026-03-12 23:39

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()
    dependencies = [
        ("projects", "0158_add_search_subproject_filter_option"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addonsconfig",
            name="search_enabled",
            field=models.BooleanField(default=True, verbose_name="Enable search modal"),
        ),
        migrations.AlterField(
            model_name="historicaladdonsconfig",
            name="search_enabled",
            field=models.BooleanField(default=True, verbose_name="Enable search modal"),
        ),
    ]
