# Generated by Django 5.2.10 on 2026-04-13 00:00

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("projects", "0158_add_search_subproject_filter_option"),
    ]

    operations = [
        # Only the Python-level default changes: new ``AddonsConfig`` rows
        # default ``notifications_show_on_external`` to ``False`` while
        # existing rows keep whatever value they already have (there is no
        # ``db_default`` on this field, so ``AlterField`` does not rewrite
        # data).
        migrations.AlterField(
            model_name="addonsconfig",
            name="notifications_show_on_external",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="historicaladdonsconfig",
            name="notifications_show_on_external",
            field=models.BooleanField(default=False),
        ),
    ]
