# Generated by Django 5.2.12 on 2026-04-14 00:00

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("projects", "0159_notifications_show_on_external_help_text"),
        ("projects", "0159_update_addonsconfig_field_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addonsconfig",
            name="notifications_show_on_external",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Display a notification on the rendered documentation of pull "
                    "request previews. Readers will see a toast linking to the "
                    "build and the pull request."
                ),
                verbose_name="Show a notification on builds from pull requests",
            ),
        ),
        migrations.AlterField(
            model_name="historicaladdonsconfig",
            name="notifications_show_on_external",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Display a notification on the rendered documentation of pull "
                    "request previews. Readers will see a toast linking to the "
                    "build and the pull request."
                ),
                verbose_name="Show a notification on builds from pull requests",
            ),
        ),
    ]
