# Generated by Django 5.2.8 on 2026-04-21 09:51

import django.db.models.deletion
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("projects", "0161_addons_notifications_show_on_external_default_false"),
    ]

    operations = [
        migrations.AddField(
            model_name="httpheader",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="http_headers",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="httpheader",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="http_headers",
                to="projects.domain",
            ),
        ),
    ]
