# Generated by Django 5.2.12 on 2026-04-09 14:07

from django.db import migrations
from django_safemigrate import Safe


def forward_migrate_data(apps, schema_editor):
    VersionAutomationRule = apps.get_model("builds", "VersionAutomationRule")
    AutomationRule = apps.get_model("projects", "AutomationRule")
    AutomationRuleMatch = apps.get_model("builds", "AutomationRuleMatch")

    for rule in VersionAutomationRule.objects.iterator():
        is_webhook = rule.action == "trigger-build"
        new_rule = AutomationRule.objects.create(
            project=rule.project,
            priority=rule.priority,
            description=rule.description,
            version_types=[rule.version_type],
            action=rule.action,
            enabled=True,
            version_match_pattern="" if is_webhook else rule.match_arg,
            version_predefined_match_pattern=(
                "all-versions"
                if is_webhook
                else (rule.predefined_match_arg or "custom-match")
            ),
            webhook_files_match_pattern=(
                [rule.match_arg] if is_webhook and rule.match_arg else None
            ),
        )
        # ``created``/``modified`` are auto_now_add/auto_now and ignore values
        # passed to ``create()``; use ``update()`` to preserve the originals.
        AutomationRule.objects.filter(pk=new_rule.pk).update(
            created=rule.created, modified=rule.modified
        )
        AutomationRuleMatch.objects.filter(rule_id=rule.id).update(rule_id=new_rule.id)


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("projects", "0162_add_automationrule_v2"),
    ]

    operations = [
        migrations.RunPython(
            forward_migrate_data, reverse_code=migrations.RunPython.noop
        ),
    ]
