# Generated by Django 5.2.12 on 2026-04-09 14:07

from django.db import migrations
from django_safemigrate import Safe


def forward_migrate_data(apps, schema_editor):
    RegexAutomationRule = apps.get_model("builds", "RegexAutomationRule")
    AutomationRule = apps.get_model("projects", "AutomationRule")
    AutomationRuleMatch = apps.get_model("projects", "AutomationRuleMatch")

    for rule in RegexAutomationRule.objects.iterator():
        newrule = AutomationRule.objects.create(
            project=rule.project,
            priority=rule.priority,
            description=rule.description,
            version_types=[rule.version_type],
            version_match_pattern=rule.match_arg,
            # ``predefined_match_arg`` could be:
            # - semver-versions
            # - all-versions
            # - custom-match (if the match_arg doesn't match with any of the predefined patterns).
            version_predefined_match_pattern=rule.predefined_match_arg
            if rule.predefined_match_arg
            else "custom-match",
            action=rule.action,
            enabled=True,
        )

        # ``auto_now_add`` and ``auto_now`` fields ignore values passed to create(),
        # so we use update() to preserve the original timestamps.
        AutomationRule.objects.filter(pk=newrule.pk).update(
            created=rule.created,
            modified=rule.modified,
        )

        for match in rule.matches.iterator():
            newmatch = AutomationRuleMatch.objects.create(
                rule=newrule,
                match_arg=match.match_arg,
                action=match.action,
                version_name=match.version_name,
                version_type=match.version_type,
            )

            # ``auto_now_add`` and ``auto_now`` fields ignore values passed to create(),
            # so we use update() to preserve the original timestamps.
            AutomationRuleMatch.objects.filter(pk=newmatch.pk).update(
                created=match.created,
                modified=match.modified,
            )


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("projects", "0162_add_automationrule_v2"),
    ]

    operations = [
        migrations.RunPython(forward_migrate_data, reverse_code=migrations.RunPython.noop),
    ]
