# Generated by Django 5.2.12 on 2026-04-09 14:07

from django.db import migrations
from django_safemigrate import Safe


def forward_migrate_data(apps, schema_editor):
    RegexAutomationRule = apps.get_model("builds", "RegexAutomationRule")
    AutomationRuleMatch = apps.get_model("builds", "AutomationRuleMatch")
    AutomationRule = apps.get_model("projects", "AutomationRule")

    for rule in RegexAutomationRule.objects.iterator():
        newrule = AutomationRule.objects.create(
            # Keep the same date for the migrated rules.
            created=rule.created,
            modified=rule.modified,
            project=rule.project,
            priority=rule.priority,
            description=rule.description,
            version_types=[rule.version_type],
            version_match_pattern=rule.match_arg,
            # ``predefined_match_arg`` could be:
            # - semver-versions
            # - all-versions
            # - custom-match (if the match_arg doesn't match with any of the predefined patterns).
            version_predefined_match_pattern=rule.predefined_match_arg
            if rule.predefined_match_arg
            else "custom-match",
            action=rule.action,
            enabled=True,
        )

        for match in AutomationRuleMatch.objects.filter(rule_id=rule.id):
            match.rule_id = newrule.id
            match.save(update_fields=["rule_id"])


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("projects", "0162_add_automationrule_v2"),
    ]

    operations = [
        migrations.RunPython(forward_migrate_data, reverse_code=migrations.RunPython.noop),
    ]
