# Generated by Django 5.2.10 on 2026-03-30 00:00

from django.db import migrations
from django_safemigrate import Safe


LANGUAGE_CODE_UPDATES = {
    "nb-no": "nb",
    "uk-ua": "uk",
    "zh-cn": "zh-hans",
    "zh-tw": "zh-hant",
    "zh": "zh-hans",
    # In case any old underscore codes still exist.
    "nb_NO": "nb",
    "uk_UA": "uk",
    "zh_CN": "zh-hans",
    "zh_TW": "zh-hant",
}


def forwards_func(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    HistoricalProject = apps.get_model("projects", "HistoricalProject")

    for old_language_code, new_language_code in LANGUAGE_CODE_UPDATES.items():
        Project.objects.filter(language=old_language_code).update(language=new_language_code)
        HistoricalProject.objects.filter(language=old_language_code).update(
            language=new_language_code,
        )


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("projects", "0163_automationrule_data_migration"),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
