# Generated by Django 5.2.12 on 2026-05-12

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("projects", "0163_automationrule_data_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproject",
            name="show_build_overview_in_comment",
            field=models.BooleanField(
                db_default=True,
                help_text="Show an overview of the build and files changed in a comment when a pull request is built.",
                verbose_name="Show build overview in a comment",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="show_build_overview_in_comment",
            field=models.BooleanField(
                db_default=True,
                help_text="Show an overview of the build and files changed in a comment when a pull request is built.",
                verbose_name="Show build overview in a comment",
            ),
        ),
    ]
