# Generated by Django 5.2.13 on 2026-06-03 09:38

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("projects", "0164_show_build_overview_in_comment_default_true"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automationrulematch",
            name="version_type",
            field=models.CharField(
                choices=[
                    ("branch", "Branch"),
                    ("tag", "Tag"),
                    ("external", "Pull request"),
                    ("unknown", "Unknown"),
                ],
                max_length=32,
            ),
        ),
    ]
