# Generated by Django 5.2.13 on 2026-06-03 09:32

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("projects", "0164_show_build_overview_in_comment_default_true"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="container_cpu_limit",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Fargate CPU units (1024 = 1 vCPU). Defaults to the system-wide default (2048 = 2 vCPU) when unset. Must pair with ``container_mem_limit`` to a supported Fargate CPU/memory combination.",
                null=True,
                verbose_name="Container CPU limit in Fargate CPU units",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="container_cpu_limit",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Fargate CPU units (1024 = 1 vCPU). Defaults to the system-wide default (2048 = 2 vCPU) when unset. Must pair with ``container_mem_limit`` to a supported Fargate CPU/memory combination.",
                null=True,
                verbose_name="Container CPU limit in Fargate CPU units",
            ),
        ),
    ]
