# Generated by Django 5.2.12 on 2026-05-12

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("projects", "0164_show_build_overview_in_comment_default_true"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproject",
            name="external_builds_enabled",
            field=models.BooleanField(
                default=True,
                help_text='More information in <a href="https://docs.readthedocs.io/page/guides/autobuild-docs-for-pull-requests.html">our docs</a>.',
                verbose_name="Build pull requests for this project",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="external_builds_enabled",
            field=models.BooleanField(
                default=True,
                help_text='More information in <a href="https://docs.readthedocs.io/page/guides/autobuild-docs-for-pull-requests.html">our docs</a>.',
                verbose_name="Build pull requests for this project",
            ),
        ),
    ]
