# Generated by Django 5.2.13 on 2026-04-23 01:48

import django.db.models.deletion
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("builds", "0071_alter_versionautomationrule_fk"),
        ("projects", "0164_show_build_overview_in_comment_default_true"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addonsconfig",
            name="options_base_version",
            field=models.ForeignKey(
                blank=True,
                help_text="Visual diff and File tree diff compare the current page against this version. Defaults to the <b>latest</b> version.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="builds.version",
                verbose_name="Base version to compare against (eg. Visual diff, File tree diff)",
            ),
        ),
        migrations.AlterField(
            model_name="historicaladdonsconfig",
            name="options_base_version",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Visual diff and File tree diff compare the current page against this version. Defaults to the <b>latest</b> version.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="builds.version",
                verbose_name="Base version to compare against (eg. Visual diff, File tree diff)",
            ),
        ),
    ]
