# Generated by Django 5.2.13 on 2026-06-09 11:18

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()
    dependencies = [
        ("projects", "0165_historicalproject_container_cpu_limit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproject",
            name="container_cpu_limit",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="ECS CPU units (1024 = 1 vCPU). Defaults to the system-wide default (2048 = 2 vCPU) when unset. Paired with ``container_mem_limit``; the build is routed to a capacity provider whose instances can fit the request.",
                null=True,
                verbose_name="Container CPU limit in ECS CPU units",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="container_cpu_limit",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="ECS CPU units (1024 = 1 vCPU). Defaults to the system-wide default (2048 = 2 vCPU) when unset. Paired with ``container_mem_limit``; the build is routed to a capacity provider whose instances can fit the request.",
                null=True,
                verbose_name="Container CPU limit in ECS CPU units",
            ),
        ),
    ]
