# Generated by Django 5.2.16 on 2026-07-29 15:44

from django.db import migrations
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()

    dependencies = [
        ("projects", "0166_alias_allow_slashes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailhook",
            options={"ordering": ("pk",)},
        ),
        migrations.AlterModelOptions(
            name="environmentvariable",
            options={"ordering": ("name", "pk")},
        ),
        migrations.AlterModelOptions(
            name="webhook",
            options={"ordering": ("pk",)},
        ),
    ]
