# Generated by Django 5.2.16 on 2026-08-12 18:46

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()
    dependencies = [
        ("projects", "0166_alias_allow_slashes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproject",
            name="has_valid_clone",
            field=models.BooleanField(
                default=False, help_text="This project has been successfully cloned", null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="has_valid_clone",
            field=models.BooleanField(
                default=False, help_text="This project has been successfully cloned", null=True
            ),
        ),
    ]
