# Generated by Django 5.2.16 on 2026-08-14 00:00

from django.db import migrations
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()

    dependencies = [
        ("projects", "0167_alter_has_valid_clone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalproject",
            name="has_valid_clone",
        ),
        migrations.RemoveField(
            model_name="project",
            name="has_valid_clone",
        ),
    ]
