# Generated by Django 5.2.16 on 2026-09-03 00:00

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("projects", "0169_external_builds_enabled_default_true"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="max_build_media_size",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Maximum size (in MB) allowed per media type when uploading build artifacts",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="max_build_media_size",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Maximum size (in MB) allowed per media type when uploading build artifacts",
            ),
        ),
    ]
