# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-03-15 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationaction',
            name='decision',
            field=models.IntegerField(choices=[(0, 'No Decision'), (1, 'Publish'), (2, 'Hide')]),
        ),
        migrations.AlterField(
            model_name='nodesnapshot',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Publication date'),
        ),
    ]
