# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0028_create-domain-data'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, verbose_name='Domain')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('display_name', models.CharField(max_length=255, verbose_name='Display Name')),
                ('type', models.CharField(max_length=255, verbose_name='Type')),
                ('doc_name', models.CharField(max_length=255, verbose_name='Doc Name')),
                ('anchor', models.CharField(max_length=255, verbose_name='Anchor')),
                ('priority', models.IntegerField(verbose_name='Priority')),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_data', to='projects.Project')),
            ],
        ),
    ]
