from test_api import *  # noqa
from view_tests import *  # noqa
from test_doc_building import *  # noqa
from test_backend import *  # noqa
from test_celery import *  # noqa
from test_hacks import *  # noqa
from test_post_commit_hooks import *  # noqa
from test_privacy import *  # noqa
from test_middlware import *  # noqa
from test_redirects import *  # noqa
from test_urls import *  # noqa
