# -*- coding: utf-8 -*-

import os
import mock

from django.test import TestCase

from readthedocs.projects.models import ImportedFile, Project, HTMLFile
from readthedocs.projects.tasks import (
    _create_imported_files,
    _sync_imported_files,
    _create_intersphinx_data,
)
from readthedocs.sphinx_domains.models import SphinxDomain


base_dir = os.path.dirname(os.path.dirname(__file__))


class ImportedFileTests(TestCase):
    fixtures = ['eric', 'test_data']

    def setUp(self):
        self.project = Project.objects.get(slug='pip')
        self.version = self.project.versions.first()

    def _manage_imported_files(self, version, path, commit, build):
        """Helper function for the tests to create and sync ImportedFiles."""
        _create_imported_files(version, path, commit, build)
        _sync_imported_files(version, build, set())

    def test_properly_created(self):
        test_dir = os.path.join(base_dir, 'files')
        self.assertEqual(ImportedFile.objects.count(), 0)
        self._manage_imported_files(self.version, test_dir, 'commit01', 1)
        self.assertEqual(ImportedFile.objects.count(), 4)
        self._manage_imported_files(self.version, test_dir, 'commit01', 2)
        self.assertEqual(ImportedFile.objects.count(), 4)

    def test_update_commit(self):
        test_dir = os.path.join(base_dir, 'files')
        self.assertEqual(ImportedFile.objects.count(), 0)
        self._manage_imported_files(self.version, test_dir, 'commit01', 1)
        self.assertEqual(ImportedFile.objects.first().commit, 'commit01')
        self._manage_imported_files(self.version, test_dir, 'commit02', 2)
        self.assertEqual(ImportedFile.objects.first().commit, 'commit02')

    def test_update_content(self):
        test_dir = os.path.join(base_dir, 'files')
        self.assertEqual(ImportedFile.objects.count(), 0)

        with open(os.path.join(test_dir, 'test.html'), 'w+') as f:
            f.write('Woo')

        self._manage_imported_files(self.version, test_dir, 'commit01', 1)
        self.assertEqual(ImportedFile.objects.get(name='test.html').md5, 'c7532f22a052d716f7b2310fb52ad981')

        with open(os.path.join(test_dir, 'test.html'), 'w+') as f:
            f.write('Something Else')

        self._manage_imported_files(self.version, test_dir, 'commit02', 2)
        self.assertNotEqual(ImportedFile.objects.get(name='test.html').md5, 'c7532f22a052d716f7b2310fb52ad981')

        self.assertEqual(ImportedFile.objects.count(), 4)

    @mock.patch('readthedocs.projects.tasks.os.path.exists')
    def test_create_intersphinx_data(self, mock_exists):
        mock_exists.return_Value = True

        # Test data for objects.inv file
        test_objects_inv = {
            'cpp:function': {
                'sphinx.test.function': [
                    'dummy-proj-1',
                    'dummy-version-1',
                    'test.html#epub-faq',  # file generated by ``sphinx.builders.html.StandaloneHTMLBuilder``
                    'dummy-func-name-1',
                ]
            },
            'py:function': {
                'sample.test.function': [
                    'dummy-proj-2',
                    'dummy-version-2',
                    'test.html#sample-test-func',  # file generated by ``sphinx.builders.html.StandaloneHTMLBuilder``
                    'dummy-func-name-2'
                ]
            },
            'js:function': {
                'testFunction': [
                    'dummy-proj-3',
                    'dummy-version-3',
                    'api/#test-func',  # file generated by ``sphinx.builders.dirhtml.DirectoryHTMLBuilder``
                    'dummy-func-name-3'
                ]
            }
        }

        with mock.patch(
            'sphinx.ext.intersphinx.fetch_inventory',
            return_value=test_objects_inv
        ) as mock_fetch_inventory:

            test_dir = os.path.join(base_dir, 'files')

            _create_imported_files(self.version, test_dir, 'commit01', 1)
            _create_intersphinx_data(self.version, test_dir, 'commit01', 1)

            # there will be two html files,
            # `api/index.html` and `test.html`
            self.assertEqual(
                HTMLFile.objects.all().count(),
                2
            )
            self.assertEqual(
                HTMLFile.objects.filter(path='api/index.html').count(),
                1
            )

            html_file_api = HTMLFile.objects.filter(path='api/index.html').first()

            self.assertEqual(
                SphinxDomain.objects.all().count(),
                3
            )
            self.assertEqual(
                SphinxDomain.objects.filter(html_file=html_file_api).count(),
                1
            )
