# Generated by Django 4.2.6 on 2023-11-23 17:26
import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("message_id", models.CharField(max_length=128)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("unread", "unread"),
                            ("read", "read"),
                            ("dismissed", "dismissed"),
                            ("cancelled", "cancelled"),
                        ],
                        db_index=True,
                        default="unread",
                        max_length=128,
                    ),
                ),
                ("dismissable", models.BooleanField(default=False)),
                (
                    "news",
                    models.BooleanField(default=False, help_text="Show under bell icon"),
                ),
                ("attached_to_id", models.PositiveIntegerField()),
                (
                    "attached_to_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
