# Generated by Django 5.2.16 on 2026-07-29 15:44

from django.db import migrations
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()

    dependencies = [
        ("notifications", "0004_remove_unused_notification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-created", "-pk"]},
        ),
    ]
