# Generated by Django 5.2.13 on 2026-06-23 22:42

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("core", "0001_initial"),
        ("core", "0002_make_userprofile_user_a_onetoonefield"),
        ("core", "0003_add_banned_status"),
        ("core", "0004_ad-opt-out"),
        ("core", "0005_migrate-old-passwords"),
        ("core", "0006_remove_userprofile_allow_email"),
        ("core", "0007_historicaluser"),
        ("core", "0008_add_extra_history_fields"),
        ("core", "0009_historicaluserprofile"),
        ("core", "0010_add_time_fields"),
        ("core", "0011_alter_historicaluser_first_name"),
        ("core", "0012_add_newsletter_setting"),
        ("core", "0013_add_optout_email_config_file_deprecation"),
        ("core", "0014_optout_email_build_image_deprecation"),
        ("core", "0015_remove_email_options"),
        ("core", "0016_update_dj_simple_history"),
        ("core", "0017_remove_unused_indexes"),
        ("core", "0018_add_profile_theme"),
        ("core", "0019_create_missing_user_profiles"),
        ("core", "0020_alter_userprofile_user"),
        ("core", "0021_create_missing_user_profiles"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalUser",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True,
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "extra_history_user_id",
                    models.IntegerField(blank=True, null=True, verbose_name="ID"),
                ),
                (
                    "extra_history_user_username",
                    models.CharField(
                        max_length=150, null=True, verbose_name="username"
                    ),
                ),
                (
                    "extra_history_ip",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="IP address"
                    ),
                ),
                (
                    "extra_history_browser",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Browser user-agent",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical user",
                "verbose_name_plural": "historical users",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalUserProfile",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "extra_history_user_id",
                    models.IntegerField(blank=True, null=True, verbose_name="ID"),
                ),
                (
                    "extra_history_user_username",
                    models.CharField(
                        max_length=150, null=True, verbose_name="username"
                    ),
                ),
                (
                    "extra_history_ip",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="IP address"
                    ),
                ),
                (
                    "extra_history_browser",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Browser user-agent",
                    ),
                ),
                (
                    "homepage",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Homepage"
                    ),
                ),
                (
                    "allow_ads",
                    models.BooleanField(
                        default=True,
                        help_text="If unchecked, you will still see community ads.",
                        verbose_name="See paid advertising",
                    ),
                ),
                (
                    "mailing_list",
                    models.BooleanField(
                        default=False,
                        help_text="Subscribe to our mailing list, and get helpful onboarding suggestions.",
                    ),
                ),
                (
                    "whitelisted",
                    models.BooleanField(default=False, verbose_name="Whitelisted"),
                ),
                ("banned", models.BooleanField(default=False, verbose_name="Banned")),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("default", "Use default theme"),
                            ("light", "Light theme"),
                            ("dark", "Dark theme"),
                            ("system", "Use system theme"),
                        ],
                        default="default",
                        verbose_name="Dashboard theme",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical user profile",
                "verbose_name_plural": "historical user profiles",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "homepage",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Homepage"
                    ),
                ),
                (
                    "allow_ads",
                    models.BooleanField(
                        default=True,
                        help_text="If unchecked, you will still see community ads.",
                        verbose_name="See paid advertising",
                    ),
                ),
                (
                    "mailing_list",
                    models.BooleanField(
                        default=False,
                        help_text="Subscribe to our mailing list, and get helpful onboarding suggestions.",
                    ),
                ),
                (
                    "whitelisted",
                    models.BooleanField(default=False, verbose_name="Whitelisted"),
                ),
                ("banned", models.BooleanField(default=False, verbose_name="Banned")),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("default", "Use default theme"),
                            ("light", "Light theme"),
                            ("dark", "Dark theme"),
                            ("system", "Use system theme"),
                        ],
                        default="default",
                        verbose_name="Dashboard theme",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
