# Generated by Django 5.2.16 on 2026-08-21 01:05

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("core", "0001_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluserprofile",
            name="attribution",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Where this user came from when they signed up, as source, medium and campaign. Empty for direct traffic, and for users who signed up before we started tracking this.",
                verbose_name="Signup attribution",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="attribution",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Where this user came from when they signed up, as source, medium and campaign. Empty for direct traffic, and for users who signed up before we started tracking this.",
                verbose_name="Signup attribution",
            ),
        ),
    ]
