# Generated by Django 5.2.16 on 2026-08-21 00:25

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("core", "0001_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluserprofile",
            name="attribution_first_touch_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Signup first touch date"
            ),
        ),
        migrations.AddField(
            model_name="historicaluserprofile",
            name="attribution_landing_page",
            field=models.CharField(
                blank=True,
                default="",
                max_length=512,
                verbose_name="Signup landing page",
            ),
        ),
        migrations.AddField(
            model_name="historicaluserprofile",
            name="attribution_referrer",
            field=models.CharField(
                blank=True, default="", max_length=512, verbose_name="Signup referrer"
            ),
        ),
        migrations.AddField(
            model_name="historicaluserprofile",
            name="attribution_utm_campaign",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Signup UTM campaign",
            ),
        ),
        migrations.AddField(
            model_name="historicaluserprofile",
            name="attribution_utm_content",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Signup UTM content",
            ),
        ),
        migrations.AddField(
            model_name="historicaluserprofile",
            name="attribution_utm_medium",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Signup UTM medium"
            ),
        ),
        migrations.AddField(
            model_name="historicaluserprofile",
            name="attribution_utm_source",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Signup UTM source"
            ),
        ),
        migrations.AddField(
            model_name="historicaluserprofile",
            name="attribution_utm_term",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Signup UTM term"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="attribution_first_touch_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Signup first touch date"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="attribution_landing_page",
            field=models.CharField(
                blank=True,
                default="",
                max_length=512,
                verbose_name="Signup landing page",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="attribution_referrer",
            field=models.CharField(
                blank=True, default="", max_length=512, verbose_name="Signup referrer"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="attribution_utm_campaign",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Signup UTM campaign",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="attribution_utm_content",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Signup UTM content",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="attribution_utm_medium",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Signup UTM medium"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="attribution_utm_source",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Signup UTM source"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="attribution_utm_term",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Signup UTM term"
            ),
        ),
    ]
