# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-14 17:16
from __future__ import unicode_literals

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_banned_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ad_opt_out',
            field=models.BooleanField(default=False, verbose_name='Opt Out of seeing advertising'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
