# Generated by Django 1.11.20 on 2019-03-01 17:30
from django.db import migrations
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("core", "0005_migrate-old-passwords"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="allow_email",
        ),
    ]
