# Generated by Django 2.2.24 on 2021-09-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_historicaluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='extra_history_browser',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Browser user-agent'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='extra_history_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address'),
        ),
    ]
