import django.db.models.deletion
import simple_history.models

# Generated by Django 2.2.24 on 2021-11-11 18:20
from django.conf import settings
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0008_add_extra_history_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalUserProfile",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "extra_history_user_id",
                    models.IntegerField(blank=True, db_index=True, null=True, verbose_name="ID"),
                ),
                (
                    "extra_history_user_username",
                    models.CharField(
                        db_index=True,
                        max_length=150,
                        null=True,
                        verbose_name="username",
                    ),
                ),
                (
                    "extra_history_ip",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="IP address"
                    ),
                ),
                (
                    "extra_history_browser",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Browser user-agent",
                    ),
                ),
                (
                    "whitelisted",
                    models.BooleanField(default=False, verbose_name="Whitelisted"),
                ),
                ("banned", models.BooleanField(default=False, verbose_name="Banned")),
                (
                    "homepage",
                    models.CharField(blank=True, max_length=100, verbose_name="Homepage"),
                ),
                (
                    "allow_ads",
                    models.BooleanField(
                        default=True,
                        help_text="If unchecked, you will still see community ads.",
                        verbose_name="See paid advertising",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical user profile",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
