# Generated by Django 3.2.9 on 2021-11-26 11:05
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("core", "0010_add_time_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluser",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="first name"),
        ),
    ]
