# Generated by Django 3.2.13 on 2022-06-28 21:52

import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_historicaluser_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluserprofile",
            name="mailing_list",
            field=models.BooleanField(
                default=False,
                help_text="Subscribe to our mailing list, and get helpful onboarding suggestions.",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="mailing_list",
            field=models.BooleanField(
                default=False,
                help_text="Subscribe to our mailing list, and get helpful onboarding suggestions.",
            ),
        ),
        migrations.AlterField(
            model_name="historicaluserprofile",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicaluserprofile",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True,
                default=django.utils.timezone.now,
                verbose_name="modified",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True,
                default=django.utils.timezone.now,
                verbose_name="modified",
            ),
            preserve_default=False,
        ),
    ]
