# Generated by Django 3.2.19 on 2023-06-14 17:17
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("core", "0012_add_newsletter_setting"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluserprofile",
            name="optout_email_config_file_deprecation",
            field=models.BooleanField(
                default=False,
                null=True,
                verbose_name="Opt-out from email about 'Config file deprecation'",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="optout_email_config_file_deprecation",
            field=models.BooleanField(
                default=False,
                null=True,
                verbose_name="Opt-out from email about 'Config file deprecation'",
            ),
        ),
    ]
