# Generated by Django 4.2.10 on 2024-02-27 18:55

from django.db import migrations
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()

    dependencies = [
        ("core", "0014_optout_email_build_image_deprecation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaluserprofile",
            name="optout_email_build_image_deprecation",
        ),
        migrations.RemoveField(
            model_name="historicaluserprofile",
            name="optout_email_config_file_deprecation",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="optout_email_build_image_deprecation",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="optout_email_config_file_deprecation",
        ),
    ]
