# Generated by Django 5.2.8 on 2026-03-18 10:01

import django_extensions.db.fields
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


def seed_blocked_domains(apps, schema_editor):
    BlockedEmailDomain = apps.get_model("core", "BlockedEmailDomain")
    BlockedEmailDomain.objects.bulk_create(
        [
            BlockedEmailDomain(domain="163.com"),
            BlockedEmailDomain(domain="*.milkgg.com"),
        ]
    )


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("core", "0017_remove_unused_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedEmailDomain",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        help_text='Exact domain (e.g. "163.com") or wildcard pattern (e.g. "*.milkgg.com").',
                        max_length=255,
                        unique=True,
                        verbose_name="Domain pattern",
                    ),
                ),
            ],
            options={
                "ordering": ["domain"],
            },
        ),
        migrations.RunPython(seed_blocked_domains, migrations.RunPython.noop),
    ]
