# Generated by Django 5.2.8 on 2026-04-24 05:55

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_remove_unused_indexes"),
    ]
    safe = Safe.before_deploy()

    operations = [
        migrations.AddField(
            model_name="historicaluserprofile",
            name="theme",
            field=models.CharField(
                choices=[
                    ("default", "Use default theme"),
                    ("light", "Light theme"),
                    ("dark", "Dark theme"),
                    ("system", "Use system theme"),
                ],
                default="default",
                verbose_name="Dashboard theme",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="theme",
            field=models.CharField(
                choices=[
                    ("default", "Use default theme"),
                    ("light", "Light theme"),
                    ("dark", "Dark theme"),
                    ("system", "Use system theme"),
                ],
                default="default",
                verbose_name="Dashboard theme",
            ),
        ),
    ]
