# Generated by Django 5.2.13 on 2026-05-27 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


def forwards_create_missing_profiles(apps, schema_editor):
    """
    Create a profile for users that don't have one yet.

    The ``user`` field used to be an ``AutoOneToOneField`` that created the
    profile lazily on access, so existing users may not have a profile row.
    """
    User = apps.get_model(settings.AUTH_USER_MODEL)
    UserProfile = apps.get_model("core", "UserProfile")

    users_without_profile = User.objects.filter(profile__isnull=True)
    UserProfile.objects.bulk_create(
        (UserProfile(user=user) for user in users_without_profile.iterator()),
        batch_size=500,
    )


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("core", "0018_add_profile_theme"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.RunPython(
            forwards_create_missing_profiles,
            migrations.RunPython.noop,
        ),
    ]
