# Generated by Django 5.2.13 on 2026-06-10 21:28

from django.db import migrations
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("core", "0021_create_missing_user_profiles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaluserprofile",
            name="homepage",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="homepage",
        ),
    ]
