Vagrant::Config.run do |config|
  config.vm.box = "lucid32"
  config.vm.forward_port  80, 8080
  config.vm.forward_port  9999, 9999

   config.vm.provision :chef_solo do |chef|
     chef.cookbooks_path = "cookbooks"
     chef.roles_path = "roles"
     chef.add_role "all"
   end
end
