. .bashrc

export PIP_DOWNLOAD_CACHE=/tmp/pip
export DJANGO_SETTINGS_MODULE=settings.onebox
export PYTHONPATH=$PYTHONPATH:~/checkouts/readthedocs.org/readthedocs
export EDITOR=vim

. bin/activate

cd ~/checkouts/readthedocs.org/

alias chk='cd ~/checkouts/readthedocs.org'
alias run='cd ~/run'
