# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-02-17 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='to_url',
            field=models.CharField(blank=True, db_index=True, help_text='Absolute or relative URL. Examples: <b>/tutorial/install.html</b>', max_length=255, verbose_name='To URL'),
        ),
    ]
