# Generated by Django 1.11.16 on 2018-10-31 11:25
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("redirects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redirect",
            name="redirect_type",
            field=models.CharField(
                choices=[
                    ("prefix", "Prefix Redirect"),
                    ("page", "Page Redirect"),
                    ("exact", "Exact Redirect"),
                    ("sphinx_html", "Sphinx HTMLDir -> HTML"),
                    ("sphinx_htmldir", "Sphinx HTML -> HTMLDir"),
                ],
                help_text="The type of redirect you wish to use.",
                max_length=255,
                verbose_name="Redirect Type",
            ),
        ),
        migrations.AlterField(
            model_name="redirect",
            name="to_url",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Absolute or relative URL. Example: <b>/tutorial/install.html</b>",
                max_length=255,
                verbose_name="To URL",
            ),
        ),
    ]
