# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-03-14 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirects', '0003_add_default_redirect_http_status_to_302'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirect',
            name='from_url_without_rest',
            field=models.CharField(blank=True, db_index=True, help_text='Only for internal querying use', max_length=255, null=True),
        ),
    ]
