# Generated by Django 3.2.13 on 2022-05-18 19:41
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("redirects", "0004_denormalize-from-url"),
    ]

    operations = [
        migrations.AddField(
            model_name="redirect",
            name="force",
            field=models.BooleanField(
                default=False,
                help_text="Apply the redirect even if the page exists.",
                null=True,
                verbose_name="Force redirect",
            ),
        ),
    ]
