# Generated by Django 4.2.8 on 2024-01-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("redirects", "0007_migrate_to_new_syntax"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redirect",
            name="position",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Order of execution of the redirect.",
                verbose_name="Position",
            ),
        ),
    ]
