# Generated by Django 4.2.9 on 2024-01-30 16:33
from django.db import migrations
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("redirects", "0008_alter_redirect_position"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="redirect",
            name="status",
        ),
    ]
