# Generated by Django 5.2.4 on 2025-07-15 13:25

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()
    dependencies = [
        ("redirects", "0009_remove_status_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redirect",
            name="redirect_type",
            field=models.CharField(
                choices=[
                    ("page", "Page Redirect"),
                    ("exact", "Exact Redirect"),
                    ("clean_url_to_html", "Clean URL to HTML (file/ to file.html)"),
                    (
                        "clean_url_without_trailing_slash_to_html",
                        "Clean URL, without trailing slash, to HTML (file to file.html)",
                    ),
                    ("html_to_clean_url", "HTML to clean URL (file.html to file/)"),
                ],
                help_text="The type of redirect you wish to use.",
                max_length=255,
                verbose_name="Redirect Type",
            ),
        ),
    ]
