# Generated by Django 3.2.18 on 2023-05-31 20:40
import django.db.models.deletion
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    initial = True

    dependencies = [
        ("projects", "0100_project_readthedocs_yaml_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildAPIKey",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=150,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("prefix", models.CharField(editable=False, max_length=8, unique=True)),
                ("hashed_key", models.CharField(editable=False, max_length=150)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "name",
                    models.CharField(
                        default=None,
                        help_text="A free-form name for the API key. Need not be unique. 50 characters max.",
                        max_length=50,
                    ),
                ),
                (
                    "revoked",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="If the API key is revoked, clients cannot use it anymore. (This cannot be undone.)",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Once API key expires, clients cannot use it anymore.",
                        null=True,
                        verbose_name="Expires",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project that this API key grants access to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="build_api_keys",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Build API key",
                "verbose_name_plural": "Build API keys",
                "ordering": ("-created",),
                "abstract": False,
            },
        ),
    ]
