# Generated by Django 5.2.17 on 2026-09-07 12:44

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("v2", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildapikey",
            name="description",
            field=models.TextField(
                blank=True,
                db_default="",
                default="",
                help_text="Optional description to remember what this key is used for",
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="buildapikey",
            name="internal",
            field=models.BooleanField(
                db_default=True,
                default=False,
                help_text="Internal keys are used by our builders and grant access to internal endpoints",
                verbose_name="Internal",
            ),
        ),
        migrations.AddField(
            model_name="buildapikey",
            name="permission_level",
            field=models.CharField(
                choices=[("read_only", "Read only"), ("read_write", "Read and write")],
                db_default="read_write",
                default="read_only",
                help_text="Read only keys can't modify the project in any way",
                max_length=16,
                verbose_name="Permission level",
            ),
        ),
    ]
