# Generated by Django 5.2.16 on 2026-08-17 10:26
import django.db.models.deletion
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("builds", "0074_change_external_type_label"),
        ("v2", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildapikey",
            name="build",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional. When set, this API key is scoped to a specific Build — writes are restricted to that Build (and its Version, commands, notifications). When null, the key retains project-wide scope (legacy behavior).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_keys",
                to="builds.build",
            ),
        ),
    ]
