import uuid

import django.db.models.deletion

# Generated by Django 2.2.24 on 2021-07-08 18:40
from django.db import migrations
from django.db import models
from django_safemigrate import Safe

import readthedocs.projects.validators


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    initial = True

    dependencies = [
        ("organizations", "0001_squashed"),
    ]

    operations = [
        migrations.CreateModel(
            name="SSODomain",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        max_length=128,
                        unique=True,
                        validators=[readthedocs.projects.validators.DomainNameValidator()],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SSOIntegration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=128, null=True)),
                ("token", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.Organization",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("allauth", "AllAuth"), ("email", "Email")],
                        max_length=32,
                    ),
                ),
                (
                    "domains",
                    models.ManyToManyField(
                        blank=True, related_name="ssointegrations", to="sso.SSODomain"
                    ),
                ),
            ],
        ),
    ]
