# Generated by Django 4.2.11 on 2024-04-04 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0005_socialtoken_nullable_app'),
        ('sso', '0001_squashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssointegration',
            name='saml_app',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sso_integration', to='socialaccount.socialapp'),
        ),
        migrations.AlterField(
            model_name='ssointegration',
            name='provider',
            field=models.CharField(choices=[('allauth', 'AllAuth'), ('email', 'Email'), ('saml', 'SAML')], max_length=32),
        ),
    ]
