# Generated by Django 4.2.11 on 2024-04-04 20:32

import django.db.models.deletion
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()
    dependencies = [
        ("socialaccount", "0005_socialtoken_nullable_app"),
        ("sso", "0001_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="ssointegration",
            name="saml_app",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sso_integration",
                to="socialaccount.socialapp",
            ),
        ),
        migrations.AlterField(
            model_name="ssointegration",
            name="provider",
            field=models.CharField(
                choices=[("allauth", "AllAuth"), ("email", "Email"), ("saml", "SAML")],
                max_length=32,
            ),
        ),
    ]
