# Generated by Django 4.2.18 on 2025-02-20 16:26

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()
    dependencies = [
        ("sso", "0002_add_saml_app"),
    ]

    operations = [
        migrations.AddField(
            model_name="ssointegration",
            name="using_old_dashboard",
            field=models.BooleanField(
                default=False,
                null=True,
                blank=True,
                help_text="Whether the SSO integration is using the old dashboard for authentication. Mainly used for SAML integrations.",
            ),
        ),
    ]
