# Generated by Django 1.9.12 on 2017-03-22 20:10
import django.db.models.deletion
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("oauth", "0007_org_slug_nonunique"),
    ]

    operations = [
        migrations.AddField(
            model_name="remoterepository",
            name="project",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="remote_repository",
                to="projects.Project",
            ),
        ),
    ]
