# Generated by Django 2.2.16 on 2020-09-19 12:35

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0010_index_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoterepository',
            name='ssh_url',
            field=models.CharField(blank=True, max_length=512, validators=[django.core.validators.RegexValidator(re.compile('^(git@([\\w\\.]+):)([\\w,\\-,\\_\\.]+)\\/([\\w,\\-,\\_\\.]+)(.git)$'), code='invalid', message='Enter a valid URL.')], verbose_name='SSH URL'),
        ),
    ]
