# Generated by Django 2.2.16 on 2020-10-05 06:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('oauth', '0011_add_remote_relation_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoterelation',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remote_relations', to='socialaccount.SocialAccount', verbose_name='Connected account'),
        ),
        migrations.AddField(
            model_name='remoterelation',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='remoterelation',
            name='admin',
            field=models.BooleanField(default=False, verbose_name='Has admin privilege'),
        ),
        migrations.AddField(
            model_name='remoterelation',
            name='json',
            field=jsonfield.fields.JSONField(default=dict, verbose_name='Serialized API response'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remoterelation',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified date'),
        ),
        migrations.AddField(
            model_name='remoterelation',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Publication date'),
            preserve_default=False,
        ),
    ]
