# Generated by Django 2.2.16 on 2020-10-10 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0012_data_migration_for_remote_relation_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remoterepository',
            name='account',
        ),
        migrations.RemoveField(
            model_name='remoterepository',
            name='active',
        ),
        migrations.RemoveField(
            model_name='remoterepository',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='remoterepository',
            name='json',
        ),
    ]
