# Generated by Django 5.2.11 on 2026-03-04 23:02

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()
    dependencies = [
        ("oauth", "0018_githubapp"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubappinstallation",
            name="all_repositories_selected",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Whether the installation has access to all repositories or just some of them",
            ),
        ),
        migrations.AddField(
            model_name="githubappinstallation",
            name="target_login",
            field=models.CharField(
                help_text="The account login the installation belongs to",
                max_length=255,
                null=True,
            ),
        ),
    ]
