# Generated by Django 5.2.13 on 2026-04-20 14:46

from django.db import migrations
from django.db import models
from django_safemigrate import Safe

import readthedocs.oauth.validators


class Migration(migrations.Migration):
    safe = Safe.after_deploy()

    dependencies = [
        ("oauth", "0018_githubapp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remoterepository",
            name="clone_url",
            field=models.CharField(
                blank=True,
                max_length=512,
                validators=[readthedocs.oauth.validators.CloneURLValidator()],
                verbose_name="Repository clone URL",
            ),
        ),
        migrations.AlterField(
            model_name="remoterepository",
            name="ssh_url",
            field=models.CharField(
                blank=True,
                max_length=512,
                validators=[readthedocs.oauth.validators.SshURLValidator()],
                verbose_name="SSH URL",
            ),
        ),
    ]
