# Generated by Django 3.2.13 on 2022-04-26 18:56
import django_extensions.db.fields
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BuildData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("data", models.JSONField()),
            ],
            options={
                "verbose_name_plural": "Build data",
            },
        ),
    ]
