# Generated by Django 5.2.4 on 2025-08-22 12:14

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()
    dependencies = [
        ("telemetry", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="builddata",
            index=models.Index(fields=["created"], name="telemetry_b_created_31070a_idx"),
        ),
    ]
