# Generated by Django 3.2.13 on 2022-07-19 00:43
import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "to_email",
                    models.EmailField(max_length=254, null=True, blank=True, verbose_name="E-mail"),
                ),
                ("token", models.CharField(max_length=32, unique=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="From user",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        null=True,
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="To user",
                    ),
                ),
                (
                    "expiration_date",
                    models.DateTimeField(verbose_name="Expiration date"),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="invitations_content_5a26b9_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="invitation",
            unique_together={
                ("to_email", "content_type", "object_id"),
                ("to_user", "content_type", "object_id"),
            },
        ),
    ]
