import django.db.models.deletion
import django_extensions.db.fields

# Generated by Django 2.2.24 on 2021-07-29 18:34
from django.conf import settings
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    initial = True

    dependencies = [
        ("projects", "0080_historicalproject"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "log_user_id",
                    models.IntegerField(
                        blank=True, db_index=True, null=True, verbose_name="User ID"
                    ),
                ),
                (
                    "log_user_username",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=150,
                        null=True,
                        verbose_name="Username",
                    ),
                ),
                (
                    "log_project_id",
                    models.IntegerField(
                        blank=True, db_index=True, null=True, verbose_name="Project ID"
                    ),
                ),
                (
                    "log_project_slug",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=63,
                        null=True,
                        verbose_name="Project slug",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("pageview", "Page view"),
                            ("authentication", "Authentication"),
                            ("authentication-failure", "Authentication failure"),
                            ("log-out", "Log out"),
                        ],
                        max_length=150,
                        verbose_name="Action",
                    ),
                ),
                (
                    "auth_backend",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Auth backend",
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="IP address"),
                ),
                (
                    "browser",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Browser user-agent",
                    ),
                ),
                (
                    "resource",
                    models.CharField(
                        blank=True, max_length=5500, null=True, verbose_name="Resource"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.Project",
                        verbose_name="Project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
