# Generated by Django 2.2.24 on 2021-09-13 22:06
from django.db import migrations
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("audit", "0002_add_organization"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={"ordering": ["-created"]},
        ),
    ]
