# Generated by Django 2.2.24 on 2021-09-21 12:22
from django.db import migrations
from django_safemigrate import Safe


def forwards_func(apps, schema_editor):
    """
    Post migration ip field from GenericIPAddressField to CharField.

    GenericIPAddressField saves the IP with ``{ip}/{range}`` format.
    We don't need to show the range to users.
    """
    AuditLog = apps.get_model("audit", "AuditLog")
    for auditlog in AuditLog.objects.all().iterator():
        ip = auditlog.ip
        if ip:
            ip = ip.split("/", maxsplit=1)[0]
            auditlog.ip = ip
            auditlog.save()


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("audit", "0004_change_ip_field_type"),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
