# Generated by Django 3.2.15 on 2022-09-15 16:43
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("audit", "0006_add_download_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="data",
            field=models.JSONField(
                blank=True,
                help_text="Extra data about the log entry. Its structure depends on the type of log entry.",
                null=True,
            ),
        ),
    ]
