# Generated by Django 3.2.15 on 2022-09-20 14:28
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("audit", "0007_auditlog_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("pageview", "Page view"),
                    ("download", "Download"),
                    ("authentication", "Authentication"),
                    ("authentication-failure", "Authentication failure"),
                    ("log-out", "Log out"),
                    ("invitation-sent", "Invitation sent"),
                    ("invitation-revoked", "Invitation revoked"),
                    ("invitation-accepted", "Invitation accepted"),
                    ("invitation-declined", "Invitation declined"),
                ],
                max_length=150,
                verbose_name="Action",
            ),
        ),
    ]
