# Generated by Django 5.2.8 on 2026-03-25 14:33

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("audit", "0008_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("pageview", "Page view"),
                    ("download", "Download"),
                    ("authentication", "Authentication"),
                    ("authentication-failure", "Authentication failure"),
                    ("log-out", "Log out"),
                    ("invitation-sent", "Invitation sent"),
                    ("invitation-revoked", "Invitation revoked"),
                    ("invitation-accepted", "Invitation accepted"),
                    ("invitation-declined", "Invitation declined"),
                    ("project-delete", "Project deleted"),
                ],
                max_length=150,
                verbose_name="Action",
            ),
        ),
    ]
