# Generated by Django 5.2.4 on 2025-01-XX XX:XX
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    
    dependencies = [
        ("audit", "0008_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="log_project_slug",
            field=models.CharField(
                max_length=55,
                blank=True,
                null=True,
                db_index=True,
                verbose_name="Project slug",
            ),
        ),
    ]
