# Generated by Django 1.11.16 on 2018-10-31 11:25
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("integrations", "0002_add-webhook"),
    ]

    operations = [
        migrations.CreateModel(
            name="BitbucketWebhook",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
            },
            bases=("integrations.integration",),
        ),
        migrations.CreateModel(
            name="GenericAPIWebhook",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
            },
            bases=("integrations.integration",),
        ),
        migrations.CreateModel(
            name="GitHubWebhook",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
            },
            bases=("integrations.integration",),
        ),
        migrations.CreateModel(
            name="GitLabWebhook",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
            },
            bases=("integrations.integration",),
        ),
        migrations.AlterField(
            model_name="integration",
            name="integration_type",
            field=models.CharField(
                choices=[
                    ("github_webhook", "GitHub incoming webhook"),
                    ("bitbucket_webhook", "Bitbucket incoming webhook"),
                    ("gitlab_webhook", "GitLab incoming webhook"),
                    ("api_webhook", "Generic API incoming webhook"),
                ],
                max_length=32,
                verbose_name="Integration type",
            ),
        ),
    ]
