# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-10 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import readthedocs.integrations.utils


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_add_integration_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='secret',
            field=models.CharField(blank=True, default=readthedocs.integrations.utils.get_secret, help_text='Secret used to validate the payload of the webhook', max_length=255, null=True),
        ),
    ]
