# Generated by Django 1.11.16 on 2018-12-10 22:08
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("integrations", "0004_add_integration_secret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integration",
            name="secret",
            field=models.CharField(
                blank=True,
                help_text="Secret used to validate the payload of the webhook",
                max_length=255,
                null=True,
            ),
        ),
    ]
