# Generated by Django 1.11.27 on 2020-02-18 19:00
from django.db import migrations
from django_safemigrate import Safe


def forwards_func(apps, schema_editor):
    """Old models with provider_data='' are being fetched as str instead of json."""
    Integration = apps.get_model("integrations", "Integration")

    Integration.objects.filter(
        provider_data="",
    ).update(
        provider_data={},
    )


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("integrations", "0006_set-default-value-provider-data"),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
