# Generated by Django 3.2.11 on 2022-01-31 11:47
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("integrations", "0007_update-provider-data"),
    ]

    operations = [
        migrations.AddField(
            model_name="httpexchange",
            name="request_headers_json",
            field=models.JSONField(null=True, blank=True, verbose_name="Request headers"),
        ),
        migrations.AddField(
            model_name="httpexchange",
            name="response_headers_json",
            field=models.JSONField(null=True, blank=True, verbose_name="Request headers"),
        ),
        migrations.AddField(
            model_name="integration",
            name="provider_data_json",
            field=models.JSONField(null=True, blank=True, verbose_name="Provider data"),
        ),
    ]
