# Generated by Django 2.2.10 on 2020-03-13 18:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_update-provider-data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='httpexchange',
            name='request_headers',
            field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Request headers'),
        ),
        migrations.AlterField(
            model_name='httpexchange',
            name='response_headers',
            field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Request headers'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='provider_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Provider data'),
        ),
    ]
