# Generated by Django 3.2.11 on 2022-01-31 12:12
from django.db import migrations
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("integrations", "0009_migrate_headers_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="httpexchange",
            name="request_headers",
        ),
        migrations.RemoveField(
            model_name="httpexchange",
            name="response_headers",
        ),
        migrations.RemoveField(
            model_name="integration",
            name="provider_data",
        ),
        migrations.RenameField(
            model_name="httpexchange",
            old_name="request_headers_json",
            new_name="request_headers",
        ),
        migrations.RenameField(
            model_name="httpexchange",
            old_name="response_headers_json",
            new_name="response_headers",
        ),
        migrations.RenameField(
            model_name="integration",
            old_name="provider_data_json",
            new_name="provider_data",
        ),
    ]
