# Generated by Django 5.2.1 on 2025-06-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0014_add_index_speedup'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubApp',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('integrations.integration',),
        ),
        migrations.AlterField(
            model_name='integration',
            name='integration_type',
            field=models.CharField(choices=[('github_webhook', 'GitHub incoming webhook'), ('bitbucket_webhook', 'Bitbucket incoming webhook'), ('gitlab_webhook', 'GitLab incoming webhook'), ('api_webhook', 'Generic API incoming webhook'), ('githubapp', 'GitHub App')], max_length=32, verbose_name='Integration type'),
        ),
    ]
