# Generated by Django 5.2.16 on 2026-07-29 15:57

from django.db import migrations
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()

    dependencies = [
        ("integrations", "0015_add_github_app_integration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="integration",
            options={"get_latest_by": "modified", "ordering": ("pk",)},
        ),
    ]
