# Generated by Django 1.9.12 on 2017-10-27 00:17
from django.db import migrations
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("builds", "0003_add-cold-storage"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIVersion",
            fields=[],
            options={
                "proxy": True,
            },
            bases=("builds.version",),
        ),
    ]
