# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-02 13:24
import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0005_remove-version-alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='_config',
            field=jsonfield.fields.JSONField(default=dict, verbose_name='Configuration used in the build'),
        ),
    ]
