# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-28 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0007_add-automation-rules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='tags',
        ),
    ]
