# Generated by Django 1.11.22 on 2019-07-25 17:24
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("builds", "0009_added_external_version_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="versionautomationrule",
            name="description",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Description"
            ),
        ),
    ]
