# Generated by Django 1.11.23 on 2019-10-07 23:32
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("builds", "0010_add-description-field-to-automation-rule"),
    ]

    operations = [
        migrations.AddField(
            model_name="version",
            name="has_epub",
            field=models.BooleanField(default=False, verbose_name="Has ePub"),
        ),
        migrations.AddField(
            model_name="version",
            name="has_htmlzip",
            field=models.BooleanField(default=False, verbose_name="Has HTML Zip"),
        ),
        migrations.AddField(
            model_name="version",
            name="has_pdf",
            field=models.BooleanField(default=False, verbose_name="Has PDF"),
        ),
    ]
