# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-13 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0010_add-description-field-to-automation-rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionautomationrule',
            name='action',
            field=models.CharField(choices=[('activate-version', 'Activate version on match'), ('set-default-version', 'Set as default version on match')], help_text='Action to apply to matching versions', max_length=32, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='versionautomationrule',
            name='version_type',
            field=models.CharField(choices=[('branch', 'Branch'), ('tag', 'Tag'), ('external', 'External'), ('unknown', 'Unknown')], help_text='Type of version the rule should be applied to', max_length=32, verbose_name='Version type'),
        ),
    ]
