# Generated by Django 1.11.25 on 2019-11-05 23:54
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("builds", "0011_version-media-availability"),
    ]

    operations = [
        migrations.AddField(
            model_name="versionautomationrule",
            name="predefined_match_arg",
            field=models.CharField(
                blank=True,
                choices=[
                    ("all-versions", "Any version"),
                    ("semver-versions", "SemVer versions"),
                    (None, "Custom match"),
                ],
                default=None,
                help_text="Match argument defined by us, it is used if is not None, otherwise match_arg will be used.",
                max_length=255,
                null=True,
                verbose_name="Predefined match argument",
            ),
        ),
        migrations.AlterField(
            model_name="versionautomationrule",
            name="action",
            field=models.CharField(
                choices=[
                    ("activate-version", "Activate version"),
                    ("set-default-version", "Set version as default"),
                ],
                help_text="Action to apply to matching versions",
                max_length=32,
                verbose_name="Action",
            ),
        ),
        migrations.AlterField(
            model_name="versionautomationrule",
            name="version_type",
            field=models.CharField(
                choices=[
                    ("branch", "Branch"),
                    ("tag", "Tag"),
                    ("external", "External"),
                    ("unknown", "Unknown"),
                ],
                help_text="Type of version the rule should be applied to",
                max_length=32,
                verbose_name="Version type",
            ),
        ),
    ]
