# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-05 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0011_version-media-availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionautomationrule',
            name='action',
            field=models.CharField(choices=[('activate-version', 'Activate version'), ('set-default-version', 'Set version as default')], help_text='Action to apply to matching versions', max_length=32, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='versionautomationrule',
            name='version_type',
            field=models.CharField(choices=[('branch', 'Branch'), ('tag', 'Tag'), ('external', 'External'), ('unknown', 'Unknown')], help_text='Type of version the rule should be applied to', max_length=32, verbose_name='Version type'),
        ),
    ]
