# Generated by Django 1.11.27 on 2020-01-14 17:37
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("builds", "0012_add-predefined-match-arg-field"),
    ]

    operations = [
        migrations.AddField(
            model_name="version",
            name="documentation_type",
            field=models.CharField(
                choices=[
                    ("sphinx", "Sphinx Html"),
                    ("mkdocs", "Mkdocs (Markdown)"),
                    ("sphinx_htmldir", "Sphinx HtmlDir"),
                    ("sphinx_singlehtml", "Sphinx Single Page HTML"),
                ],
                default="sphinx",
                help_text="Type of documentation the version was built with.",
                max_length=20,
                verbose_name="Documentation type",
            ),
        ),
    ]
