# Generated by Django 2.2.11 on 2020-03-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0014_migrate-doctype-from-project-to-version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='state',
            field=models.CharField(choices=[('triggered', 'Triggered'), ('pulling-cache', 'Pulling cache'), ('cloning', 'Cloning'), ('installing', 'Installing'), ('building', 'Building'), ('pushing-cache', 'Pushing cache'), ('finished', 'Finished')], default='finished', max_length=55, verbose_name='State'),
        ),
    ]
