# Generated by Django 2.2.10 on 2020-03-13 18:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0014_migrate-doctype-from-project-to-version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='_config',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Configuration used in the build'),
        ),
    ]
