# Generated by Django 2.2.11 on 2020-03-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0014_migrate-doctype-from-project-to-version'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Hide this version from the footer and search results?', verbose_name='Hidden'),
        ),
    ]
