# Generated by Django 2.2.12 on 2020-04-17 23:18
from django.db import migrations
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("builds", "0016_add_mkdocs_html_doctype"),
    ]

    operations = [
        # TODO: something changed in Django 5.2 that I need to comment this index together here.
        # We need to research a little more.
        #
        # ValueError: Found wrong number (0) of constraints for builds_build(date, id)
        #
        # migrations.AlterIndexTogether(
        #     name="build",
        #     index_together={("date", "id"), ("version", "state", "type")},
        # ),
    ]
