# Generated by Django 2.2.12 on 2020-04-17 23:18
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("builds", "0016_add_mkdocs_html_doctype"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="build",
            index=models.Index(
                fields=["version", "state", "type"], name="builds_buil_version_dd29f9_idx"
            ),
        ),
    ]
