# Generated by Django 2.2.12 on 2020-04-17 23:18
from django.db import migrations
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy
    dependencies = [
        ("builds", "0016_add_mkdocs_html_doctype"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="build",
            index_together={("date", "id"), ("version", "state", "type")},
        ),
    ]
