# Generated by Django 2.2.11 on 2020-03-18 01:47
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("builds", "0017_builds_deterministic_order_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="version",
            name="hidden",
            field=models.BooleanField(
                null=True,
                default=False,
                help_text="Hide this version from the version (flyout) menu and search results?",
                verbose_name="Hidden",
            ),
        ),
    ]
