# Generated by Django 2.2.12 on 2020-04-29 20:08
from django.db import migrations
from django_safemigrate import Safe


def forwards_func(apps, schema_editor):
    """Make all hidden fields not none."""
    Version = apps.get_model("builds", "Version")
    Version.objects.filter(hidden=None).update(hidden=False)


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("builds", "0019_migrate_protected_versions_to_hidden"),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
