# Generated by Django 2.2.12 on 2020-04-29 20:02
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("builds", "0020_migrate_null_hidden_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="hidden",
            field=models.BooleanField(
                default=False,
                help_text="Hide this version from the version (flyout) menu and search results?",
                verbose_name="Hidden",
            ),
        ),
    ]
