from django.conf import settings

# Generated by Django 2.2.12 on 2020-05-18 20:06
from django.db import migrations
from django_safemigrate import Safe


def forwards_func(apps, schema_editor):
    """
    Migrate all protected versions.

    For .org, we mark them as public,
    and for .com we mark them as private.
    """
    Version = apps.get_model("builds", "Version")
    target_privacy_level = "private" if settings.ALLOW_PRIVATE_REPOS else "public"
    Version.objects.filter(privacy_level="protected").update(
        privacy_level=target_privacy_level,
    )


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("builds", "0021_make_hidden_field_not_null"),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
