# Generated by Django 2.2.12 on 2020-06-03 15:17
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("builds", "0022_migrate_protected_versions"),
    ]

    operations = [
        migrations.AddField(
            model_name="build",
            name="status_code",
            field=models.BooleanField(
                blank=True, default=None, null=True, verbose_name="Status code"
            ),
        ),
    ]
