# Generated by Django 2.2.12 on 2020-06-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0023_add_status_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='status_code',
        ),
        migrations.AddField(
            model_name='build',
            name='status',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('duplicated', 'Duplicated')], default=None, max_length=32, null=True, verbose_name='Status'),
        ),
    ]
