# Generated by Django 2.2.12 on 2020-07-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0026_add_hide_version_automation_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionautomationrule',
            name='action',
            field=models.CharField(choices=[('activate-version', 'Activate version'), ('hide-version', 'Hide version'), ('make-version-public', 'Make version public'), ('make-version-private', 'Make version private'), ('set-default-version', 'Set version as default')], help_text='Action to apply to matching versions', max_length=32, verbose_name='Action'),
        ),
    ]
