# Generated by Django 2.2.16 on 2020-11-18 16:26

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("builds", "0028_add_delete_version_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="version",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, null=True, verbose_name="created"
            ),
        ),
        migrations.AddField(
            model_name="version",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, null=True, verbose_name="modified"
            ),
        ),
    ]
