# Generated by Django 2.2.17 on 2020-11-25 15:56
from django.db import migrations
from django_safemigrate import Safe


def forwards_func(apps, schema_editor):
    """Migrate all data from versions to builds."""
    Build = apps.get_model("builds", "Build")
    for build in Build.objects.all().iterator():
        # When the build is saved, the fields are updated.
        build.save()


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("builds", "0031_add_version_fields_to_build"),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
