# Generated by Django 2.2.17 on 2020-11-25 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0032_migrate_version_data_to_build'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds', to='builds.Version', verbose_name='Version'),
        ),
    ]
