# Generated by Django 2.2.17 on 2021-03-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0033_dont_cascade_delete_builds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='state',
            field=models.CharField(choices=[('triggered', 'Triggered'), ('cloning', 'Cloning'), ('installing', 'Installing'), ('building', 'Building'), ('uploading', 'Uploading'), ('finished', 'Finished')], default='triggered', max_length=55, verbose_name='State'),
        ),
    ]
