# Generated by Django 2.2.23 on 2021-06-03 23:55
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("builds", "0034_remove_protected_privacy_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="build",
            name="date",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="build",
            name="state",
            field=models.CharField(
                choices=[
                    ("triggered", "Triggered"),
                    ("cloning", "Cloning"),
                    ("installing", "Installing"),
                    ("building", "Building"),
                    ("uploading", "Uploading"),
                    ("finished", "Finished"),
                ],
                db_index=True,
                default="finished",
                max_length=55,
                verbose_name="State",
            ),
        ),
        migrations.AddIndex(
            model_name="build",
            index=models.Index(fields=["project", "date"], name="builds_buil_project_fea68c_idx"),
        ),
    ]
