# Generated by Django 2.2.24 on 2021-08-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0036_change_mkdocs_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='privacy_level',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', help_text='Allow public access to the docs from this version?', max_length=20, verbose_name='Privacy Level'),
        ),
    ]
