# Generated by Django 3.2.11 on 2022-01-31 11:47
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("builds", "0037_alter_build_cold_storage"),
    ]

    operations = [
        migrations.AddField(
            model_name="build",
            name="_config_json",
            field=models.JSONField(
                null=True, blank=True, verbose_name="Configuration used in the build"
            ),
        ),
    ]
