# Generated by Django 3.2.11 on 2022-01-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0037_alter_build_cold_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='task_id',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Celery task id'),
        ),
    ]
