# Generated by Django 3.2.11 on 2022-01-31 11:47

from django.db import migrations, models
from django.db.models import F
from django.db.models.functions import Cast


def forwards_func(apps, schema_editor):
    Build = apps.get_model('builds', 'Build')
    (
        Build.objects
        .annotate(_config_in_json=Cast('_config', output_field=models.JSONField()))
        # Copy `_config` JSONField (text) into `_config_json` (jsonb)
        .update(_config_json=F('_config_in_json'))
    )


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0037_alter_build_cold_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='_config_json',
            field=models.JSONField(default=dict, verbose_name='Configuration used in the build'),
        ),
        migrations.RunPython(forwards_func)
    ]
