# Generated by Django 3.2.11 on 2022-01-31 12:12
from django.db import migrations
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("builds", "0039_migrate_config_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="build",
            name="_config",
        ),
        migrations.RenameField(
            model_name="build",
            old_name="_config_json",
            new_name="_config",
        ),
    ]
