# Generated by Django 3.2.12 on 2022-04-21 13:50
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


def forwards_func(apps, schema_editor):
    """
    Migrate external Versions with `active=False` to use `state=Closed` and `active=True`.
    """
    Version = apps.get_model("builds", "Version")
    # NOTE: we can't use `Version.external` because the Django's __fake__
    # object does not declare it. So, we need to pass `type=external` in the
    # filter
    Version.objects.filter(type="external", active=False).update(
        active=True,
        state="closed",
    )


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("builds", "0041_track_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="version",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[("open", "Open"), ("closed", "Closed")],
                help_text="State of the PR/MR associated to this version.",
                max_length=20,
                null=True,
                verbose_name="State",
            ),
        ),
        migrations.RunPython(forwards_func),
    ]
