# Generated by Django 3.2.13 on 2022-07-11 08:53
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("builds", "0045_alter_build_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="identifier",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Identifier"
            ),
        ),
    ]
