# Generated by Django 3.2.16 on 2023-01-26 23:46
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("builds", "0046_identifier_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="build",
            name="state",
            field=models.CharField(
                choices=[
                    ("triggered", "Triggered"),
                    ("cloning", "Cloning"),
                    ("installing", "Installing"),
                    ("building", "Building"),
                    ("uploading", "Uploading"),
                    ("finished", "Finished"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="triggered",
                max_length=55,
                verbose_name="State",
            ),
        ),
    ]
