# Generated by Django 3.2.18 on 2023-03-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builds", "0047_build_default_triggered"),
    ]

    operations = [
        migrations.AddField(
            model_name="version",
            name="build_data",
            field=models.JSONField(
                default=None,
                null=True,
                verbose_name="Data generated at build time by the doctool (`readthedocs-build.yaml`).",
            ),
        ),
    ]
