# Generated by Django 3.2.18 on 2023-03-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0047_build_default_triggered"),
    ]

    operations = [
        migrations.AddField(
            model_name="build",
            name="build_config_file",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=1024,
                null=True,
                verbose_name="Non-default build configuration file used",
            ),
        ),
    ]
