# Generated by Django 3.2.18 on 2023-03-21 22:56

from django.db import migrations, models

import readthedocs.projects.validators


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0048_add_build_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="build",
            name="build_config_file",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=1024,
                null=True,
                validators=[readthedocs.projects.validators.validate_build_config_file],
                verbose_name="Non-default build configuration file used",
            ),
        ),
    ]
