# Generated by Django 4.2.4 on 2023-08-31 23:47
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("builds", "0052_alter_versionautomationrule_polymorphic_ctype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="build_data",
            field=models.JSONField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Data generated at build time by the doctool (`readthedocs-build.yaml`).",
            ),
        ),
    ]
