# Generated by Django 4.2.6 on 2023-10-18 11:43
from django.db import migrations
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("builds", "0053_alter_version_build_data"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="build",
            index_together={
                ("version", "state", "date", "success"),
            },
        ),
    ]
