# Generated by Django 4.2.5 on 2023-11-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builds", "0054_add_builds_index_for_addons"),
    ]

    operations = [
        migrations.AlterField(
            model_name="versionautomationrule",
            name="priority",
            field=models.IntegerField(
                default=0,
                help_text="A lower number (0) means a higher priority",
                verbose_name="Rule priority",
            ),
        ),
    ]
