# Generated by Django 4.2.9 on 2024-02-01 20:29

import datetime

from django.db import migrations
from django_safemigrate import Safe


def migrate(apps, schema_editor):
    """
    Migrate the created and modified fields of the Version model to have a non-null value.

    This date corresponds to the release date of 5.6.5,
    when the created field was added to the Version model
    at https://github.com/readthedocs/readthedocs.org/commit/d72ee6e27dc398b97e884ccec8a8cf135134faac.
    """
    Version = apps.get_model("builds", "Version")
    date = datetime.datetime(2020, 11, 23, tzinfo=datetime.timezone.utc)
    Version.objects.filter(created=None).update(created=date)
    Version.objects.filter(modified=None).update(modified=date)


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("builds", "0056_alter_versionautomationrule_priority"),
    ]

    operations = [
        migrations.RunPython(migrate),
    ]
