# Generated by Django 4.2.9 on 2024-02-01 20:38

import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()

    dependencies = [
        ("builds", "0057_migrate_timestamp_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="version",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True,
                default=django.utils.timezone.now,
                verbose_name="modified",
            ),
            preserve_default=False,
        ),
    ]
