# Generated by Django 4.2.16 on 2024-09-23 18:18

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.always()
    dependencies = [
        ("builds", "0058_alter_version_created_alter_version_modified"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="build",
            index=models.Index(fields=["version", "date"], name="builds_buil_version_259bbf_idx"),
        ),
    ]
