# Generated by Django 4.2.16 on 2024-12-02 15:05

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy

    dependencies = [
        ('builds', '0059_add_version_date_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('original_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('user_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('original_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('user_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='override', to='builds.version')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
