# Generated by Django 4.2.17 on 2025-02-18 21:38

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("builds", "0060_alter_version_slug"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="build",
            index_together={
                ("version", "state", "date", "success"),
            },
        ),
        migrations.AlterField(
            model_name="version",
            name="type",
            field=models.CharField(
                choices=[
                    ("branch", "Branch"),
                    ("tag", "Tag"),
                    ("external", "External"),
                    ("unknown", "Unknown"),
                ],
                db_index=True,
                default="unknown",
                max_length=20,
                verbose_name="Type",
            ),
        ),
    ]
