# Generated by Django 5.2 on 2025-04-16 11:28

from django.db import migrations
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("builds", "0061_remove_unused_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="build",
            new_name="builds_buil_version_ee7034_idx",
            old_fields=("version", "state", "date", "success"),
        ),
        migrations.RenameIndex(
            model_name="build",
            new_name="builds_buil_version_dd29f9_idx",
            old_fields=("version", "state", "type"),
        ),
    ]
