# Generated by Django 5.2.1 on 2025-06-09 22:47

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("builds", "0062_rename_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildcommandresult",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Start time"),
        ),
        migrations.AlterField(
            model_name="buildcommandresult",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="End time"),
        ),
        migrations.AlterField(
            model_name="buildcommandresult",
            name="exit_code",
            field=models.IntegerField(blank=True, null=True, verbose_name="Command exit code"),
        ),
    ]
