# Generated by Django 5.2.4 on 2025-07-17 11:39

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("builds", "0063_alter_buildcommandresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="build",
            name="healthcheck",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Healthcheck"),
        ),
    ]
