# Generated by Django 5.2.6 on 2025-09-30 12:39

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("builds", "0064_healthcheck"),
    ]

    operations = [
        migrations.AddField(
            model_name="build",
            name="task_executed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Task executed at datetime"
            ),
        ),
    ]
