# Generated by Django 5.2.8 on 2025-12-04 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0065_task_executed_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['verbose_name']},
        ),
    ]
