# Generated by Django 5.2.9 on 2026-01-15 14:23

from django.db import migrations
from django_safemigrate import Safe


# NOTE: borrowed from builds/models.py Build.config @property
def _get_config(Build, build):
    CONFIG_KEY = "__config"
    if build._config and CONFIG_KEY in build._config:
        return Build.objects.only("_config").get(pk=build._config[CONFIG_KEY])._config
    return build._config


def forward_create_buildconfig(apps, schema_editor):
    BuildConfig = apps.get_model("builds", "BuildConfig")
    Build = apps.get_model("builds", "Build")

    for build in (
        Build.objects.filter(
            readthedocs_yaml_config__isnull=True,
            _config__isnull=False,
        )
        .only("id", "_config")
        .iterator()
    ):
        build_config = _get_config(Build, build)
        readthedocs_yaml_config, _ = BuildConfig.objects.get_or_create(data=build_config)
        Build.objects.filter(pk=build.id).update(
            readthedocs_yaml_config_id=readthedocs_yaml_config.id
        )


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("builds", "0066_add_buildconfig_model"),
    ]

    operations = [
        migrations.RunPython(
            forward_create_buildconfig,
            migrations.RunPython.noop,
        )
    ]
