# Generated by Django 5.2.9 on 2026-01-15 16:19

from django.db import migrations
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()

    dependencies = [
        ("builds", "0066_add_buildconfig_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="build",
            name="_config",
        ),
    ]
