# Generated by Django 5.2.9 on 2026-01-15 14:23

from django.db import migrations
from django_safemigrate import Safe


def forward_create_buildconfig(apps, schema_editor):
    BuildConfig = apps.get_model("builds", "BuildConfig")
    Build = apps.get_model("builds", "Build")

    for build in Build.objects.filter(
        readthedocs_yaml_config__isnull=True,
        _config__isnull=False,
    ).iterator():
        build.readthedocs_yaml_config, _ = BuildConfig.objects.get_or_create(data=build.config)
        build.save(update_fields=["readthedocs_yaml_config"])


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("builds", "0066_add_buildconfig_model"),
    ]

    operations = [migrations.RunPython(forward_create_buildconfig)]
