# Generated by Django 5.2.9 on 2026-01-21 15:23

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("builds", "0066_add_buildconfig_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildconfig",
            name="data_hash",
            field=models.CharField(editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="buildconfig",
            name="data",
            field=models.JSONField(
                help_text="The rendered YAML configuration used in the build",
                verbose_name="Configuration data",
            ),
        ),
    ]
