# Generated by Django 5.2.9 on 2026-01-21 15:23

import hashlib
import json

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


def forward_update_data_hash(apps, schema_editor):
    BuildConfig = apps.get_model("builds", "BuildConfig")

    for config in BuildConfig.objects.filter(data__isnull=False).iterator():
        dump = json.dumps(config.data)
        data_hash = hashlib.sha256(dump.encode("utf-8")).hexdigest()
        BuildConfig.objects.filter(pk=config.id).update(
            data_hash=data_hash,
        )


class Migration(migrations.Migration):
    safe = Safe.after_deploy()

    dependencies = [
        ("builds", "0067_migrate_buildconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildconfig",
            name="data_hash",
            field=models.CharField(editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="buildconfig",
            name="data",
            field=models.JSONField(
                help_text="The rendered YAML configuration used in the build",
                verbose_name="Configuration data",
            ),
        ),
        migrations.RunPython(
            forward_update_data_hash,
            migrations.RunPython.noop,
        ),
    ]
