# Generated by Django 5.2.9 on 2026-02-02 12:05

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("builds", "0067_migrate_buildconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookAutomationRule",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("builds.versionautomationrule",),
        ),
        migrations.AlterField(
            model_name="automationrulematch",
            name="action",
            field=models.CharField(
                choices=[
                    ("activate-version", "Activate version"),
                    ("hide-version", "Hide version"),
                    ("make-version-public", "Make version public"),
                    ("make-version-private", "Make version private"),
                    ("set-default-version", "Set version as default"),
                    ("delete-version", "Delete version"),
                    ("trigger-build", "Trigger build for version"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="versionautomationrule",
            name="action",
            field=models.CharField(
                choices=[
                    ("activate-version", "Activate version"),
                    ("hide-version", "Hide version"),
                    ("make-version-public", "Make version public"),
                    ("make-version-private", "Make version private"),
                    ("set-default-version", "Set version as default"),
                    ("delete-version", "Delete version"),
                    ("trigger-build", "Trigger build for version"),
                ],
                help_text="Action to apply to matching versions",
                max_length=32,
                verbose_name="Action",
            ),
        ),
    ]
