# Generated by Django 5.2.8 on 2026-02-20 06:49

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("builds", "0069_add_webhook_automation_rule"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildcommandresult",
            name="build_job",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Build job",
            ),
        ),
    ]
