# Generated by Django 5.2.10 on 2026-02-25 15:26

from django.db import migrations
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("builds", "0069_add_webhook_automation_rule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="build",
            name="_config",
        ),
    ]
