# Generated by Django 5.2.12 on 2026-04-08 11:03

import django.db.models.deletion
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()

    dependencies = [
        ("builds", "0070_delete_build_old_config"),
        ("projects", "0163_automationrule_data_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automationrulematch",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="projects.automationrule",
                verbose_name="Matched rule",
            ),
        ),
        migrations.AlterField(
            model_name="versionautomationrule",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="version_automation_rules",
                to="projects.project",
            ),
        ),
    ]
