# Generated by Django 5.2.10 on 2026-03-16 15:40

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()
    dependencies = [
        ("builds", "0071_add_automationrule_v2"),
        ("projects", "0158_add_search_subproject_filter_option"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automationrule",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, verbose_name="created"
            ),
        ),
        migrations.AlterField(
            model_name="automationrule",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
        migrations.AlterField(
            model_name="automationrule",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="automation_rules",
                to="projects.project",
                verbose_name="Project",
            ),
        ),
        migrations.AlterField(
            model_name="automationrulematch",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="builds.automationrule",
                verbose_name="Matched rule",
            ),
        ),
        migrations.AlterField(
            model_name="versionautomationrule",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="version_automation_rules",
                to="projects.project",
            ),
        ),
    ]
