# Generated by Django 5.2.13 on 2026-04-22 14:13

from django.db import migrations
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()

    dependencies = [
        ("builds", "0071_alter_versionautomationrule_fk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="build",
            name="error",
        ),
        migrations.RemoveField(
            model_name="build",
            name="exit_code",
        ),
        migrations.RemoveField(
            model_name="build",
            name="output",
        ),
        migrations.RemoveField(
            model_name="build",
            name="setup",
        ),
        migrations.RemoveField(
            model_name="build",
            name="setup_error",
        ),
    ]
