# Generated by Django 5.2.13 on 2026-06-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0072_remove_deprecated_build_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="version",
            name="base_identifier",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Base identifier"
            ),
        ),
    ]
