# Generated by Django 5.2.13 on 2026-06-03 09:32

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("builds", "0072_remove_deprecated_build_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="build",
            name="task_arn",
            field=models.CharField(
                blank=True,
                help_text="ECS task ARN for builds dispatched via Fargate. Set by ``submit_build_to_ecs``; consumed by ``cancel_build`` to call ``ecs:StopTask``. Mutually exclusive with ``task_id`` (legacy Celery path).",
                max_length=255,
                null=True,
                verbose_name="ECS task ARN",
            ),
        ),
    ]
