# Generated by Django 5.2.13 on 2026-05-27 17:44

import django.db.models.deletion
from django.db import migrations, models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()

    dependencies = [
        ("builds", "0072_remove_deprecated_build_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="build",
            name="diff_base_build",
            field=models.ForeignKey(
                blank=True,
                help_text="Build to compare against for the file tree diff. Set on the first build of a pull request version, pinning the base to the base version's latest build at PR-open time.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="builds.build",
                verbose_name="Diff base build",
            ),
        ),
    ]
