# Generated by Django 5.2.13 on 2026-06-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0072_remove_deprecated_build_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automationrulematch",
            name="version_type",
            field=models.CharField(
                choices=[
                    ("branch", "Branch"),
                    ("tag", "Tag"),
                    ("external", "Pull request"),
                    ("unknown", "Unknown"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="build",
            name="version_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("branch", "Branch"),
                    ("tag", "Tag"),
                    ("external", "Pull request"),
                    ("unknown", "Unknown"),
                ],
                max_length=32,
                null=True,
                verbose_name="Version type",
            ),
        ),
        migrations.AlterField(
            model_name="version",
            name="type",
            field=models.CharField(
                choices=[
                    ("branch", "Branch"),
                    ("tag", "Tag"),
                    ("external", "Pull request"),
                    ("unknown", "Unknown"),
                ],
                db_index=True,
                default="unknown",
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="versionautomationrule",
            name="version_type",
            field=models.CharField(
                choices=[
                    ("branch", "Branch"),
                    ("tag", "Tag"),
                    ("external", "Pull request"),
                    ("unknown", "Unknown"),
                ],
                help_text="Type of version the rule should be applied to",
                max_length=32,
                verbose_name="Version type",
            ),
        ),
    ]
