# Generated by Django 5.2.13 on 2026-06-01 09:11

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("builds", "0073_remove_deprecated_build_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="build",
            name="queue_time",
            field=models.IntegerField(blank=True, null=True, verbose_name="Queue time"),
        ),
    ]
