# Generated by Django 5.2.13 on 2026-07-06 21:37

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()
    dependencies = [
        ("builds", "0074_change_external_type_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="build",
            name="is_uploaded",
            field=models.BooleanField(
                db_default=False,
                default=False,
                verbose_name="Artifacts uploaded using the upload API",
            ),
        ),
    ]
