# Generated by Django 5.2.15 on 2026-07-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0074_change_external_type_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='is_uploaded',
            field=models.BooleanField(default=False, help_text='Whether this build was created from an external artifacts upload.', verbose_name='Is uploaded'),
        ),
    ]
