# Generated by Django 5.2.16 on 2026-09-01 16:19

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()

    dependencies = [
        ("builds", "0074_change_external_type_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="slug",
            field=models.CharField(
                db_index=True,
                help_text="A unique identifier used in the URL and links for this version. It can contain lowercase letters, numbers, dots, dashes or underscores. It must start with a lowercase letter or a number.",
                max_length=255,
                verbose_name="Slug",
            ),
        ),
    ]
