# Generated by Django 5.2.15 on 2026-07-14 23:23

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()
    dependencies = [
        ("builds", "0075_build_is_uploaded"),
    ]

    operations = [
        migrations.AddField(
            model_name="version",
            name="is_uploaded",
            field=models.BooleanField(
                db_default=False,
                default=False,
                verbose_name="Artifacts uploaded using the upload API",
            ),
        ),
    ]
