# Generated by Django 5.2.17 on 2026-08-26 19:22

from django.db import migrations
from django_safemigrate import Safe


def forward_merge_uploaded(apps, schema_editor):
    """
    Mark legacy manually uploaded versions as uploaded.

    The legacy ``uploaded`` field was used to mark versions
    manually uploaded by the core team, its replacement (``is_uploaded``)
    is used for versions uploaded using the upload API.
    Both mean the version wasn't built from the repository.
    """
    Version = apps.get_model("builds", "Version")
    Version.objects.filter(uploaded=True).update(is_uploaded=True)


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ("builds", "0077_build_dispatched_date"),
    ]

    operations = [
        migrations.RunPython(forward_merge_uploaded, migrations.RunPython.noop),
    ]
