# Generated by Django 5.2.17 on 2026-08-26 19:22

from django.db import migrations
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()

    dependencies = [
        ("builds", "0077_build_dispatched_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="version",
            name="uploaded",
        ),
    ]
