# Generated by Django 5.2.17 on 2026-09-15 09:00

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    """
    Make the field nullable before removing it.

    The column is only dropped after the deploy, so without this,
    inserts from the new code (which no longer knows about the field)
    would fail on the NOT NULL constraint during the deploy.
    """

    safe = Safe.before_deploy()

    dependencies = [
        ("builds", "0077_build_dispatched_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="uploaded",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="Uploaded",
            ),
        ),
    ]
