# Generated by Django 5.2.17

from django.db import migrations, models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()

    dependencies = [
        ('builds', '0079_remove_version_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='upload_completed_at',
            field=models.DateTimeField(blank=True, help_text='Set when the /complete endpoint is called for this upload build.', null=True, verbose_name='Upload completed at'),
        ),
    ]
