# Generated by Django 1.9.13 on 2018-07-16 15:45
from django.db import migrations
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("gold", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="golduser",
            old_name="last_4_digits",
            new_name="last_4_card_digits",
        ),
    ]
