# Generated by Django 1.9.13 on 2018-10-22 07:13
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("gold", "0003_add_missing_model_change_migrations"),
    ]

    operations = [
        migrations.AddField(
            model_name="golduser",
            name="business_vat_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
