# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-22 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0003_add_missing_model_change_migrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='golduser',
            name='business_vat_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
