# Generated by Django 2.2.17 on 2021-02-08 16:52
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("gold", "0004_add_vat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="golduser",
            name="last_4_card_digits",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
