# Generated by Django 2.2.19 on 2021-03-10 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0005_last_4_digits_null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golduser',
            name='business_vat_id',
        ),
        migrations.RemoveField(
            model_name='golduser',
            name='last_4_card_digits',
        ),
    ]
