# Generated by Django 4.2.13 on 2024-07-08 09:06

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()
    dependencies = [
        ("gold", "0006_remove_old_payments_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="golduser",
            name="level",
            field=models.CharField(
                choices=[
                    ("v1-org-5", "$5/mo"),
                    ("v1-org-10", "$10/mo"),
                    ("v1-org-15", "$15/mo"),
                    ("v1-org-20", "$20/mo"),
                    ("v1-org-50", "$50/mo"),
                    ("v1-org-100", "$100/mo"),
                ],
                default="v1-org-5",
                max_length=64,
                verbose_name="Level",
            ),
        ),
    ]
