name: Upload documentation to Read the Docs

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest
    # Pull requests from forks don't have access to secrets.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: pip install -r requirements/docs.txt

      - name: Build documentation
        working-directory: docs
        env:
          PROJECT: user
        run: sphinx-build -W --keep-going -b html . _build/html

      - name: Upload documentation to Read the Docs
        uses: readthedocs/upload-action@main
        with:
          token: ${{ secrets.READTHEDOCS_TOKEN }}
          project-slug: docs-upload
          html-dir: docs/_build/html
