name: lint_python
on: [push, pull_request]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - run: pip install codespell flake8  # pytest
      # - run: codespell --quiet-level=2  # --ignore-words-list="" --skip=""
      - run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      # - run: pip install -r requirements.txt || true
      # - run: pytest
