import datetime
import signal
import socket
import subprocess
from dataclasses import dataclass
from dataclasses import field
from pathlib import Path

import structlog
from celery import Task
from celery.exceptions import SoftTimeLimitExceeded
from django.conf import settings
from django.utils import timezone
from slumber import API

from readthedocs.api.v2.client import setup_api
from readthedocs.builds.constants import ARTIFACT_TYPES
from readthedocs.builds.constants import BUILD_FINAL_STATES
from readthedocs.builds.constants import BUILD_STATE_CANCELLED
from readthedocs.builds.constants import BUILD_STATE_CLONING
from readthedocs.builds.constants import BUILD_STATE_FINISHED
from readthedocs.builds.constants import BUILD_STATE_TRIGGERED
from readthedocs.builds.constants import BUILD_STATE_UPLOADING
from readthedocs.builds.constants import BUILD_STATUS_FAILURE
from readthedocs.builds.constants import BUILD_STATUS_SUCCESS
from readthedocs.builds.constants import UNDELETABLE_ARTIFACT_TYPES
from readthedocs.builds.models import APIVersion
from readthedocs.builds.models import Build
from readthedocs.builds.signals import build_complete
from readthedocs.builds.tasks import check_and_disable_project_for_consecutive_failed_builds
from readthedocs.builds.tasks import send_build_notifications
from readthedocs.builds.tasks import send_build_status
from readthedocs.doc_builder.environments import DockerBuildEnvironment
from readthedocs.doc_builder.exceptions import BuildAppError
from readthedocs.doc_builder.exceptions import BuildCancelled
from readthedocs.doc_builder.exceptions import BuildMaxConcurrencyError
from readthedocs.doc_builder.exceptions import BuildUserError
from readthedocs.doc_builder.exceptions import MkDocsYAMLParseError
from readthedocs.projects.exceptions import ProjectConfigurationError
from readthedocs.projects.exceptions import RepositoryError
from readthedocs.projects.models import APIProject
from readthedocs.projects.models import Feature
from readthedocs.projects.models import WebHookEvent
from readthedocs.projects.tasks.search import index_build
from readthedocs.projects.tasks.storage import StorageType
from readthedocs.projects.tasks.storage import get_storage
from readthedocs.projects.tasks.utils import BuildRequest
from readthedocs.projects.tasks.utils import clean_build
from readthedocs.projects.tasks.utils import set_builder_scale_in_protection
from readthedocs.projects.tasks.utils import stop_consuming_tasks_and_terminate
from readthedocs.worker import app


logger = structlog.get_logger(__name__)


@dataclass(slots=True)
class TaskData:
    build_id: int | None = None
    start_time: datetime.datetime = field(default_factory=timezone.now)

    api_client: API | None = None

    build: dict = field(default_factory=dict)
    version: APIVersion | None = None
    project: APIProject | None = None


class ProcessUploadedBuildTask(Task):
    name = __name__ + ".process_uploaded_build_task"
    autoretry_for = (BuildMaxConcurrencyError,)
    max_retries = settings.RTD_BUILDS_MAX_RETRIES
    default_retry_delay = settings.RTD_BUILDS_RETRY_DELAY
    retry_backoff = False
    ignore_result = True

    # Expected exceptions that will be logged as info only and not retried.
    # These exceptions are not sent to Sentry either because we are using
    # ``SENTRY_CELERY_IGNORE_EXPECTED=True``.
    #
    # All exceptions generated by a user miss-configuration should be listed
    # here. Actually, every subclass of ``BuildUserError``.
    throws = (
        BuildCancelled,
        BuildUserError,
        RepositoryError,
        MkDocsYAMLParseError,
        ProjectConfigurationError,
        BuildMaxConcurrencyError,
        SoftTimeLimitExceeded,
    )

    # Do not send notifications on failure builds for these exceptions.
    exceptions_without_notifications = (
        BuildCancelled.CANCELLED_BY_USER,
        BuildCancelled.SKIPPED_EXIT_CODE_183,
        BuildAppError.BUILDS_DISABLED,
        BuildMaxConcurrencyError.LIMIT_REACHED,
    )

    # Do not send external build status on failure builds for these exceptions.
    exceptions_without_external_build_status = (BuildMaxConcurrencyError.LIMIT_REACHED,)

    acks_late = True
    track_started = True

    # These values have to be dynamic based on project
    time_limit = None
    soft_time_limit = None

    Request = BuildRequest

    def _setup_sigterm(self):
        def sigterm_received(*args, **kwargs):
            logger.warning(
                "SIGTERM received. Waiting for build to stop gracefully after it finishes."
            )

        def sigint_received(*args, **kwargs):
            logger.warning("SIGINT received. Canceling the build running.")

            # Only allow to cancel the build if it's not already uploading the files.
            # This is to protect our users to end up with half of the documentation uploaded.
            # TODO: remove this condition once we implement "Atomic Uploads"
            if self.data.build.get("state") == BUILD_STATE_UPLOADING:
                logger.warning('Ignoring cancelling the build at "Uploading" state.')
                return

            raise BuildCancelled(message_id=BuildCancelled.CANCELLED_BY_USER)

        # Do not send the SIGTERM signal to children (pip is automatically killed when
        # receives SIGTERM and make the build to fail one command and stop build)
        signal.signal(signal.SIGTERM, sigterm_received)

        signal.signal(signal.SIGINT, sigint_received)

    def run(self, build_id, build_api_key):
        structlog.contextvars.bind_contextvars(build_id=build_id)
        logger.info("Running task.", name=self.name)
        builder = socket.gethostname()
        # Enable scale-in protection on this instance
        set_builder_scale_in_protection.delay(
            build_id=build_id,
            builder=builder,
            protected_from_scale_in=True,
        )

        self.data = TaskData(build_id=build_id)
        self.data.api_client = setup_api(build_api_key)

        self.data.build = self.data.api_client.build(build_id).get()
        logger.info("Build data retrieved.", build_data=self.data.build)
        self.data.build["builder"] = builder

        version_data = self.data.api_client.version(self.data.build["version"]).get()
        self.data.version = APIVersion(**version_data)
        self.data.project = self.data.version.project

        structlog.contextvars.bind_contextvars(
            builder=self.data.build["builder"],
            commit=self.data.build["commit"],
            project_slug=self.data.project.slug,
            version_slug=self.data.version.slug,
        )

        # Log a warning if the task took more than 10 minutes to be retried
        if self.data.build["task_executed_at"]:
            task_executed_at = datetime.datetime.fromisoformat(self.data.build["task_executed_at"])
            delta = timezone.now() - task_executed_at
            if delta > timezone.timedelta(minutes=10):
                logger.warning(
                    "This task waited more than 10 minutes to be retried.",
                    delta_minutes=round(delta.seconds / 60, 1),
                )

        # Save when the task was executed by a builder
        self.data.build["task_executed_at"] = timezone.now()

        # Clean the build paths for this version to avoid conflicts with a previous run.
        clean_build(self.data.version)

        # NOTE: this should be done before triggering the build
        # self._check_project_disabled()
        # NOTE: I think we do want this, but we should just rely on autoretry_for.
        # Maybe we also want to have a limit when starting the upload process?
        # self._check_concurrency_limit()

        # Always reset the build before starting, in case the build was retried.
        self.data.api_client.build(self.data.build_id).reset.post()

        # actual run
        build_uploads_storage = get_storage(
            build_id=self.data.build_id,
            api_client=self.data.api_client,
            storage_type=StorageType.build_uploads,
        )
        self.data.build["state"] = BUILD_STATE_CLONING
        self._update_build()

        # Download zip
        resp = self.data.api_client.command.post(
            {
                "build": self.data.build_id,
                "command": "Downloading artifacts from storage...",
                "output": "",
                "start_time": timezone.now().isoformat(),
            }
        )
        command_id = resp["id"]

        # TODO: use the build id instead? probably the docker env is hardcoded to use the version slug.
        output_dir = Path(self.data.project.checkout_path(self.data.version.slug))
        local_zip_artifacts_path = output_dir / "artifacts.zip"
        artifacts_storage_path = f"{self.data.project.id}/{self.data.build_id}/artifacts.zip"
        try:
            with build_uploads_storage.open(artifacts_storage_path, "rb") as artifacts_file:
                local_zip_artifacts_path.parent.mkdir(parents=True, exist_ok=True)
                with local_zip_artifacts_path.open("wb") as local_file:
                    local_file.write(artifacts_file.read())
        except Exception as exc:
            logger.exception(
                "Error downloading artifacts from storage",
                artifacts_storage_path=artifacts_storage_path,
            )
            self.data.api_client.command(command_id).patch(
                {
                    "output": "Error downloading artifacts from storage.",
                    "end_time": timezone.now().isoformat(),
                    "exit_code": 1,
                }
            )
            raise BuildAppError(
                BuildAppError.GENERIC_WITH_BUILD_ID,
                exception_message="Unexpected error downloading artifacts from storage.",
            ) from exc
        else:
            self.data.api_client.command(command_id).patch(
                {
                    "output": "Artifacts downloaded from storage.",
                    "end_time": timezone.now().isoformat(),
                    "exit_code": 0,
                }
            )

        environment = DockerBuildEnvironment(
            project=self.data.project,
            version=self.data.version,
            build=self.data.build,
            container_image=settings.RTD_DOCKER_CLONE_IMAGE,
            api_client=self.data.api_client,
        )
        local_artifacts_path = output_dir / "_readthedocs"
        with environment:
            # Exctract zip
            environment.run(
                "unzip",
                str(local_zip_artifacts_path),
                "-d",
                str(local_artifacts_path),
                cwd=str(output_dir),
            )

        # Validate files
        self.data.build["state"] = BUILD_STATE_UPLOADING
        self._update_build()

        logger.info("Uploading artifacts to storage.")
        # Upload artifacts to the right place
        build_media_storage = get_storage(
            build_id=self.data.build_id,
            api_client=self.data.api_client,
            storage_type=StorageType.build_media,
        )
        for media_type in ARTIFACT_TYPES:
            from_path = self.data.project.artifact_path(
                version=self.data.version.slug,
                type_=media_type,
            )
            to_path = self.data.version.get_storage_path(media_type=media_type)
            if Path(from_path).exists():
                self._log_directory_size(from_path, media_type)
                try:
                    build_media_storage.rclone_sync_directory(from_path, to_path)
                except Exception as exc:
                    logger.exception(
                        "Error copying to storage",
                        media_type=media_type,
                        from_path=from_path,
                        to_path=to_path,
                    )
                    # Re-raise the exception to fail the build and handle it
                    # automatically at `on_failure`.
                    # It will clearly communicate the error to the user.
                    raise BuildAppError(
                        BuildAppError.UPLOAD_FAILED,
                        exception_message="Error uploading files to the storage.",
                    ) from exc
            elif media_type not in UNDELETABLE_ARTIFACT_TYPES:
                try:
                    build_media_storage.delete_directory(to_path)
                except Exception as exc:
                    # NOTE: I didn't find any log line for this case yet
                    logger.exception(
                        "Error deleting files from storage",
                        media_type=media_type,
                        media_path=to_path,
                    )
                    # Re-raise the exception to fail the build and handle it
                    # automatically at `on_failure`.
                    # It will clearly communicate the error to the user.
                    raise BuildAppError(
                        BuildAppError.GENERIC_WITH_BUILD_ID,
                        exception_message="Error deleting files from storage.",
                    ) from exc

        logger.info("Artifacts uploaded.")
        self.data.build["state"] = BUILD_STATE_FINISHED
        self._update_build()

        index_build.delay(build_id=self.data.build_id)

        # Check if the project is spam
        if "readthedocsext.spamfighting" in settings.INSTALLED_APPS:
            from readthedocsext.spamfighting.tasks import (  # noqa
                spam_check_after_build_complete,
            )

            spam_check_after_build_complete.delay(build_id=self.data.build_id)

        if not self.data.project.has_valid_clone:
            self.set_valid_clone()

        send_build_notifications.delay(
            version_pk=self.data.version.id,
            build_pk=self.data.build_id,
            event=WebHookEvent.BUILD_PASSED,
        )
        send_build_status.delay(
            build_pk=self.data.build_id,
            commit=self.data.build["commit"],
            status=BUILD_STATUS_SUCCESS,
        )
        self.data.build["success"] = True
        self._update_build()

    def _update_build(self):
        if not self.data.build:
            return

        try:
            self.data.api_client.build(self.data.build_id).patch(self.data.build)
        except Exception as e:
            # Get json response from slumber
            error_json = ""
            response = getattr(e, "response", None)
            if response is not None:
                try:
                    error_json = response.json()
                except Exception:
                    pass

            # NOTE: we are updating the "Build" object on each `state`.
            # Only if the last update fails, there may be some inconsistency
            # between the "Build" object in our db and the reality.
            #
            # The `state` argument will help us to track this more and understand
            # at what state our updates are failing and decide what to do.
            logger.exception("Error while updating the build object.", error_json=error_json)

    def on_failure(self, exc, task_id, args, kwargs, einfo):
        """
        Celery handler to be executed when a task fails.

        Updates build data, adds tasks to send build notifications.

        .. note::

           Since the task has failed, some attributes from the `self.data`
           object may not be defined.
        """
        logger.info("Task failed.")
        # Known errors in our application code (e.g. we couldn't connect to
        # Docker API). Report a generic message to the user.
        if isinstance(exc, BuildAppError):
            message_id = exc.message_id

        # Known errors in the user's project (e.g. invalid config file, invalid
        # repository, command failed, etc). Report the error back to the user
        # by creating a notification attached to the build
        # Otherwise, use a notification with a generic message.
        elif isinstance(exc, BuildUserError):
            if hasattr(exc, "message_id") and exc.message_id is not None:
                message_id = exc.message_id
            else:
                message_id = BuildUserError.GENERIC

            # Set build state as cancelled if the user cancelled the build
            if isinstance(exc, BuildCancelled):
                self.data.build["state"] = BUILD_STATE_CANCELLED

        elif isinstance(exc, SoftTimeLimitExceeded):
            logger.info("Soft time limit exceeded.")
            message_id = BuildUserError.BUILD_TIME_OUT

        else:
            # We don't know what happened in the build. Log the exception and
            # report a generic notification to the user.
            # Note we are using `log.error(exc_info=...)` instead of `log.exception`
            # because this is not executed inside a try/except block.
            logger.error("Build failed with unhandled exception.", exc_info=exc)
            message_id = BuildAppError.GENERIC_WITH_BUILD_ID

        # Grab the format values from the exception in case it contains
        format_values = exc.format_values if hasattr(exc, "format_values") else None

        # Attach the notification to the build.
        self.data.api_client.notifications.post(
            {
                "attached_to": f"build/{self.data.build_id}",
                "message_id": message_id,
                "format_values": format_values,
            }
        )

        # Send notifications for unhandled errors
        if message_id not in self.exceptions_without_notifications:
            send_build_notifications.delay(
                version_pk=self.data.version.id,
                build_pk=self.data.build_id,
                event=WebHookEvent.BUILD_FAILED,
            )

        # NOTE: we should always report the build status on exceptions,
        # otherwise the status will be always marked as "pending".
        if message_id not in self.exceptions_without_external_build_status:
            status = BUILD_STATUS_FAILURE
            send_build_status.delay(
                build_pk=self.data.build_id,
                commit=self.data.build["commit"],
                status=status,
            )

        # Trigger task to check number of failed builds and disable the project if needed (only for community)
        if not settings.ALLOW_PRIVATE_REPOS:
            check_and_disable_project_for_consecutive_failed_builds.delay(
                project_slug=self.data.project.slug,
                version_slug=self.data.version.slug,
            )

        # Update build object
        self.data.build["success"] = False

    def set_valid_clone(self):
        """Mark on the project that it has been cloned properly."""
        self.data.api_client.project(self.data.project.pk).patch({"has_valid_clone": True})
        self.data.project.has_valid_clone = True

    def on_retry(self, exc, task_id, args, kwargs, einfo):
        """
        Celery helper called when the task is retried.

        This happens when any of the exceptions defined in ``autoretry_for``
        argument is raised or when ``self.retry`` is called from inside the
        task.

        See https://docs.celeryproject.org/en/master/userguide/tasks.html#retrying
        """
        logger.info("Retrying this task.")

        if isinstance(exc, BuildMaxConcurrencyError):
            logger.warning(
                "Delaying tasks due to concurrency limit.",
                project_slug=self.data.project.slug,
                version_slug=self.data.version.slug,
            )

            # Grab the format values from the exception in case it contains
            format_values = exc.format_values if hasattr(exc, "format_values") else None
            self.data.api_client.notifications.post(
                {
                    "attached_to": f"build/{self.data.build_id}",
                    "message_id": BuildMaxConcurrencyError.LIMIT_REACHED,
                    "format_values": format_values,
                }
            )

        # Always update the build on retry
        self.data.build["state"] = BUILD_STATE_TRIGGERED
        self._update_build()

    def after_return(self, status, retval, task_id, args, kwargs, einfo):
        """
        Celery handler to be executed after a task runs.

        .. note::

           This handler is called even if the task has failed,
           so some attributes from the `self.data` object may not be defined.
        """
        # Update build object
        self.data.build["length"] = (timezone.now() - self.data.start_time).seconds

        # The state key might not be defined
        # previous to finishing the task.
        if self.data.build.get("state") not in BUILD_FINAL_STATES:
            self.data.build["state"] = BUILD_STATE_FINISHED

        self._update_build()

        # TODO: just move this here, we don't need a signal for this.
        # Be defensive with the signal, so if a listener fails we still clean up
        try:
            build_complete.send(sender=Build, build=self.data.build)
        except Exception:
            logger.exception("Error during build_complete", exc_info=True)

        if self.data.version:
            clean_build(self.data.version)

        try:
            self.data.api_client.revoke.post()
        except Exception:
            logger.exception("Failed to revoke build api key.", exc_info=True)

        # Disable scale-in protection on this instance
        set_builder_scale_in_protection.delay(
            build_id=self.data.build_id,
            builder=socket.gethostname(),
            protected_from_scale_in=False,
        )

        logger.info(
            "Build finished.",
            length=self.data.build["length"],
            success=self.data.build["success"],
        )

        if self.data.project and self.data.project.has_feature(
            Feature.TERMINATE_INSTANCE_ON_BUILD_FINISH
        ):
            if settings.RTD_DOCKER_COMPOSE:
                logger.info(
                    "Running development environment. Skipping instance termination.",
                )
                return

            # Stop consuming new tasks first so this worker doesn't grab a
            # build that would be killed mid-flight when the instance is
            # terminated.
            logger.info(
                "Stopping consumption of new tasks before terminating the instance...",
            )
            stop_consuming_tasks_and_terminate(build_id=self.data.build_id)

    def _log_directory_size(self, directory, media_type):
        try:
            output = subprocess.check_output(["du", "--summarize", "-m", "--", directory])
            # The output is something like: "5\t/path/to/directory".
            directory_size = int(output.decode().split()[0])
            logger.info(
                "Build artifacts directory size.",
                directory=directory,
                size=directory_size,  # Size in mega bytes
                media_type=media_type,
            )
        except Exception:
            logger.info(
                "Error getting build artifacts directory size.",
                exc_info=True,
            )


process_uploaded_build = app.register_task(ProcessUploadedBuildTask())
