import datetime
import signal
import socket
import subprocess
from dataclasses import dataclass
from dataclasses import field
from pathlib import Path

import structlog
from celery import Task
from celery.exceptions import SoftTimeLimitExceeded
from django.conf import settings
from django.utils import timezone
from slumber import API

from readthedocs.api.v2.client import setup_api
from readthedocs.builds.constants import ARTIFACT_TYPES
from readthedocs.builds.constants import ARTIFACT_TYPES_WITHOUT_MULTIPLE_FILES_SUPPORT
from readthedocs.builds.constants import BUILD_FINAL_STATES
from readthedocs.builds.constants import BUILD_STATE_BUILDING
from readthedocs.builds.constants import BUILD_STATE_CANCELLED
from readthedocs.builds.constants import BUILD_STATE_CLONING
from readthedocs.builds.constants import BUILD_STATE_FINISHED
from readthedocs.builds.constants import BUILD_STATE_TRIGGERED
from readthedocs.builds.constants import BUILD_STATE_UPLOADING
from readthedocs.builds.constants import BUILD_STATUS_FAILURE
from readthedocs.builds.constants import BUILD_STATUS_SUCCESS
from readthedocs.builds.constants import UNDELETABLE_ARTIFACT_TYPES
from readthedocs.builds.models import APIVersion
from readthedocs.builds.tasks import check_and_disable_project_for_consecutive_failed_builds
from readthedocs.builds.tasks import send_build_notifications
from readthedocs.builds.tasks import send_build_status
from readthedocs.doc_builder.environments import DockerBuildEnvironment
from readthedocs.doc_builder.exceptions import BuildAppError
from readthedocs.doc_builder.exceptions import BuildCancelled
from readthedocs.doc_builder.exceptions import BuildUserError
from readthedocs.projects.models import APIProject
from readthedocs.projects.models import Feature
from readthedocs.projects.models import WebHookEvent
from readthedocs.projects.tasks.search import index_build
from readthedocs.projects.tasks.storage import StorageType
from readthedocs.projects.tasks.storage import get_storage
from readthedocs.projects.tasks.utils import BuildRequest
from readthedocs.projects.tasks.utils import clean_build
from readthedocs.projects.tasks.utils import set_builder_scale_in_protection
from readthedocs.projects.tasks.utils import stop_consuming_tasks_and_terminate
from readthedocs.worker import app


logger = structlog.get_logger(__name__)


@dataclass(slots=True)
class TaskData:
    build_pk: int | None = None
    start_time: datetime.datetime = field(default_factory=timezone.now)
    api_client: API | None = None
    build: dict = field(default_factory=dict)
    version: APIVersion | None = None
    project: APIProject | None = None


class ProcessUploadedBuildTask(Task):
    name = __name__ + ".process_uploaded_build"
    # Retry only if something from our side failed.
    max_retries = 10
    default_retry_delay = 1 * 60  # 1 minute in seconds
    ignore_result = True

    # Expected exceptions that will be logged as info only and not retried.
    # These exceptions are not sent to Sentry either because we are using
    # ``SENTRY_CELERY_IGNORE_EXPECTED=True``.
    #
    # All exceptions generated by a user miss-configuration should be listed here.
    throws = [
        BuildUserError,
        BuildCancelled,
        SoftTimeLimitExceeded,
    ]
    autoretry_for = [
        BuildAppError,
    ]

    acks_late = True
    track_started = True

    time_limit = settings.RTD_UPLOAD_PROCESS_UPLOAD_TIME_LIMIT
    soft_time_limit = settings.RTD_UPLOAD_PROCESS_UPLOAD_SOFT_TIME_LIMIT

    Request = BuildRequest

    def _setup_sigterm(self):
        def sigterm_received(*args, **kwargs):
            logger.warning(
                "SIGTERM received. Waiting for build to stop gracefully after it finishes."
            )

        def sigint_received(*args, **kwargs):
            logger.warning("SIGINT received. Canceling the build running.")

            # Only allow to cancel the build if it's not already uploading the files.
            # This is to protect our users to end up with half of the documentation uploaded.
            # TODO: remove this condition once we implement "Atomic Uploads"
            if self.data.build.get("state") == BUILD_STATE_UPLOADING:
                logger.warning('Ignoring cancelling the build at "Uploading" state.')
                return

            raise BuildCancelled(message_id=BuildCancelled.CANCELLED_BY_USER)

        # Do not send the SIGTERM signal to children (pip is automatically killed when
        # receives SIGTERM and make the build to fail one command and stop build)
        signal.signal(signal.SIGTERM, sigterm_received)
        signal.signal(signal.SIGINT, sigint_received)

    def run(self, build_id, build_api_key):
        structlog.contextvars.bind_contextvars(build_id=build_id)
        logger.info("Running task.", name=self.name)

        # Clean the build paths to avoid conflicts with a previous run.
        clean_build()
        self._setup_sigterm()

        builder = socket.gethostname()
        # Enable scale-in protection on this instance
        set_builder_scale_in_protection.delay(
            build_id=build_id,
            builder=builder,
            protected_from_scale_in=True,
        )

        self.data = TaskData(build_pk=build_id)
        self.data.api_client = setup_api(build_api_key)

        # Always reset the build before starting, in case the build was retried.
        self.data.api_client.build(self.data.build_pk).reset.post()
        self.data.build = self.data.api_client.build(build_id).get()
        self.data.build["builder"] = builder
        # Save when the task was executed by a builder
        self.data.build["task_executed_at"] = self.data.start_time

        version_data = self.data.api_client.version(self.data.build["version"]).get()
        self.data.version = APIVersion(**version_data)
        self.data.project = self.data.version.project

        structlog.contextvars.bind_contextvars(
            builder=self.data.build["builder"],
            commit=self.data.build["commit"],
            project_slug=self.data.project.slug,
            version_slug=self.data.version.slug,
        )

        self.data.build["state"] = BUILD_STATE_CLONING
        self._update_build()

        logger.info("Downloading artifacts from storage.")
        command = self._create_command(command="Downloading artifacts from storage")
        command_id = command["id"]

        output_dir = Path(self.data.project.checkout_path(self.data.version.slug))
        zip_destination = output_dir / "artifacts.zip"
        try:
            self._downlad_artifacts_from_storage(zip_destination)
        except Exception as exc:
            logger.exception("Error downloading artifacts from storage")
            message = "Unexpected error downloading artifacts from storage. Try again later."
            self._update_command(
                command_id=command_id,
                output=message,
                exit_code=1,
            )
            raise BuildAppError(
                BuildAppError.GENERIC_WITH_BUILD_ID, exception_message=message
            ) from exc
        else:
            logger.info("Artifacts downloaded from storage.")
            self._update_command(
                command_id=command_id,
                output="Artifacts downloaded from storage.",
                exit_code=0,
            )

        self.data.build["state"] = BUILD_STATE_BUILDING
        self._update_build()

        logger.info("Extracting artifacts.")
        command = self._create_command(command="Extracting artifacts")
        command_id = command["id"]

        local_artifacts_path = output_dir / "_readthedocs"
        try:
            self._extract_artifacts(source=zip_destination, destination=local_artifacts_path)
        except Exception as exc:
            logger.exception("Error extracting artifacts")
            message = "Unexpected error extracting artifacts. Check your build artifacts or try again later."
            self._update_command(
                command_id=command_id,
                output=message,
                exit_code=1,
            )
            raise BuildAppError(
                BuildAppError.GENERIC_WITH_BUILD_ID,
                exception_message=message,
            ) from exc
        else:
            logger.info("Artifacts extracted.")
            self._update_command(command_id=command_id, output="Artifacts extracted.", exit_code=0)

        logger.info("Validating artifacts.")
        command = self._create_command(command="Validating artifacts")
        command_id = command["id"]
        try:
            self._validate_artifacts()
        except BuildUserError:
            message = "Validation failed. See the notification above for more details."
            self._update_command(
                command_id=command_id,
                output=message,
                exit_code=1,
            )
            # Re-reaise, this is a known error.
            raise
        except Exception as exc:
            logger.exception("Error validating artifacts")
            message = (
                "Validation failed unexpectedly. Check your build artifacts or try again later."
            )
            self._update_command(
                command_id=command_id,
                output=message,
                exit_code=1,
            )
            raise BuildAppError(
                BuildAppError.GENERIC_WITH_BUILD_ID,
                exception_message=message,
            ) from exc
        else:
            logger.info("Artifacts validated successfully.")
            self._update_command(
                command_id=command_id,
                output="Artifacts validated successfully.",
                exit_code=0,
            )

        logger.info("Uploading artifacts to storage.")
        self.data.build["state"] = BUILD_STATE_UPLOADING
        self._update_build()

        logger.info("Extracting artifacts.")
        command = self._create_command(command="Syncing artifacts to storage")
        command_id = command["id"]

        try:
            self._sync_artifacts_to_storage()
        except Exception as exc:
            logger.exception("Error syncing artifacts to storage")
            message = "Unexpected error syncing artifacts to storage. Try again later."
            self._update_command(
                command_id=command_id,
                output=message,
                exit_code=1,
            )
            raise BuildAppError(
                BuildAppError.GENERIC_WITH_BUILD_ID,
                exception_message=message,
            ) from exc
        else:
            logger.info("Artifacts synced to storage.")
            self._update_command(
                command_id=command_id,
                output="Artifacts synced to storage.",
                exit_code=0,
            )

        self.data.build["state"] = BUILD_STATE_FINISHED
        self.data.build["success"] = True
        self._update_build()

        try:
            self._run_post_success_actions()
        except Exception:
            logger.exception("Error running post success actions.")

    def _run_post_success_actions(self):
        index_build.delay(build_id=self.data.build_pk)

        # Check if the project is spam
        if "readthedocsext.spamfighting" in settings.INSTALLED_APPS:
            from readthedocsext.spamfighting.tasks import (  # noqa
                spam_check_after_build_complete,
            )

            spam_check_after_build_complete.delay(build_id=self.data.build_pk)

        send_build_notifications.delay(
            version_pk=self.data.version.id,
            build_pk=self.data.build_pk,
            event=WebHookEvent.BUILD_PASSED,
        )
        send_build_status.delay(
            build_pk=self.data.build_pk,
            commit=self.data.build["commit"],
            status=BUILD_STATUS_SUCCESS,
        )

    def _update_build(self):
        # Nothing to update.
        if not self.data.build:
            return

        self.data.api_client.build(self.data.build_pk).patch(self.data.build)

    def on_failure(self, exc, task_id, args, kwargs, einfo):
        """
        Celery handler to be executed when a task fails.

        Updates build data, adds tasks to send build notifications.

        .. note::

           Since the task has failed, some attributes from the `self.data`
           object may not be defined.
        """
        logger.info("Task failed.")

        message_id = None

        # Known errors in our application code (e.g. we couldn't connect to Docker, API request failed, etc)
        # or related to user artifacts (no index file, more than one PDF file, etc).
        if isinstance(exc, (BuildAppError, BuildUserError)):
            message_id = exc.message_id

        # If the build was cancelled, set the state to cancelled.
        if isinstance(exc, BuildCancelled):
            self.data.build["state"] = BUILD_STATE_CANCELLED

        if isinstance(exc, SoftTimeLimitExceeded):
            logger.info("Soft time limit exceeded.")
            message_id = BuildUserError.BUILD_TIME_OUT

        if not message_id:
            # We don't know what happened in the build. Log the exception and
            # report a generic notification to the user.
            logger.error("Build failed with unhandled exception.", exc_info=exc)
            message_id = BuildAppError.GENERIC_WITH_BUILD_ID

        # Grab the format values from the exception if available.
        format_values = getattr(exc, "format_values", None) or {}

        # Attach the notification to the build.
        self.data.api_client.notifications.post(
            {
                "attached_to": f"build/{self.data.build_pk}",
                "message_id": message_id,
                "format_values": format_values,
            }
        )

        # Update build object
        self.data.build["success"] = False
        self._update_build()

        try:
            self._run_post_failure_actions()
        except Exception:
            logger.exception("Error running post failure actions.")

    def _run_post_failure_actions(self):
        # Send notifications for unhandled errors,
        # execpt if the build was cancelled by the user.
        if self.data.build.get("state") != BUILD_STATE_CANCELLED:
            send_build_notifications.delay(
                version_pk=self.data.version.id,
                build_pk=self.data.build_pk,
                event=WebHookEvent.BUILD_FAILED,
            )

        # Send commit status.
        if self.data.build:
            send_build_status.delay(
                build_pk=self.data.build_pk,
                commit=self.data.build["commit"],
                status=BUILD_STATUS_FAILURE,
            )

        # Trigger task to check number of failed builds and disable the project if needed (only for community).
        if not settings.ALLOW_PRIVATE_REPOS:
            check_and_disable_project_for_consecutive_failed_builds.delay(
                project_slug=self.data.project.slug,
                version_slug=self.data.version.slug,
            )

    def on_retry(self, exc, task_id, args, kwargs, einfo):
        """
        Celery helper called when the task is retried.

        This happens when any of the exceptions defined in ``autoretry_for``
        argument is raised or when ``self.retry`` is called from inside the
        task.

        See https://docs.celeryproject.org/en/master/userguide/tasks.html#retrying
        """
        logger.info("Retrying this task.")
        # Always update the build on retry
        self.data.build["state"] = BUILD_STATE_TRIGGERED
        self._update_build()

    def after_return(self, status, retval, task_id, args, kwargs, einfo):
        """
        Celery handler to be executed after a task runs.

        .. note::

           This handler is called even if the task has failed,
           so some attributes from the `self.data` object may not be defined.
        """
        # Update build object
        self.data.build["length"] = (timezone.now() - self.data.start_time).seconds

        # The state key might not be defined
        # previous to finishing the task.
        if self.data.build.get("state") not in BUILD_FINAL_STATES:
            self.data.build["state"] = BUILD_STATE_FINISHED

        self._update_build()

        clean_build()

        try:
            self.data.api_client.revoke.post()
        except Exception:
            logger.exception("Failed to revoke build api key.")

        # Disable scale-in protection on this instance
        set_builder_scale_in_protection.delay(
            build_id=self.data.build_pk,
            builder=socket.gethostname(),
            protected_from_scale_in=False,
        )

        logger.info(
            "Build finished.",
            length=self.data.build["length"],
            success=self.data.build.get("success"),
        )

        if self.data.project and self.data.project.has_feature(
            Feature.TERMINATE_INSTANCE_ON_BUILD_FINISH
        ):
            if settings.RTD_DOCKER_COMPOSE:
                logger.info(
                    "Running development environment. Skipping instance termination.",
                )
                return

            logger.info(
                "Stopping consumption of new tasks and terminating instance...",
            )
            stop_consuming_tasks_and_terminate(build_id=self.data.build_pk)

    def _log_directory_size(self, directory, artifact_type):
        try:
            output = subprocess.check_output(["du", "--summarize", "-m", "--", directory])
            # The output is something like: "5\t/path/to/directory".
            directory_size = int(output.decode().split()[0])
            logger.info(
                "Build artifacts directory size.",
                directory=directory,
                # Size in mega bytes
                size=directory_size,
                artifact_type=artifact_type,
            )
        except Exception:
            logger.exception("Error getting build artifacts directory size.")

    def _downlad_artifacts_from_storage(self, destination):
        build_uploads_storage = get_storage(
            build_id=self.data.build_pk,
            api_client=self.data.api_client,
            storage_type=StorageType.build_uploads,
        )
        destination.parent.mkdir(parents=True, exist_ok=True)
        storage_path = self.data.build["uploaded_artifacts_storage_path"]
        with build_uploads_storage.open(storage_path, "rb") as artifacts_file:
            with destination.open("wb") as local_file:
                local_file.write(artifacts_file.read())

    def _extract_artifacts(self, source, destination):
        environment = DockerBuildEnvironment(
            project=self.data.project,
            version=self.data.version,
            build=self.data.build,
            container_image=settings.RTD_DOCKER_CLONE_IMAGE,
            api_client=self.data.api_client,
        )
        with environment:
            result = environment.run(
                "unzip",
                str(source),
                "-d",
                str(destination),
                # cwd=str(output_dir),
                record=False,
            )

        if result.exit_code != 0:
            logger.error(
                "Error extracting artifacts.",
                exit_code=result.exit_code,
                output=result.output,
            )
            raise BuildAppError(BuildAppError.GENERIC_WITH_BUILD_ID)

    def _validate_artifacts(self):
        for artifact_type in ARTIFACT_TYPES:
            # Skip json, we aren't using it, nor allowing it.
            # TODO: we should just remove it from the list.
            if artifact_type == "json":
                continue

            artifact_path = Path(
                self.data.project.artifact_path(
                    version=self.data.version.slug,
                    type_=artifact_type,
                )
            )

            if artifact_path == "html" and not (artifact_path / "index.html").exists():
                raise BuildUserError(BuildUserError.BUILD_OUTPUT_HTML_NO_INDEX_FILE)

            # Only html artifacts are required, the rest are optional.
            if not artifact_path.exists():
                continue

            if not artifact_path.is_dir():
                raise BuildUserError(
                    BuildUserError.BUILD_OUTPUT_IS_NOT_A_DIRECTORY,
                    format_values={"artifact_type": artifact_type},
                )

            if artifact_type in ARTIFACT_TYPES_WITHOUT_MULTIPLE_FILES_SUPPORT:
                # Make sure there is only one file in the artifact directory, and that it has the right extension.
                # NOTE: maybe just check that there is only one file with the right extension, and ignore any other files that may be present.
                files = artifact_path.iterdir()
                # Skip the first file/dir
                file = next(files, None)
                if not file:
                    raise BuildUserError(
                        BuildUserError.BUILD_OUTPUT_HAS_0_FILES,
                        format_values={
                            "artifact_type": artifact_type,
                        },
                    )

                # Check if there is a second file/dir, if so, raise an error.
                if next(files, None):
                    raise BuildUserError(
                        BuildUserError.BUILD_OUTPUT_HAS_MULTIPLE_FILES,
                        format_values={
                            "artifact_type": artifact_type,
                        },
                    )

                if not file.is_file():
                    # TODO: use a better error message.
                    raise BuildUserError(
                        BuildUserError.BUILD_OUTPUT_HAS_0_FILES,
                        format_values={"artifact_type": artifact_type},
                    )

                # Check that we have only one file with the right extension in the artifact directory.
                extension = artifact_type.replace("htmlzip", "zip")
                if file.suffix != f".{extension}":
                    # TODO: use a better error message.
                    raise BuildUserError(
                        BuildUserError.BUILD_OUTPUT_HAS_0_FILES,
                        format_values={
                            "artifact_type": artifact_type,
                        },
                    )

    def _sync_artifacts_to_storage(self):
        build_media_storage = get_storage(
            build_id=self.data.build_pk,
            api_client=self.data.api_client,
            storage_type=StorageType.build_media,
        )
        for artifact_type in ARTIFACT_TYPES:
            # Skip json, we aren't using it, nor allowing it.
            # TODO: we should just remove it from the list.
            if artifact_type == "json":
                continue

            logger.info("Syncing artifacts to storage.", artifact_type=artifact_type)
            artifact_path = Path(
                self.data.project.artifact_path(
                    version=self.data.version.slug,
                    type_=artifact_type,
                )
            )
            artifact_storage_path = self.data.version.get_storage_path(media_type=artifact_type)
            if artifact_path.exists():
                self._log_directory_size(directory=artifact_path, artifact_type=artifact_type)
                # NOTE: use rclone sync only for directories,
                # for single files, like PDF, just upload the file directly
                # under the required name.
                build_media_storage.rclone_sync_directory(
                    source=str(artifact_path),
                    destination=artifact_storage_path,
                )
            elif artifact_path not in UNDELETABLE_ARTIFACT_TYPES:
                build_media_storage.delete_directory(artifact_storage_path)

    def _create_command(self, command):
        return self.data.api_client.command.post(
            {
                "build": self.data.build_pk,
                "command": command,
                "output": "",
                "start_time": timezone.now().isoformat(),
            }
        )

    def _update_command(self, command_id, output, exit_code=0):
        return self.data.api_client.command(command_id).patch(
            {
                "output": output,
                "end_time": timezone.now().isoformat(),
                "exit_code": exit_code,
            }
        )


process_uploaded_build = app.register_task(ProcessUploadedBuildTask())
