# Generated by Django 2.2.16 on 2020-09-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_team_auto_join_email_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='max_concurrent_builds',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum concurrent builds allowed for this organization'),
        ),
    ]
