# Generated by Django 2.2.24 on 2021-07-21 15:36
import autoslug.fields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0004_organization_max_concurrent_builds"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalTeam",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "extra_history_user_id",
                    models.IntegerField(blank=True, db_index=True, null=True, verbose_name="ID"),
                ),
                (
                    "extra_history_user_username",
                    models.CharField(
                        db_index=True,
                        max_length=150,
                        null=True,
                        verbose_name="username",
                    ),
                ),
                (
                    "pub_date",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Publication date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Modified date"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        always_update=True,
                        editable=False,
                        populate_from="name",
                        unique_with=["organization"],
                    ),
                ),
                (
                    "access",
                    models.CharField(
                        choices=[("readonly", "Read-only"), ("admin", "Admin")],
                        default="readonly",
                        max_length=100,
                        verbose_name="Access",
                    ),
                ),
                (
                    "auto_join_email_users",
                    models.BooleanField(
                        default=False,
                        help_text="Auto join users with an organization's email address to this team.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="organizations.Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical team",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalOrganization",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "extra_history_user_id",
                    models.IntegerField(blank=True, db_index=True, null=True, verbose_name="ID"),
                ),
                (
                    "extra_history_user_username",
                    models.CharField(
                        db_index=True,
                        max_length=150,
                        null=True,
                        verbose_name="username",
                    ),
                ),
                (
                    "pub_date",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Publication date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Modified date"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("slug", models.SlugField(max_length=255, verbose_name="Slug")),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="How can we get in touch with you?",
                        max_length=255,
                        null=True,
                        verbose_name="E-mail",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Tell us a little about yourself.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="The main website for your Organization",
                        max_length=255,
                        null=True,
                        verbose_name="Home Page",
                    ),
                ),
                (
                    "disabled",
                    models.BooleanField(
                        default=False,
                        help_text="Docs and builds are disabled for this organization",
                        verbose_name="Disabled",
                    ),
                ),
                (
                    "max_concurrent_builds",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Maximum concurrent builds allowed for this organization",
                    ),
                ),
                (
                    "stripe_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Stripe customer ID",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical organization",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
