# Generated by Django 3.2.13 on 2022-08-10 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0010_alter_customer_balance"),
        ("organizations", "0007_add_extra_history_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorganization",
            name="stripe_customer",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="djstripe.customer",
                verbose_name="Stripe customer",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="stripe_customer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rtd_organization",
                to="djstripe.customer",
                verbose_name="Stripe customer",
            ),
        ),
    ]
