# Generated by Django 3.2.13 on 2022-07-27 21:42
from django.db import migrations
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("organizations", "0008_migrate_old_invitations"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "base_manager_name": "objects",
                "get_latest_by": ["-pub_date"],
                "ordering": ["name"],
                "verbose_name": "organization",
            },
        ),
        migrations.AlterModelOptions(
            name="team",
            options={"base_manager_name": "objects", "verbose_name": "team"},
        ),
    ]
