# Generated by Django 3.2.13 on 2022-08-10 02:21
import django.db.models.deletion
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("djstripe", "0010_alter_customer_balance"),
        ("organizations", "0009_update_meta_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorganization",
            name="stripe_customer",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="djstripe.customer",
                verbose_name="Stripe customer",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="stripe_customer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rtd_organization",
                to="djstripe.customer",
                verbose_name="Stripe customer",
            ),
        ),
    ]
