# Generated by Django 3.2.16 on 2022-11-21 22:52
import django.db.models.deletion
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("djstripe", "0010_alter_customer_balance"),
        ("organizations", "0010_add_stripe_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorganization",
            name="stripe_subscription",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="djstripe.subscription",
                verbose_name="Stripe subscription",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="stripe_subscription",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rtd_organization",
                to="djstripe.subscription",
                verbose_name="Stripe subscription",
            ),
        ),
    ]
