# Generated by Django 4.2.4 on 2023-08-17 22:58
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()
    dependencies = [
        ("organizations", "0011_add_stripe_subscription_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorganization",
            name="never_disable",
            field=models.BooleanField(
                default=False,
                help_text="Never disable this organization, even if its subscription ends",
                null=True,
                verbose_name="Never disable",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="never_disable",
            field=models.BooleanField(
                default=False,
                help_text="Never disable this organization, even if its subscription ends",
                null=True,
                verbose_name="Never disable",
            ),
        ),
    ]
