# Generated by Django 4.2.13 on 2024-07-17 22:41

from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.always()

    dependencies = [
        ("organizations", "0012_add_organization_never_disable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalorganization",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="A short description shown on your profile page",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganization",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Best email address for billing related inquiries",
                max_length=255,
                null=True,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganization",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="The main website for your organization",
                max_length=255,
                null=True,
                verbose_name="Home Page",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="A short description shown on your profile page",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Best email address for billing related inquiries",
                max_length=255,
                null=True,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="The main website for your organization",
                max_length=255,
                null=True,
                verbose_name="Home Page",
            ),
        ),
    ]
