# Generated by Django 4.2.16 on 2024-11-27 19:39
from django.db import migrations
from django.db import models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy()
    dependencies = [
        ("organizations", "0013_update_naming"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalorganization",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical organization",
                "verbose_name_plural": "historical organizations",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalteam",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical team",
                "verbose_name_plural": "historical teams",
            },
        ),
        migrations.AlterField(
            model_name="historicalorganization",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalteam",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
