# Generated by Django 5.2.3 on 2025-06-16 22:17

import readthedocs.organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_remove_unused_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganization',
            name='avatar',
            field=models.TextField(blank=True, help_text='Avatar for your organization (JPG or PNG format, max 500x500px, 750KB)', max_length=100, null=True, verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='organization',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Avatar for your organization (JPG or PNG format, max 500x500px, 750KB)', null=True, storage='usercontent', upload_to=readthedocs.organizations.models._upload_organization_avatar_to, verbose_name='Avatar'),
        ),
    ]
