# Generated by Django 5.2.16 on 2026-07-29 15:44

from django.db import migrations
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.after_deploy()

    dependencies = [
        ("organizations", "0016_organization_avatar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organizationowner",
            options={"ordering": ("pk",)},
        ),
        migrations.AlterModelOptions(
            name="team",
            options={
                "base_manager_name": "objects",
                "ordering": ["name", "pk"],
                "verbose_name": "team",
            },
        ),
    ]
